<?php if ($this->feed) { ?>
<div class="post">
	<h1><?php echo _t('sub.feed.add'); ?></h1>

	<?php if (!$this->load_ok) { ?>
	<p class="alert alert-error"><span class="alert-head"><?php echo _t('gen.short.damn'); ?></span> <?php echo _t('feedback.sub.feed.internal_problem', _url('index', 'logs')); ?></p>
	<?php } ?>

	<form method="post" action="<?php echo _url('feed', 'add'); ?>" autocomplete="off">
		<legend><?php echo _t('sub.feed.informations'); ?></legend>
		<?php if ($this->load_ok) { ?>
		<div class="form-group">
			<label class="group-name"><?php echo _t('sub.feed.title'); ?></label>
			<div class="group-controls">
				<label><?php echo $this->feed->name() ; ?></label>
			</div>
		</div>

		<?php $desc = $this->feed->description(); if ($desc != '') { ?>
		<div class="form-group">
			<label class="group-name"><?php echo _t('sub.feed.description'); ?></label>
			<div class="group-controls">
				<label><?php echo htmlspecialchars($desc, ENT_NOQUOTES, 'UTF-8'); ?></label>
			</div>
		</div>
		<?php } ?>

		<div class="form-group">
			<label class="group-name"><?php echo _t('sub.feed.website'); ?></label>
			<div class="group-controls">
				<?php echo $this->feed->website(); ?>
				<a class="btn" target="_blank" href="<?php echo $this->feed->website(); ?>"><?php echo _i('link'); ?></a>
			</div>
		</div>
		<?php } ?>

		<div class="form-group">
			<label class="group-name" for="url"><?php echo _t('sub.feed.url'); ?></label>
			<div class="group-controls">
				<div class="stick">
					<input type="text" name="url_rss" id="url" class="extend" value="<?php echo $this->feed->url(); ?>" />
					<a class="btn" target="_blank" href="<?php echo $this->feed->url(); ?>"><?php echo _i('link'); ?></a>
				</div>
				<a class="btn" target="_blank" href="http://validator.w3.org/feed/check.cgi?url=<?php echo $this->feed->url(); ?>"><?php echo _t('sub.feed.validator'); ?></a>
			</div>
		</div>
		<div class="form-group">
			<label class="group-name" for="category"><?php echo _t('sub.category'); ?></label>
			<div class="group-controls">
				<select name="category" id="category">
					<?php foreach ($this->categories as $cat) { ?>
					<option value="<?php echo $cat->id(); ?>"<?php echo $cat->id() == 1 ? ' selected="selected"' : ''; ?>>
						<?php echo $cat->name(); ?>
					</option>
					<?php } ?>
					<option value="nc"><?php echo _t('sub.category.new'); ?></option>
				</select>

				<span style="display: none;">
					<input type="text" name="new_category[name]" id="new_category_name" autocomplete="off" placeholder="<?php echo _t('sub.category.new'); ?>" />
				</span>
			</div>
		</div>

		<legend><?php echo _t('sub.feed.auth.http'); ?></legend>
		<?php $auth = $this->feed->httpAuth(false); ?>
		<div class="form-group">
			<label class="group-name" for="http_user"><?php echo _t('sub.feed.auth.username'); ?></label>
			<div class="group-controls">
				<input type="text" name="http_user" id="http_user" class="extend" value="<?php echo empty($auth['username']) ? ' ' : $auth['username']; ?>" autocomplete="off" />
			</div>

			<label class="group-name" for="http_pass"><?php echo _t('sub.feed.auth.password'); ?></label>
			<div class="group-controls">
				<input type="password" name="http_pass" id="http_pass" class="extend" value="<?php echo $auth['password']; ?>" autocomplete="off" />
			</div>

			<div class="group-controls">
				<?php echo _i('help'); ?> <?php echo _t('sub.feed.auth.help'); ?>
			</div>
		</div>

		<div class="form-group form-actions">
			<div class="group-controls">
				<button type="submit" class="btn btn-important"><?php echo _t('gen.action.submit'); ?></button>
				<button type="reset" class="btn"><?php echo _t('gen.action.cancel'); ?></button>
			</div>
		</div>
	</form>
</div>
<?php } ?>
