<?php FreshRSS::preLayout(); ?>
<!DOCTYPE html>
<html class="preview_background" lang="<?= FreshRSS_Context::$user_conf->language ?>" xml:lang="<?= FreshRSS_Context::$user_conf->language ?>">
	<head>
		<?= self::headStyle() ?>
		<script src="<?= Minz_Url::display('/scripts/preview.js?' . @filemtime(PUBLIC_PATH . '/scripts/main.js')) ?>"></script>
	</head>
	<body class="preview_background">
		<?php if ($this->fatalError != '') { ?>
			<p class="warning"><?= $this->fatalError ?></p>
		<?php } else { ?>
			<?php if ($this->selectorSuccess === false) { ?>
				<p class="warning"><?= _t('feedback.sub.feed.selector_preview.no_result') ?></p>
				<hr />
			<?php } ?>
			<div class="preview_center">
				<input type="radio" id="freshrss_rendered" name="freshrss_type" checked="checked" />
				<label class="preview_label" for="freshrss_rendered"><?= _t('sub.feed.selector_preview.show_rendered') ?></label>

				<input type="radio" id="freshrss_raw" name="freshrss_type" />
				<label class="preview_label" for="freshrss_raw"><?= _t('sub.feed.selector_preview.show_raw') ?></label>
			</div>

			<hr />

			<div class="flux_content content" id="freshrss_rendered_view"> <?= $this->htmlContent ?></div>
			<pre id="freshrss_raw_view" hidden="hidden"> <?= htmlspecialchars($this->htmlContent) ?></pre>
		<?php } ?>
	</body>
</html>
