<?php $this->partial ('nav_menu'); ?>

<?php if (!empty($this->entries)) { ?>
<div id="stream" class="global categories">
<?php
	$arUrl = array('c' => 'index', 'a' => 'index', 'params' => array());
	if ($this->conf->view_mode !== 'normal') {
		$arUrl['params']['output'] = 'normal';
	}
	$p = Minz_Request::param('state', '');
	if (($p != '') && ($this->conf->default_view !== $p)) {
		$arUrl['params']['state'] = $p;
	}

	foreach ($this->cat_aside as $cat) {
		$feeds = $cat->feeds ();
		if (!empty ($feeds)) {
?>
	<div class="box-category">
		<div class="category">
			<a data-unread="<?php echo formatNumber($cat->nbNotRead()); ?>" class="btn" href="<?php $arUrl['params']['get'] = 'c_' . $cat->id (); echo Minz_Url::display($arUrl); ?>">
			<?php echo $cat->name(); ?>
			</a>
		</div>
		<ul class="feeds">
			<?php foreach ($feeds as $feed) { ?>
			<?php $not_read = $feed->nbNotRead (); ?>
			<li id="f_<?php echo $feed->id (); ?>" class="item<?php echo $feed->inError () ? ' error' : ''; ?><?php echo $feed->nbEntries () == 0 ? ' empty' : ''; ?>">
				<img class="favicon" src="<?php echo $feed->favicon (); ?>" alt="✇" />
				<a class="feed" data-unread="<?php echo formatNumber($feed->nbNotRead()); ?>" data-priority="<?php echo $feed->priority (); ?>" href="<?php $arUrl['params']['get'] = 'f_' . $feed->id(); echo Minz_Url::display($arUrl); ?>">
				<?php echo $feed->name(); ?>
				</a>
			</li>
			<?php } ?>
		</ul>
	</div>
<?php
		}
	}
?>
</div>

<div id="overlay"></div>
<div id="panel"<?php echo $this->conf->display_posts ? '' : ' class="hide_posts"'; ?>>
	<a class="close" href="#"><?php echo FreshRSS_Themes::icon('close'); ?></a>
</div>

<?php } else { ?>
<div id="stream" class="prompt alert alert-warn global">
	<h2><?php echo _t('no_feed_to_display'); ?></h2>
	<a href="<?php echo _url('configure', 'feed'); ?>"><?php echo _t('think_to_add'); ?></a><br /><br />
</div>
<?php } ?>
