<?php $this->partial ('nav_menu'); ?>

<div id="stream" class="global categories">
<?php
	foreach ($this->cat_aside as $cat) {
		$feeds = $cat->feeds ();
		if (!empty ($feeds)) {
?>
	<div class="box-category">
		<div class="category">
			<a data-unread="<?php echo $cat->nbNotRead (); ?>" class="btn" href="<?php echo _url ('index', 'index', 'get', 'c_' . $cat->id (), 'output', 'normal'); ?>">
			<?php echo $cat->name(); ?>
			</a>
		</div>
		<ul class="feeds">
			<?php foreach ($feeds as $feed) { ?>
			<?php $not_read = $feed->nbNotRead (); ?>
			<li id="f_<?php echo $feed->id (); ?>" class="item<?php echo $feed->inError () ? ' error' : ''; ?><?php echo $feed->nbEntries () == 0 ? ' empty' : ''; ?>">
				<img class="favicon" src="<?php echo $feed->favicon (); ?>" alt="✇" />
				<a class="feed" data-unread="<?php echo $feed->nbNotRead (); ?>" data-priority="<?php echo $feed->priority (); ?>" href="<?php echo _url ('index', 'index', 'get', 'f_' . $feed->id (), 'output', 'normal'); ?>">
				<?php echo $feed->name(); ?>
				</a>
			</li>
			<?php } ?>
		</ul>
	</div>
<?php
		}
	}
?>
</div>

<div id="overlay"></div>
<div id="panel"<?php echo $this->conf->displayPosts () === 'no' ? ' class="hide_posts"' : ''; ?>>
	<a class="close" href="#"><i class="icon i_close">❌</i></a>
</div>