<?php

$this->partial ('aside_flux');
$this->partial ('nav_menu');

if (isset ($this->entryPaginator) && !$this->entryPaginator->isEmpty ()) {
	$items = $this->entryPaginator->items ();
?>

<div id="stream" class="normal">
	<?php
		$display_today = true;
		$display_yesterday = true;
		$display_others = true;
	?>
	<?php foreach ($items as $item) { ?>

	<?php if ($display_today && $item->isDay (Days::TODAY)) { ?>
	<div class="day"><?php echo Translate::t ('today'); ?> - <?php echo timestamptodate (time (), false); ?></div>
	<?php $display_today = false; } ?>
	<?php if ($display_yesterday && $item->isDay (Days::YESTERDAY)) { ?>
	<div class="day"><?php echo Translate::t ('yesterday'); ?> - <?php echo timestamptodate (time () - 86400, false); ?></div>
	<?php $display_yesterday = false; } ?>
	<?php if ($display_others && $item->isDay (Days::BEFORE_YESTERDAY)) { ?>
	<div class="day"><?php echo Translate::t ('before_yesterday'); ?></div>
	<?php $display_others = false; } ?>

	<div class="flux<?php echo !$item->isRead () ? ' not_read' : ''; ?><?php echo $item->isFavorite () ? ' favorite' : ''; ?>" id="flux_<?php echo $item->id (); ?>">
		<ul class="horizontal-list flux_header">
			<?php if (!login_is_conf ($this->conf) || is_logged ()) { ?>
			<li class="item manage">
				<?php if (!$item->isRead ()) { ?>
				<a class="read" href="<?php echo _url ('entry', 'read', 'id', $item->id (), 'is_read', 1); ?>">&nbsp;</a>
				<?php } else { ?>
				<a class="read" href="<?php echo _url ('entry', 'read', 'id', $item->id (), 'is_read', 0); ?>">&nbsp;</a>
				<?php } ?>

				<?php if (!$item->isFavorite ()) { ?>
				<a class="bookmark" href="<?php echo _url ('entry', 'bookmark', 'id', $item->id (), 'is_favorite', 1); ?>">&nbsp;</a>
				<?php } else { ?>
				<a class="bookmark" href="<?php echo _url ('entry', 'bookmark', 'id', $item->id (), 'is_favorite', 0); ?>">&nbsp;</a>
				<?php } ?>
			</li>
			<?php } ?>
			<?php $feed = $item->feed (true); ?>
			<li class="item website"><a href="<?php echo _url ('index', 'index', 'get', 'f_' . $feed->id ()); ?>"><img class="favicon" src="<?php echo $feed->favicon (); ?>" alt="" /> <span><?php echo $feed->name (); ?></span></a></li>
			<li class="item title"><?php echo $item->title (); ?></li>
			<li class="item date"><?php echo $item->date (); ?></li>
			<li class="item link"><a target="_blank" href="<?php echo $item->link (); ?>">&nbsp;</a></li>
		</ul>

		<div class="flux_content">
			<div class="content">
				<h1 class="title"><?php echo $item->title (); ?></h1>
				<?php $author = $item->author (); ?>
				<?php echo $author != '' ? '<div class="author">' . Translate::t ('by_author', $author) . '</div>' : ''; ?>
				<?php
					if($this->conf->lazyload() == 'yes') {
						echo lazyimg($item->content ());
					} else {
						echo $item->content();
					}
				?>
			</div>

			<ul class="horizontal-list bottom">
				<?php if (!login_is_conf ($this->conf) || is_logged ()) { ?>
				<li class="item manage">
					<?php if (!$item->isRead ()) { ?>
					<a class="read" href="<?php echo _url ('entry', 'read', 'id', $item->id (), 'is_read', 1); ?>">&nbsp;</a>
					<?php } else { ?>
					<a class="read" href="<?php echo _url ('entry', 'read', 'id', $item->id (), 'is_read', 0); ?>">&nbsp;</a>
					<?php } ?>

					<?php if (!$item->isFavorite ()) { ?>
					<a class="bookmark" href="<?php echo _url ('entry', 'bookmark', 'id', $item->id (), 'is_favorite', 1); ?>">&nbsp;</a>
					<?php } else { ?>
					<a class="bookmark" href="<?php echo _url ('entry', 'bookmark', 'id', $item->id (), 'is_favorite', 0); ?>">&nbsp;</a>
					<?php } ?>
				</li>
				<?php } ?>
				<li class="item">
					<div class="dropdown">
						<div id="dropdown-share-<?php echo $item->id ();?>" class="dropdown-target"></div>
						<i class="icon i_share"></i> <a class="dropdown-toggle" href="#dropdown-share-<?php echo $item->id ();?>"><?php echo Translate::t ('share'); ?></a>

						<ul class="dropdown-menu">
							<li class="dropdown-close"><a href="#close"><i class="icon i_close"></i></a></li>

							<li class="item"><a href="mailto:?subject=<?php echo $item->title (); ?>&amp;body=J'ai trouvé cet article intéressant, tu peux le lire à cette adresse : <?php echo urlencode($item->link ()); ?>"><?php echo Translate::t ('by_email'); ?></a></li>
							<?php
							$shaarli = $this->conf->urlShaarli ();
							if ($shaarli) {
							?>
							<li class="item"><a target="_blank" href="<?php echo $shaarli . '?post=' . urlencode($item->link ()) . '&amp;title=' . urlencode ($item->title ()) . '&amp;source=bookmarklet'; ?>"><?php echo Translate::t ('on_shaarli'); ?></a></li>
							<?php } ?>
						</ul>
					</div>
				</li>
				<?php $tags = $item->tags(); ?>
				<?php if(!empty($tags)) { ?>
				<li class="item">
					<div class="dropdown">
						<div id="dropdown-tags-<?php echo $item->id ();?>" class="dropdown-target"></div>
						<i class="icon i_tag"></i> <a class="dropdown-toggle" href="#dropdown-tags-<?php echo $item->id ();?>"><?php echo Translate::t ('related_tags'); ?></a>

						<ul class="dropdown-menu">
							<li class="dropdown-close"><a href="#close"><i class="icon i_close"></i></a></li>

							<?php foreach($tags as $tag) { ?>
							<li class="item"><a href="<?php echo _url ('index', 'index', 'search', urlencode ('#' . $tag)); ?>"><?php echo $tag; ?></a></li>
							<?php } ?>
						</ul>
					</div>
				</li>
				<?php } ?>
				<li class="item date"><?php echo $item->date (); ?></li>
				<li class="item link"><a target="_blank" href="<?php echo $item->link (); ?>">&nbsp;</a></li>
			</ul>
		</div>
	</div>
	<?php } ?>
	
	<?php $this->entryPaginator->render ('pagination.phtml', 'next'); ?>
</div>

<?php $this->partial ('nav_entries'); ?>

<?php } else { ?>
<div id="stream" class="alert alert-warn normal">
	<span class="alert-head"><?php echo Translate::t ('no_feed_to_display'); ?></span>
</div>
<?php } ?>