<?php
$this->partial ('nav_menu');

if (!empty($this->entries)) {
	$lazyload = $this->conf->lazyload;
	$content_width = $this->conf->content_width;
?>

<div id="stream" class="reader">
	<?php foreach ($this->entries as $item) { ?>

	<div class="flux<?php echo !$item->isRead () ? ' not_read' : ''; ?><?php echo $item->isFavorite () ? ' favorite' : ''; ?>" id="flux_<?php echo $item->id (); ?>">
		<div class="flux_content">
			<div class="content <?php echo $content_width; ?>">
				<?php
					$feed = FreshRSS_CategoryDAO::findFeed($this->cat_aside, $item->feed ());	//We most likely already have the feed object in cache
					if (empty($feed)) $feed = $item->feed (true);
				?>
				<a href="<?php echo $item->link (); ?>">
					<img class="favicon" src="<?php echo $feed->favicon (); ?>" alt="✇" /> <span><?php echo $feed->name(); ?></span>
				</a>
				<h1 class="title"><?php echo $item->title (); ?></h1>

				<div class="author"><?php
					$author = $item->author();
					echo $author != '' ? Minz_Translate::t('by_author', $author) . ' — ' : '',
						$item->date();
				?></div>

				<?php echo $item->content(); ?>
			</div>
		</div>
	</div>
	<?php } ?>

	<?php $this->renderHelper('pagination'); ?>
</div>

<?php } else { ?>
<div id="stream" class="prompt alert alert-warn reader">
	<h2><?php echo _t('no_feed_to_display'); ?></h2>
	<a href="<?php echo _url('configure', 'feed'); ?>"><?php echo _t('think_to_add'); ?></a><br /><br />
</div>
<?php } ?>
