<?php
$this->partial ('nav_menu');

if (!empty($this->entries)) {
?>

<div id="stream" class="reader">
	<?php foreach ($this->entries as $item) { ?>

	<div class="flux<?php echo !$item->isRead () ? ' not_read' : ''; ?><?php echo $item->isFavorite () ? ' favorite' : ''; ?>" id="flux_<?php echo $item->id (); ?>">
		<div class="flux_content">
			<div class="content">
				<?php
					$feed = FreshRSS_CategoryDAO::findFeed($this->cat_aside, $item->feed ());	//We most likely already have the feed object in cache
					if (empty($feed)) $feed = $item->feed (true);
				?>
				<a href="<?php echo $item->link (); ?>">
					<img class="favicon" src="<?php echo $feed->favicon (); ?>" alt="✇" /> <span><?php echo $feed->name(); ?></span>
				</a>
				<h1 class="title"><?php echo $item->title (); ?></h1>

				<div class="author">
					<?php $author = $item->author (); ?>
					<?php echo $author != '' ? Minz_Translate::t ('by_author', $author) . ' - ' : ''; ?>
					<?php echo $item->date (); ?>
				</div>

				<?php
					if($this->conf->lazyload() == 'yes') {
						echo lazyimg($item->content ());
					} else {
						echo $item->content();
					}
				?>
			</div>
		</div>
	</div>
	<?php } ?>

	<?php $this->renderHelper('pagination'); ?>
</div>

<?php } else { ?>
<div id="stream" class="alert alert-warn reader">
	<span class="alert-head"><?php echo Minz_Translate::t ('no_feed_to_display'); ?></span>
</div>
<?php } ?>