<?php

// Plural-Forms: nplurals=2; plural=(n != 1);
// This file is generated by cli/compile.plurals.php.
// Edit the formula comment and run `make fix-all`.

return array(
	'nplurals' => 2,
	'plural' => static fn (int $n): int => (($n !== 1) ? 1 : 0),
);
