<?php

// Plural-Forms: nplurals=3; plural=(n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);
// This file is generated by cli/compile.plurals.php.
// Edit the formula comment and run `make fix-all`.

return array(
	'nplurals' => 3,
	'plural' => static fn (int $n): int => (((((($n) == (1)) ? 1 : 0)) != 0) ? (0) : ((((((((((((((($n) % 10)) >= (2)) ? 1 : 0)) != 0 && (((((($n) % 10)) <= (4)) ? 1 : 0)) != 0) ? 1 : 0)) != 0 && ((((((((($n) % 100)) < (10)) ? 1 : 0)) != 0 || (((((($n) % 100)) >= (20)) ? 1 : 0)) != 0) ? 1 : 0)) != 0) ? 1 : 0)) != 0) ? (1) : (2)))),
);
