<ul class="nav nav-list aside">
	<li class="nav-header"><?php echo Minz_Translate::t ('stats'); ?></li>
	<li class="item<?php echo Minz_Request::actionName () == 'main' ? ' active' : ''; ?>">
		<a href="<?php echo _url ('stats', 'main'); ?>"><?php echo Minz_Translate::t ('stats_main'); ?></a>
	</li>
	<li class="item<?php echo Minz_Request::actionName () == 'idle' ? ' active' : ''; ?>">
		<a href="<?php echo _url ('stats', 'idle'); ?>"><?php echo Minz_Translate::t ('stats_idle'); ?></a>
	</li>
</ul>
