<div id="main_aside" class="aside">
	<?php if (!login_is_conf ($this->conf) || is_logged ()) { ?>
	<form id="add_rss" method="post" action="<?php echo Url::display (array ('c' => 'feed', 'a' => 'add')); ?>">
		<input type="url" name="url_rss" placeholder="Ajouter un flux RSS" /><!--
		--><input type="submit" value="+" />
	</form>
	<?php } ?>
	
	<ul id="menu">
		<li <?php echo Request::controllerName () == 'index' ? 'class="active"' : ''; ?>>
			<a href="<?php echo Url::display (array ()); ?>">Flux RSS</a>
		</li>
		
		<?php if (!login_is_conf ($this->conf) || is_logged ()) { ?>
		<li <?php echo Request::controllerName () == 'configure' ? 'class="active"' : ''; ?>>
			<a href="<?php echo Url::display (array ('c' => 'configure', 'a' => 'display')); ?>">Configurer</a>
		</li>
		<?php } ?>
		
		<?php if (login_is_conf ($this->conf)) { ?>
		<li>
			<?php if (!is_logged ()) { ?>
			<a id="signin" href="#">Connexion</a>
			<?php } else { ?>
			<a id="signout" href="#">Déconnexion</a>
			<?php } ?>
		</li>
		<?php } ?>
	</ul>
	
	<?php if (isset ($this->cat_aside)) { ?>
	<ul id="categories">
		<li class="all<?php echo !$this->get ? ' active' : ''; ?>">
			<a href="<?php echo Url::display (array ()); ?>">
				Tous
				<span><?php echo $this->nb_total; ?> article<?php echo $this->nb_total > 1 ? 's' : ''; ?> (<span class="nb_not_read"><?php echo $this->nb_not_read; ?></span>)</span>
			</a>
		</li>
		
		<li class="favorites<?php echo $this->get == 'favoris' ? ' active' : ''; ?>"><a href="<?php echo Url::display (array ('params' => array ('get' => 'favoris'))); ?>">Favoris <span><?php echo $this->nb_favorites; ?> article<?php echo $this->nb_favorites > 1 ? 's' : ''; ?></span></a></li>
		
		<?php foreach ($this->cat_aside as $cat) { ?>
		<li class="category<?php echo $this->get == $cat->id () ? ' active' : ''; ?>">
			<a href="<?php echo Url::display (array ('params' => array ('get' => $cat->id ()))); ?>">
				<?php echo $cat->name (); ?>
				<span><?php echo $cat->nbNotRead (); ?> non lu</span>
			</a>
		</li>
		<?php } ?>
	</ul>
	<?php } ?>
</div>
