<div class="aside aside_flux<?php if ($this->conf->hide_read_feeds && ($this->state & FreshRSS_Entry::STATE_NOT_READ) && !($this->state & FreshRSS_Entry::STATE_READ)) echo ' state_unread'; ?>" id="aside_flux">
	<a class="toggle_aside" href="#close"><?php echo _i('close'); ?></a>

	<ul class="categories">
		<?php if ($this->loginOk) { ?>
		<form id="mark-read-aside" method="post" style="display: none"></form>

		<li>
			<div class="stick configure-feeds">
				<a class="btn btn-important" href="<?php echo _url('configure', 'feed'); ?>"><?php echo _t('subscription_management'); ?></a>
				<a class="btn btn-important" href="<?php echo _url('configure', 'categorize'); ?>" title="<?php echo _t('categories_management'); ?>"><?php echo _i('category-white'); ?></a>
			</div>
		</li>
		<?php } elseif (Minz_Configuration::needsLogin()) { ?>
		<li><a href="<?php echo _url('index', 'about'); ?>"><?php echo _t('about_freshrss'); ?></a></li>
		<?php } ?>

		<?php
			$arUrl = array('c' => 'index', 'a' => 'index', 'params' => array());
			if ($this->conf->view_mode !== Minz_Request::param('output', 'normal')) {
				$arUrl['params']['output'] = 'normal';
			}
		?>
		<li>
			<div class="category all<?php echo $this->get_c == 'a' ? ' active' : ''; ?>">
				<a data-unread="<?php echo formatNumber($this->nb_not_read); ?>" class="btn<?php echo $this->get_c == 'a' ? ' active' : ''; ?>" href="<?php echo Minz_Url::display($arUrl); ?>">
					<?php echo _i('all'); ?>
					<?php echo _t('main_stream'); ?>
				</a>
			</div>
		</li>

		<li>
			<div class="category favorites<?php echo $this->get_c == 's' ? ' active' : ''; ?>">
				<a data-unread="<?php echo formatNumber($this->nb_favorites['unread']); ?>" class="btn<?php echo $this->get_c == 's' ? ' active' : ''; ?>" href="<?php $arUrl['params']['get'] = 's'; echo Minz_Url::display($arUrl); ?>">
					<?php echo _i('bookmark'); ?>
					<?php echo _t('favorite_feeds', formatNumber($this->nb_favorites['all'])); ?>
				</a>
			</div>
		</li>

		<?php
		foreach ($this->cat_aside as $cat) {
			$feeds = $cat->feeds();
			if (!empty($feeds)) {
				$c_active = false;
				$c_show = false;
				if ($this->get_c == $cat->id()) {
					$c_active = true;
					if (!$this->conf->display_categories || $this->get_f) {
						$c_show = true;
					}
				}
				?><li data-unread="<?php echo $cat->nbNotRead(); ?>"<?php if ($c_active) echo ' class="active"'; ?>><?php
				?><div class="category stick<?php echo $c_active ? ' active' : ''; ?>"><?php
					?><a data-unread="<?php echo formatNumber($cat->nbNotRead()); ?>" class="btn<?php echo $c_active ? ' active' : ''; ?>" href="<?php $arUrl['params']['get'] = 'c_' . $cat->id(); echo Minz_Url::display($arUrl); ?>"><?php echo $cat->name(); ?></a><?php
					?><a class="btn dropdown-toggle" href="#"><?php echo _i($c_show ? 'up' : 'down'); ?></a><?php
				?></div><?php
				?><ul class="feeds<?php echo $c_show ? ' active' : ''; ?>"><?php
				foreach ($feeds as $feed) {
					$feed_id = $feed->id();
					$nbEntries = $feed->nbEntries();
					$f_active = ($this->get_f == $feed_id);
					?><li id="f_<?php echo $feed_id; ?>" class="item<?php echo $f_active ? ' active' : ''; ?><?php echo $feed->inError() ? ' error' : ''; ?><?php echo $nbEntries == 0 ? ' empty' : ''; ?>" data-unread="<?php echo $feed->nbNotRead(); ?>"><?php
						?><div class="dropdown"><?php
							?><div class="dropdown-target"></div><?php
							?><a class="dropdown-toggle" data-fweb="<?php echo $feed->website(); ?>"><?php echo _i('configure'); ?></a><?php
							/* feed_config_template */
						?></div><?php
						?> <img class="favicon" src="<?php echo $feed->favicon(); ?>" alt="✇" /> <?php
						?><a class="feed" data-unread="<?php echo formatNumber($feed->nbNotRead()); ?>" data-priority="<?php echo $feed->priority(); ?>" href="<?php $arUrl['params']['get'] = 'f_' . $feed_id; echo Minz_Url::display($arUrl); ?>"><?php echo $feed->name(); ?></a><?php
					?></li><?php
				}
				?></ul><?php
				?></li><?php
			}
		} ?>
	</ul>
	<span class="aside_flux_ender"><!-- For fixed menu --></span>
</div>

<script id="feed_config_template" type="text/html">
	<ul class="dropdown-menu">
		<li class="dropdown-close"><a href="#close">❌</a></li>
		<li class="item"><a href="<?php echo _url('index', 'index', 'get', 'f_!!!!!!'); ?>"><?php echo _t('filter'); ?></a></li>
		<?php if ($this->loginOk) { ?>
		<li class="item"><a href="<?php echo _url('stats', 'repartition', 'id', '!!!!!!'); ?>"><?php echo _t('stats'); ?></a></li>
		<?php } ?>
		<li class="item"><a target="_blank" href="http://example.net/"><?php echo _t('see_website'); ?></a></li>
		<?php if ($this->loginOk) { ?>
		<li class="separator"></li>
		<li class="item"><a href="<?php echo _url('configure', 'feed', 'id', '!!!!!!'); ?>"><?php echo _t('administration'); ?></a></li>
		<li class="item"><a href="<?php echo _url('feed', 'actualize', 'id', '!!!!!!'); ?>"><?php echo _t('actualize'); ?></a></li>
		<li class="item">
			<?php $confirm = $this->conf->reading_confirm ? 'confirm' : ''; ?>
			<button class="read_all as-link <?php echo $confirm; ?>"
			        form="mark-read-aside"
			        formaction="<?php echo _url('entry', 'read', 'get', 'f_!!!!!!'); ?>"
			        type="submit"><?php echo _t('mark_read'); ?></button>
		</li>
		<?php } ?>
	</ul>
</script>
