<div id="main_aside" class="aside">
	<form id="add_rss" method="post" action="<?php echo Url::display (array ('c' => 'feed', 'a' => 'add')); ?>">
		<input type="url" name="url_rss" placeholder="Ajouter un flux RSS" />
		<input type="submit" value="+" />
	</form>
	
	<ul id="menu">
		<li <?php echo Request::controllerName () == 'index' ? 'class="active"' : ''; ?>>
			<a href="<?php echo Url::display (array ()); ?>">
				Flux RSS <?php if ($this->nb_not_read > 0) { ?><span>(<?php echo $this->nb_not_read; ?> non lu<?php echo $this->nb_not_read > 1 ? 's' : ''; ?>)</span><?php } ?>
			</a>
			
			<?php if (isset ($this->cat_aside)) { ?>
			<ul id="flux_menu">
				<li><a href="<?php echo Url::display (array ('params' => array ('get' => 'favoris'))); ?>">Favoris</a></li>
				<?php foreach ($this->cat_aside as $cat) { ?>
				<li><a href="<?php echo Url::display (array ('params' => array ('get' => $cat->id ()))); ?>"><?php echo $cat->name (); ?> <span><?php echo $cat->nbFeed (); ?> flux</span></a></li>
				<?php } ?>
			</ul>
			<?php } ?>
		</li>
		<li <?php echo Request::controllerName () == 'configure' ? 'class="active"' : ''; ?>>
			<a href="<?php echo Url::display (array ('c' => 'configure', 'a' => 'flux')); ?>">Configurer</a>
		</li>
		<li>
			<a href="<?php echo Url::display (array ('c' => 'feed', 'a' => 'actualize')); ?>">Mettre les flux à jour</a>
		</li>
	</ul>
</div>

<?php if (Request::controllerName () == 'configure') { ?>
<div class="aside">
	<ul id="menu">
		<li><h2>Configuration</h2></li>
		<li <?php echo Request::actionName () == 'flux' ? 'class="active"' : ''; ?>>
			<a href="<?php echo Url::display (array ('c' => 'configure', 'a' => 'flux')); ?>">Flux RSS</a>
		</li>
		<li <?php echo Request::actionName () == 'categorize' ? 'class="active"' : ''; ?>>
			<a href="<?php echo Url::display (array ('c' => 'configure', 'a' => 'categorize')); ?>">Catégories</a>
		</li>
		<li <?php echo Request::actionName () == 'display' ? 'class="active"' : ''; ?>>
			<a href="<?php echo Url::display (array ('c' => 'configure', 'a' => 'display')); ?>">Affichage</a>
		</li>
		<li <?php echo Request::actionName () == 'importExport' ? 'class="active"' : ''; ?>>
			<a href="<?php echo Url::display (array ('c' => 'configure', 'a' => 'importExport')); ?>">Import / Export OPML</a>
		</li>
		<li <?php echo Request::actionName () == 'shortcut' ? 'class="active"' : ''; ?>>
			<a href="<?php echo Url::display (array ('c' => 'configure', 'a' => 'shortcut')); ?>">Raccourcis</a>
		</li>
	</ul>
</div>
<?php } ?>
