<?php if (login_is_conf ($this->conf)) { ?>
<ul class="nav nav-head nav-login">
	<?php if (!is_logged ()) { ?>
	<li class="item"><i class="icon i_login"></i> <a class="signin" href="#"><?php echo Translate::t ('login'); ?></a></li>
	<?php } else { ?>
	<li class="item"><i class="icon i_logout"></i> <a class="signout" href="#"><?php echo Translate::t ('logout'); ?></a></li>
	<?php } ?>
</ul>
<?php } ?>

<div class="header">
	<div class="item title">
		<h1>
			<a href="<?php echo _url ('index', 'index'); ?>">
				<img class="logo" width="32" height="32" src="<?php echo Url::display ('/themes/icons/icon-32.png'); ?>" alt="[logo]" />
				<?php echo Configuration::title (); ?>
			</a>
		</h1>
	</div>

	<div class="item search">
		<?php if(!login_is_conf ($this->conf) ||
		         is_logged() ||
		         $this->conf->anonAccess() == 'yes') { ?>
		<form action="<?php echo _url ('index', 'index'); ?>" method="get">
			<div class="stick">
				<?php $search = Request::param ('search', ''); ?>
				<input type="text" name="search" id="search" value="<?php echo $search; ?>" placeholder="<?php echo Translate::t ('search'); ?>" />

				<?php $get = Request::param ('get', ''); ?>
				<?php if($get != '') { ?>
				<input type="hidden" name="get" value="<?php echo $get; ?>" />
				<?php } ?>

				<?php $order = Request::param ('order', ''); ?>
				<?php if($order != '') { ?>
				<input type="hidden" name="order" value="<?php echo $order; ?>" />
				<?php } ?>

				<?php $state = Request::param ('state', ''); ?>
				<?php if($state != '') { ?>
				<input type="hidden" name="state" value="<?php echo $state; ?>" />
				<?php } ?>

				<button class="btn" type="submit"><i class="icon i_search"></i></button>
			</div>
		</form>
		<?php } ?>
	</div>

	<?php if (!login_is_conf ($this->conf) || is_logged ()) { ?>
	<div class="item configure">
		<div class="dropdown">
			<div id="dropdown-configure" class="dropdown-target"></div>

			<a class="btn dropdown-toggle" href="#dropdown-configure"><i class="icon i_configure"></i></a>
			<ul class="dropdown-menu">
				<li class="dropdown-close"><a href="#close"> </a></li>
				<li class="dropdown-header"><?php echo Translate::t ('configuration'); ?></li>
				<li class="item"><a href="<?php echo _url ('configure', 'display'); ?>"><?php echo Translate::t ('general_and_reading'); ?></a></li>
				<li class="item"><a href="<?php echo _url ('configure', 'shortcut'); ?>"><?php echo Translate::t ('shortcuts'); ?></a></li>
				<li class="separator"></li>
				<li class="item"><a href="<?php echo _url ('index', 'about'); ?>"><?php echo Translate::t ('about'); ?></a></li>
				<li class="item"><a href="<?php echo _url ('index', 'logs'); ?>"><?php echo Translate::t ('logs'); ?></a></li>
				<?php if (login_is_conf ($this->conf) && is_logged ()) { ?>
				<li class="separator"></li>
				<li class="item"><a class="signout" href="#"><i class="icon i_logout"></i> <?php echo Translate::t ('logout'); ?></a></li>
				<?php } ?>
			</ul>
		</div>
	</div>
	<?php }

	if (login_is_conf ($this->conf) && !is_logged ()) { ?>
	<div class="item configure">
		<i class="icon i_login"></i> <a class="signin" href="#"><?php echo Translate::t ('login'); ?></a>
	</div>
	<?php } ?>
</div>
