<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="initial-scale=1.0">
		<?php echo self::headTitle (); ?>
		<?php echo self::headStyle (); ?>
		<?php echo self::headScript (); ?>
	</head>
	<body>
<div id="global">
	<?php $this->partial ('aside'); ?>
	
	<div id="main">
		<?php $this->render (); ?>
	</div>
</div>

<?php $this->partial ('persona'); ?>

<?php if (isset ($this->notification)) { ?>
<div id="notification" class="<?php echo $this->notification['type']; ?>">
<?php echo $this->notification['content']; ?>
<a class="close" href="">X</a>
</div>
<?php } ?>
	</body>
</html>
