<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="initial-scale=1.0">
		<?php echo self::headTitle (); ?>
		<?php echo self::headStyle (); ?>
		<?php echo self::headScript (); ?>
	</head>
	<body>
<?php $this->partial ('header'); ?>

<div id="global">
	<?php if (Request::controllerName () != 'configure') { ?>
	<?php $this->partial ('aside'); ?>
	<?php } ?>
	
	<div id="main">
		<?php $this->render (); ?>
	</div>
</div>

<?php $this->partial ('persona'); ?>

<?php if (isset ($this->notification)) { ?>
<div class="notification <?php echo $this->notification['type']; ?>">
	<?php echo $this->notification['content']; ?>
	<a class="close" href=""><i class="icon close"></i></a>
</div>
<?php } ?>
	</body>
</html>
