<div <?php if (FreshRSS_Context::$user_conf->hide_nav_entries) echo 'hidden'; ?> > <!-- adding hidden to the ul doesn't have the desired effect -->
	<ul id="nav_entries">
		<li class="item"><a class="previous_entry" href="#"><?php echo _i('prev'); ?></a></li>
		<li class="item"><a class="up" href="#"><?php echo _i('up'); ?></a></li>
		<li class="item"><a class="next_entry" href="#"><?php echo _i('next'); ?></a></li>
	</ul>
</div>