<?php
	declare(strict_types=1);
?>
<nav id="nav_entries">
	<button class="previous_entry" title="<?= _t('gen.action.nav_buttons.prev') ?>"><?= _i('prev') ?></button>
	<button class="link" title="<?= _t('gen.action.nav_buttons.link') ?>"><?= _i('link') ?></button>
	<button class="up" title="<?= _t('gen.action.nav_buttons.up') ?>"><?= _i('up') ?></button>
	<button class="favourite" title="<?= _t('gen.action.nav_buttons.favourite') ?>"><?= _i('non-starred') ?></button>
	<button class="next_entry" title="<?= _t('gen.action.nav_buttons.next') ?>"><?= _i('next') ?></button>
</nav>
