<?php
	declare(strict_types=1);
	/** @var FreshRSS_View $this */
?>
<main class="prompt">
	<h1><?= _t('gen.auth.forgot_password.title') ?></h1>

	<form method="post" action="<?= _url('auth', 'forgotPassword') ?>">
		<input type="hidden" name="_csrf" value="<?= FreshRSS_Auth::csrfToken() ?>" />

		<p><?= _t('gen.auth.forgot_password.help') ?></p>

		<div class="form-group">
			<label for="username"><?= _t('gen.auth.username') ?></label>
			<input type="text" id="username" name="username" autocomplete="username" size="16" required="required"
				pattern="<?= FreshRSS_user_Controller::USERNAME_PATTERN ?>" autofocus="autofocus" autocapitalize="off" />
		</div>

		<div class="form-group form-group-actions">
			<button type="submit" class="btn btn-important"><?= _t('gen.auth.forgot_password.submit') ?></button>
			<a href="<?= _url('auth', 'login') ?>"><?= _t('gen.action.cancel') ?></a>
		</div>
	</form>
</main>
