<?php
	declare(strict_types=1);
	/** @var View $this */

use FreshRss\Minz\User;
use FreshRss\Models\Auth;
use FreshRss\Models\Context;
use FreshRss\Models\View;

?>

<main class="prompt">
	<h1><?= _t('gen.auth.reauth.header') ?></h1>

	<form class="crypto-form" method="post">
		<input type="hidden" name="_csrf" value="<?= Auth::csrfToken() ?>" />
		<input type="hidden" id="username" value="<?= User::name() ?>" />
		<div class="form-group">
			<label for="passwordPlain"><?= _t('gen.auth.password') ?></label>
			<div class="stick">
				<input type="password" id="passwordPlain" class="passwordPlain" required="required" />
				<button type="button" class="btn toggle-password"><?= _i('key') ?></button>
			</div>
			<input type="hidden" id="challenge" name="challenge" />
			<noscript><strong><?= _t('gen.js.should_be_activated') ?></strong></noscript>
		</div>
		<?php
			$reauth_time = Context::systemConf()->reauth_time;
		?>
		<p class="help"><?= _i('help') ?> <?= _t('gen.auth.reauth.tip', (int)($reauth_time / 60)) ?></p>
		<div class="form-group form-group-actions">
			<button type="submit" class="btn btn-important" disabled="disabled">
				<?= _t('gen.auth.login') ?>
			</button>
		</div>
	</form>
</main>

