<div class="prompt">
	<h1><?php echo _t('gen.auth.registration'); ?></h1>

	<form method="post" action="<?php echo _url('user', 'create'); ?>">
		<input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />
		<div>
			<label class="group-name" for="new_user_name"><?php echo _t('gen.auth.username'), '<br />', _i('help'), ' ', _t('gen.auth.username.format'); ?></label>
			<input id="new_user_name" name="new_user_name" type="text" size="16" required="required" autocomplete="off" pattern="<?php echo FreshRSS_user_Controller::USERNAME_PATTERN; ?>" />
		</div>

		<?php if ($this->show_email_field) { ?>
			<div>
				<label class="group-name" for="new_user_email">
					<?php echo _t('gen.auth.email'); ?>
				</label>
				<input id="new_user_email" name="new_user_email" type="email" required />
			</div>
		<?php } ?>

		<div>
			<label class="group-name" for="new_user_passwordPlain"><?php echo _t('gen.auth.password'), '<br />', _i('help'), ' ', _t('gen.auth.password.format'); ?></label>
			<div class="stick">
				<input type="password" id="new_user_passwordPlain" name="new_user_passwordPlain" required="required" autocomplete="new-password" pattern=".{7,}" />
				<a class="btn toggle-password" data-toggle="new_user_passwordPlain"><?php echo _i('key'); ?></a>
			</div>
			<noscript><b><?php echo _t('gen.js.should_be_activated'); ?></b></noscript>
		</div>

		<div>
			<?php
				$redirect_url = urlencode(Minz_Url::display(
					array('c' => 'index', 'a' => 'index'),
					'php', true
				));
			?>
			<input type="hidden" name="r" value="<?php echo $redirect_url; ?>" />
			<button type="submit" class="btn btn-important"><?php echo _t('gen.action.create'); ?></button>
			<a class="btn" href="<?php echo _url('index', 'index'); ?>"><?php echo _t('gen.action.cancel'); ?></a>
		</div>
	</form>

	<p><a href="<?php echo _url('index', 'about'); ?>"><?php echo _t('gen.freshrss.about'); ?></a></p>
</div>
