<?php
	declare(strict_types=1);
	/** @var FreshRSS_View $this */
?>
<main class="prompt">
	<h1><?= _t('gen.auth.reset_password.title') ?></h1>

	<?php if (!$this->reset_token_valid): ?>
		<p><?= _t('gen.auth.reset_password.invalid') ?></p>
		<p><a href="<?= _url('auth', 'forgotPassword') ?>"><?= _t('gen.auth.reset_password.request_new') ?></a></p>
	<?php else: ?>
	<form method="post" action="<?= _url('auth', 'resetPassword') ?>">
		<input type="hidden" name="_csrf" value="<?= FreshRSS_Auth::csrfToken() ?>" />
		<input type="hidden" name="username" value="<?= $this->username ?>" />
		<input type="hidden" name="token" value="<?= $this->reset_token ?>" />

		<div class="form-group">
			<label for="newPasswordPlain"><?= _t('conf.profile.new_password') ?></label>
			<div class="stick">
				<input type="password" id="newPasswordPlain" name="newPasswordPlain" required="required" autocomplete="new-password"
					pattern=".{7,}" autofocus="autofocus" />
				<button type="button" class="btn toggle-password"><?= _i('key') ?></button>
			</div>
			<p class="help"><?= _i('help') ?> <?= _t('gen.auth.password.format') ?></p>
		</div>

		<div class="form-group">
			<label for="confirmPasswordPlain"><?= _t('conf.profile.confirm_new_password') ?></label>
			<div class="stick">
				<input type="password" id="confirmPasswordPlain" name="confirmPasswordPlain" required="required" autocomplete="new-password"
					pattern=".{7,}" />
				<button type="button" class="btn toggle-password"><?= _i('key') ?></button>
			</div>
		</div>

		<div class="form-group form-group-actions">
			<button type="submit" class="btn btn-important"><?= _t('gen.auth.reset_password.submit') ?></button>
		</div>
	</form>
	<?php endif; ?>
</main>
