<?php
	declare(strict_types=1);
	/** @var FreshRSS_View $this */
	$this->partial('aside_subscription');
?>
<main class="post">
	<h1><?= _t('gen.menu.advanced_search') ?></h1>
	<p class="help"><?= _t('gen.search.advanced_search_desc') ?></p>

	<form method="post" action="<?= _url('search', 'submit') ?>">
		<input type="hidden" name="_csrf" value="<?= FreshRSS_Auth::csrfToken() ?>" />

		<fieldset>
			<legend><?= _t('gen.search.basic_criteria') ?></legend>

			<div class="form-group">
				<label class="group-name" for="free_text"><?= _t('gen.search.free_text') ?></label>
				<div class="group-controls">
					<input id="free_text" name="free_text" type="text" placeholder="<?= _t('gen.search.free_text_placeholder') ?>" />
					<p class="help"><?= _t('gen.search.free_text_help') ?></p>
				</div>
			</div>

			<div class="form-group">
				<label class="group-name" for="title"><?= _t('gen.search.title') ?></label>
				<div class="group-controls">
					<input id="title" name="title" type="text" placeholder="<?= _t('gen.search.title_placeholder') ?>" />
					<p class="help"><?= _t('gen.search.title_help') ?></p>
				</div>
			</div>

			<div class="form-group">
				<label class="group-name" for="content"><?= _t('gen.search.content') ?></label>
				<div class="group-controls">
					<input id="content" name="content" type="text" placeholder="<?= _t('gen.search.content_placeholder') ?>" />
					<p class="help"><?= _t('gen.search.content_help') ?></p>
				</div>
			</div>

			<div class="form-group">
				<label class="group-name" for="url"><?= _t('gen.search.url') ?></label>
				<div class="group-controls">
					<input id="url" name="url" type="text" placeholder="<?= _t('gen.search.url_placeholder') ?>" />
					<p class="help"><?= _t('gen.search.url_help') ?></p>
				</div>
			</div>

			<div class="form-group">
				<label class="group-name" for="author"><?= _t('gen.search.author') ?></label>
				<div class="group-controls">
					<input id="author" name="author" type="text" placeholder="<?= _t('gen.search.author_placeholder') ?>" />
					<p class="help"><?= _t('gen.search.author_help') ?></p>
				</div>
			</div>

			<div class="form-group">
				<label class="group-name" for="tags"><?= _t('gen.search.tags') ?></label>
				<div class="group-controls">
					<input id="tags" name="tags" type="text" placeholder="<?= _t('gen.search.tags_placeholder') ?>" />
					<p class="help"><?= _t('gen.search.tags_help') ?></p>
				</div>
			</div>
		</fieldset>

		<fieldset>
			<legend><?= _t('gen.search.date_past') ?></legend>

			<div class="form-group">
				<label class="group-name"><?= _t('gen.search.date_received') ?></label>
				<div class="group-controls">
					<div>
						<label for="date_number"><?= _t('gen.search.date_past') ?>
							<input id="date_number" name="date_number" type="number" min="1" placeholder="1" />
							<select id="date_unit" name="date_unit">
								<option value="H"><?= _t('gen.period.hours') ?></option>
								<option value="D"><?= _t('gen.period.days') ?></option>
								<option value="W"><?= _t('gen.period.weeks') ?></option>
								<option value="M"><?= _t('gen.period.months') ?></option>
								<option value="Y"><?= _t('gen.period.years') ?></option>
							</select>
						</label>
					</div>
				</div>
			</div>

			<div class="form-group">
				<label class="group-name"><?= _t('gen.search.date_published') ?></label>
				<div class="group-controls">
					<div>
						<label for="pubdate_number"><?= _t('gen.search.date_past') ?>
							<input id="pubdate_number" name="pubdate_number" type="number" min="1" placeholder="1" />
							<select id="pubdate_unit" name="pubdate_unit">
								<option value="H"><?= _t('gen.period.hours') ?></option>
								<option value="D"><?= _t('gen.period.days') ?></option>
								<option value="W"><?= _t('gen.period.weeks') ?></option>
								<option value="M"><?= _t('gen.period.months') ?></option>
								<option value="Y"><?= _t('gen.period.years') ?></option>
							</select>
						</label>
					</div>
				</div>
			</div>
		</fieldset>

		<fieldset>
			<legend><?= _t('gen.search.date_range') ?></legend>

			<div class="form-group">
				<label class="group-name"><?= _t('gen.search.date_received') ?></label>
				<div class="group-controls">
					<div>
						<label for="date_from"><?= _t('gen.search.date_from') ?>
							<input id="date_from" name="date_from" type="date" />
						</label>
						<label for="date_to"><?= _t('gen.search.date_to') ?>
							<input id="date_to" name="date_to" type="date" />
						</label>
					</div>
				</div>
			</div>

			<div class="form-group">
				<label class="group-name"><?= _t('gen.search.date_published') ?></label>
				<div class="group-controls">
					<div>
						<label for="pubdate_from"><?= _t('gen.search.date_from') ?>
							<input id="pubdate_from" name="pubdate_from" type="date" />
						</label>
						<label for="pubdate_to"><?= _t('gen.search.date_to') ?>
							<input id="pubdate_to" name="pubdate_to" type="date" />
						</label>
					</div>
				</div>
			</div>
		</fieldset>

		<fieldset>
			<legend><?= _t('gen.search.source_criteria') ?></legend>

			<div class="form-group">
				<label class="group-name" for="feed_ids"><?= _t('gen.search.feeds') ?></label>
				<div class="group-controls">
					<select name="feed_ids[]" id="feed_ids" size="<?= min(10, count($this->feeds)) ?>" multiple="multiple">
						<?php foreach ($this->feeds as $feed) { ?>
						<option value="<?= $feed->id() ?>"><?= $feed->name() ?></option>
						<?php } ?>
					</select>
					<p class="help"><?= _t('gen.search.feeds_help') ?></p>
				</div>
			</div>

			<div class="form-group">
				<label class="group-name" for="category_ids"><?= _t('gen.search.categories') ?></label>
				<div class="group-controls">
					<select name="category_ids[]" id="category_ids" size="<?= min(10, count($this->categories)) ?>" multiple="multiple">
						<?php foreach ($this->categories as $category) { ?>
						<option value="<?= $category->id() ?>"><?= $category->name() ?></option>
						<?php } ?>
					</select>
					<p class="help"><?= _t('gen.search.categories_help') ?></p>
				</div>
			</div>
		</fieldset>

	<fieldset>
		<legend><?= _t('gen.search.label_criteria') ?></legend>

		<div class="form-group">
			<label class="group-name" for="label_ids"><?= _t('gen.search.labels') ?></label>
			<div class="group-controls">
				<select name="label_ids[]" id="label_ids" size="<?= min(10, count($this->labels)) ?>" multiple="multiple">
					<?php foreach ($this->labels as $label) { ?>
					<option value="<?= $label->id() ?>"><?= $label->name() ?></option>
					<?php } ?>
				</select>
				<p class="help"><?= _t('gen.search.labels_help') ?></p>
			</div>
		</div>
	</fieldset>		<fieldset>
			<legend><?= _t('gen.search.advanced_criteria') ?></legend>

			<div class="form-group">
				<label class="group-name" for="user_query"><?= _t('gen.search.user_query') ?></label>
				<div class="group-controls">
					<input id="user_query" name="user_query" type="text" placeholder="<?= _t('gen.search.user_query_placeholder') ?>" />
					<p class="help"><?= _t('gen.search.user_query_help') ?></p>
				</div>
			</div>
		</fieldset>

		<div class="form-group form-actions">
			<div class="group-controls">
				<button type="submit" class="btn btn-important"><?= _t('gen.action.submit') ?></button>
				<button type="reset" class="btn"><?= _t('gen.action.cancel') ?></button>
			</div>
		</div>
	</form>

	<p>
		<a href="https://freshrss.github.io/FreshRSS/en/users/10_filter.html#with-the-search-field" target="_blank">
			<?= _t('gen.search.full_documentation') ?>
		</a>
	</p>
</main>
