<?php
$feeds = array();
foreach ($this->feeds as $feed) {
	$feeds[] = array(
		'url' => Minz\Url::display(array('c' => 'feed', 'a' => 'actualize', 'params' => array('id' => $feed->id(), 'ajax' => '1')), 'php'),
		'title' => $feed->name(),
	);
}
echo json_encode(array(
	'feeds' => $feeds,
	'feedback_no_refresh' => _t('feedback.sub.feed.no_refresh'),
	'feedback_actualize' => _t('feedback.sub.actualize'),
));
