<?php
	$mark = $this->conf->markWhen ();
	echo 'var ',
		'hide_posts=', $this->conf->displayPosts () === 'no' ? 'true,' : 'false,',
		'hide_posts=', $this->conf->displayPosts () === 'no' ? 'true,' : 'false,',
		'auto_mark_article=', $mark['article'] === 'yes' ? 'true,' : 'false,',
		'auto_mark_site=', $mark['site'] === 'yes' ? 'true,' : 'false,',
		'auto_mark_scroll=', $mark['scroll'] === 'yes' ? 'true,' : 'false,',
		'auto_load_more=', $this->conf->autoLoadMore () === 'yes' ? 'true,' : 'false,',
		'does_lazyload=', $this->conf->lazyload() === 'yes' ? 'true' : 'false', ";\n";

	$s = $this->conf->shortcuts ();
	echo 'var shortcuts={',
			'mark_read:"', $s['mark_read'], '",',
			'mark_favorite:"', $s['mark_favorite'], '",',
			'go_website:"', $s['go_website'], '",',
			'prev_entry:"', $s['prev_entry'], '",',
			'next_entry:"', $s['next_entry'], '"',
		"};\n";
