volumes:
  data:
  extensions:

services:
  freshrss:
    image: freshrss/freshrss:latest
    # # Optional build section if you want to build the image locally:
    # build:
    #   # Pick #latest (slow releases) or #edge (rolling release) or a specific release like #1.27.1
    #   context: https://github.com/FreshRSS/FreshRSS.git#latest
    #   dockerfile: Docker/Dockerfile-Alpine
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - data:/var/www/FreshRSS/data
      - extensions:/var/www/FreshRSS/extensions
    environment:
      TZ: Europe/Paris
      CRON_MIN: '3,33'
      TRUSTED_PROXY: 172.16.0.1/12 192.168.0.1/16
      # # Optional parameter to allow sending requests to certain internal hosts. By default all internal requests are blocked
      # # Examples: 127.0.0.1:8080, rss-bridge:80, etc.
      # #   or a CIDR notation: 0.0.0.0/0 (to allow any IPv4), ::/0 (to allow any IPv6)
      # # Setting * disables this check completely, allowing any host to be accessed (unsafe)
      # INTERNAL_HOST_ALLOWLIST: rss-bridge:80 rsshub:1200
    # # Optional healthcheck section:
    # healthcheck:
    #   test: ["CMD", "cli/health.php"]
    #   timeout: 10s
    #   start_period: 60s
    #   start_interval: 11s
    #   interval: 75s
    #   retries: 3
