<?php
	declare(strict_types=1);
	/** @var GravityColorExtension $this */
?>
<form action="<?= _url('extension', 'configure', 'e', urlencode($this->getName())); ?>" method="post">
	<input type="hidden" name="_csrf" value="<?= FreshRSS_Auth::csrfToken() ?>" />

	<div class="form-group">
		<label class="group-name" for="gravity_color"><?= _t('ext.gravity_color.select_gravity_color') ?></label>
		<div class="group-controls">
			<select name="gravity_color" id="gravity_color">
				<option value="<?= htmlentities(FreshRSS_Context::userConf()->gravity_color ?? '') ?>" selected="selected"><?= htmlentities(FreshRSS_Context::userConf()->gravity_color ?? '') ?></option>
				<hr>
				<option value="Blue">Blue</option>
				<option value="Green">Green</option>
				<option value="Orange">Orange</option>
				<option value="Pink">Pink</option>
				<option value="Purple">Purple</option>
				<option value="Red">Red</option>
				<option value="Yellow">Yellow</option>
			</select>
		</div>
	</div>

	<div class="form-group form-actions">
		<div class="group-controls">
			<button type="submit" class="btn btn-important"><?= _t('gen.action.submit') ?></button>
			<button type="reset" class="btn"><?= _t('gen.action.cancel') ?></button>
		</div>
	</div>

</form>
