<?php
declare(strict_types=1);

final class PluralFormsCompiler {
	private const FORMULA_PATTERN = '/^\s*nplurals\s*=\s*(\d+)\s*;\s*plural\s*=\s*(.+?)\s*;\s*$/';

	private const COMMENT_PATTERN = '/^\s*\/\/\s*Plural-Forms:\s*(?P<formula>.+?)\s*$/mi';

	private const COMMENT_PREFIX_PATTERN = '/^\s*\/\/\s*/';

	private const TOKEN_PATTERN = '/\G\s*(\d+|n|==|!=|<=|>=|\|\||&&|[?:()!%+\-*\/<>=])\s*/A';

	/**
	 * Ordered from lowest to highest precedence.
	 * @var list<list<string>>
	 */
	private const BINARY_OPERATORS = [
		['||'],
		['&&'],
		['==', '!='],
		['<', '<=', '>', '>='],
		['+', '-'],
		['*', '/', '%'],
	];

	/**
	 * @return array{formula:string,nplurals:int,lambda:string}
	 */
	public function compileFormula(string $pluralForms): array {
		['formula' => $formula, 'nplurals' => $pluralCount, 'expression' => $expression] =
			$this->parsePluralHeader($pluralForms);
		$expressionTree = $this->parsePluralExpression($expression, $formula);

		return [
			'formula' => $formula,
			'nplurals' => $pluralCount,
			'lambda' => 'static fn (int $n): int => ' . $this->renderPhpExpression($expressionTree),
		];
	}

	public function compileFormulaToLambda(string $pluralForms): string {
		return $this->compileFormula($pluralForms)['lambda'];
	}

	public function compileFile(string $filePath): bool {
		if (!is_file($filePath)) {
			throw new InvalidArgumentException('Plural file not found: ' . $filePath);
		}

		$compiled = $this->compileFormula($this->extractPluralFormsFromFile($filePath));
		$newContent = $this->renderCompiledFile($compiled);
		$currentContent = file_get_contents($filePath);
		if (!is_string($currentContent)) {
			throw new RuntimeException('Unable to read plural file: ' . $filePath);
		}

		if ($currentContent === $newContent) {
			return false;
		}

		if (file_put_contents($filePath, $newContent) === false) {
			throw new RuntimeException('Unable to write plural file: ' . $filePath);
		}

		return true;
	}

	public function compileAll(string $globPattern = I18N_PATH . '/*/plurals.php'): int {
		$files = glob($globPattern) ?: [];
		sort($files, SORT_NATURAL);

		$changed = 0;
		foreach ($files as $filePath) {
			if ($this->compileFile($filePath)) {
				$changed++;
			}
		}

		return $changed;
	}

	private function extractPluralFormsFromFile(string $filePath): string {
		$fileContent = file_get_contents($filePath);
		if (!is_string($fileContent)) {
			throw new RuntimeException('Unable to read plural file: ' . $filePath);
		}

		if (preg_match(self::COMMENT_PATTERN, $fileContent, $matches) === 1) {
			return $this->normalisePluralForms($matches['formula']);
		}

		return $this->extractGetTextPluralFormsFromFile($filePath);
	}

	/**
	 * @param array{formula:string,nplurals:int,lambda:string} $compiled
	 */
	private function renderCompiledFile(array $compiled): string {
		return <<<PHP
<?php

// Plural-Forms: {$compiled['formula']}
// This file is generated by cli/compile.plurals.php.
// Edit the formula comment and run `make fix-all`.

return array(
	'nplurals' => {$compiled['nplurals']},
	'plural' => {$compiled['lambda']},
);

PHP;
	}

	/**
	 * @return array{formula:string,nplurals:int,expression:string}
	 */
	private function parsePluralHeader(string $pluralForms): array {
		$formula = $this->normalisePluralForms($pluralForms);
		if (!preg_match(self::FORMULA_PATTERN, $formula, $matches)) {
			throw new InvalidArgumentException('Invalid plural formula: ' . $formula);
		}

		return [
			'formula' => $formula,
			'nplurals' => max(1, (int)$matches[1]),
			'expression' => $matches[2],
		];
	}

	private function normalisePluralForms(string $pluralForms): string {
		$pluralForms = trim($pluralForms);
		$pluralForms = preg_replace(self::COMMENT_PREFIX_PATTERN, '', $pluralForms) ?? $pluralForms;
		if (preg_match('/^\s*Plural-Forms:\s*(?P<formula>.+?)\s*$/i', $pluralForms, $matches) === 1) {
			$pluralForms = $matches['formula'];
		}

		return trim($pluralForms);
	}

	private function extractGetTextPluralFormsFromFile(string $filePath): string {
		$pluralData = include $filePath;
		$pluralForms = is_array($pluralData) ? ($pluralData['plural-forms'] ?? null) : null;
		if (!is_string($pluralForms) || $pluralForms === '') {
			throw new RuntimeException('No plural formula found in `' . $filePath . '`');
		}

		return $this->normalisePluralForms($pluralForms);
	}

	/**
	 * @return array<string,mixed>
	 */
	private function parsePluralExpression(string $expression, string $pluralForms): array {
		$tokens = $this->tokeniseExpression($expression);
		$position = 0;
		$tree = $this->parsePluralTernary($tokens, $position, $pluralForms);
		if ($position !== count($tokens)) {
			throw new RuntimeException('Unexpected token in plural expression `' . $pluralForms . '`');
		}

		return $tree;
	}

	/**
	 * @param list<string> $tokens
	 * @return array<string,mixed>
	 */
	private function parsePluralTernary(array $tokens, int &$position, string $pluralForms): array {
		$condition = $this->parseBinaryExpression($tokens, $position, $pluralForms, 0);
		if (($tokens[$position] ?? null) !== '?') {
			return $condition;
		}

		$position++;
		$ifTrue = $this->parsePluralTernary($tokens, $position, $pluralForms);
		if (($tokens[$position] ?? null) !== ':') {
			throw new RuntimeException('Missing `:` in plural expression `' . $pluralForms . '`');
		}
		$position++;
		$ifFalse = $this->parsePluralTernary($tokens, $position, $pluralForms);

		return [
			'type' => 'ternary',
			'condition' => $condition,
			'if_true' => $ifTrue,
			'if_false' => $ifFalse,
		];
	}

	/**
	 * @param list<string> $tokens
	 * @return array<string,mixed>
	 */
	private function parseBinaryExpression(array $tokens, int &$position, string $pluralForms, int $precedenceIndex): array {
		if (!isset(self::BINARY_OPERATORS[$precedenceIndex])) {
			return $this->parsePluralUnary($tokens, $position, $pluralForms);
		}

		$node = $this->parseBinaryExpression($tokens, $position, $pluralForms, $precedenceIndex + 1);
		$operators = self::BINARY_OPERATORS[$precedenceIndex];

		while (in_array($tokens[$position] ?? null, $operators, true)) {
			$operator = $tokens[$position];
			$position++;
			$node = [
				'type' => 'binary',
				'operator' => $operator,
				'left' => $node,
				'right' => $this->parseBinaryExpression($tokens, $position, $pluralForms, $precedenceIndex + 1),
			];
		}

		return $node;
	}

	/**
	 * @param list<string> $tokens
	 * @return array<string,mixed>
	 */
	private function parsePluralUnary(array $tokens, int &$position, string $pluralForms): array {
		$token = $tokens[$position] ?? null;
		if ($token === '!' || $token === '-') {
			$position++;
			return [
				'type' => 'unary',
				'operator' => $token,
				'operand' => $this->parsePluralUnary($tokens, $position, $pluralForms),
			];
		}

		return $this->parsePluralPrimary($tokens, $position, $pluralForms);
	}

	/**
	 * @param list<string> $tokens
	 * @return array<string,mixed>
	 */
	private function parsePluralPrimary(array $tokens, int &$position, string $pluralForms): array {
		$token = $tokens[$position] ?? null;
		if ($token === null) {
			throw new RuntimeException('Unexpected end of plural expression `' . $pluralForms . '`');
		}

		if (ctype_digit($token)) {
			$position++;
			return ['type' => 'number', 'value' => (int)$token];
		}

		if ($token === 'n') {
			$position++;
			return ['type' => 'variable'];
		}

		if ($token === '(') {
			$position++;
			$node = $this->parsePluralTernary($tokens, $position, $pluralForms);
			if (($tokens[$position] ?? null) !== ')') {
				throw new RuntimeException('Missing `)` in plural expression `' . $pluralForms . '`');
			}
			$position++;
			return $node;
		}

		throw new RuntimeException('Unexpected token `' . $token . '` in plural expression `' . $pluralForms . '`');
	}

	/**
	 * @param array<string,mixed> $node
	 */
	private function renderPhpExpression(array $node, bool $asCondition = false): string {
		switch ($node['type'] ?? null) {
			case 'number':
				$expression = (string)(is_int($node['value'] ?? null) ? $node['value'] : 0);
				return $asCondition ? '(' . $expression . ' != 0)' : $expression;
			case 'variable':
				return $asCondition ? '($n != 0)' : '$n';
			case 'unary':
				$operator = is_string($node['operator'] ?? null) ? $node['operator'] : '';
				if ($operator === '!') {
					$operand = $this->renderPhpExpression($this->childNode($node, 'operand'), true);
					return $asCondition ? '(!' . $operand . ')' : '((!' . $operand . ') ? 1 : 0)';
				}

				$operand = $this->renderPhpExpression($this->childNode($node, 'operand'));
				$expression = $operator === '-' ? '(-' . $operand . ')' : '(' . $operand . ')';
				return $asCondition ? '(' . $expression . ' != 0)' : $expression;
			case 'ternary':
				$expression = '(' . $this->renderPhpExpression($this->childNode($node, 'condition'), true) . ' ? '
					. $this->renderPhpExpression($this->childNode($node, 'if_true')) . ' : '
					. $this->renderPhpExpression($this->childNode($node, 'if_false')) . ')';
				return $asCondition ? '(' . $expression . ' != 0)' : $expression;
			case 'binary':
				return $this->renderBinaryExpression(
					is_string($node['operator'] ?? null) ? $node['operator'] : '',
					$this->childNode($node, 'left'),
					$this->childNode($node, 'right'),
					$asCondition
				);
			default:
				return $asCondition ? '(0 != 0)' : '0';
		}
	}

	/**
	 * @param array<string,mixed> $leftNode
	 * @param array<string,mixed> $rightNode
	 */
	private function renderBinaryExpression(string $operator, array $leftNode, array $rightNode, bool $asCondition = false): string {
		if (in_array($operator, ['||', '&&'], true)) {
			$expression = '(' . $this->renderPhpExpression($leftNode, true) . ' ' . $operator . ' '
				. $this->renderPhpExpression($rightNode, true) . ')';
			return $asCondition ? $expression : '(' . $expression . ' ? 1 : 0)';
		}

		$left = $this->renderPhpExpression($leftNode);
		$right = $this->renderPhpExpression($rightNode);
		$rightConstant = ($rightNode['type'] ?? null) === 'number' && is_int($rightNode['value'] ?? null)
			? $rightNode['value']
			: null;

		return match ($operator) {
			'==', '!=', '<', '<=', '>', '>=' => $asCondition
				? '(' . $left . ' ' . $operator . ' ' . $right . ')'
				: '((' . $left . ' ' . $operator . ' ' . $right . ') ? 1 : 0)',
			'/' => $asCondition
				? '(' . $this->renderDivisionExpression($left, $right, $rightConstant) . ' != 0)'
				: $this->renderDivisionExpression($left, $right, $rightConstant),
			'%' => $asCondition
				? '(' . $this->renderModuloExpression($left, $right, $rightConstant) . ' != 0)'
				: $this->renderModuloExpression($left, $right, $rightConstant),
			'+', '-', '*' => $asCondition
				? '((' . $left . ' ' . $operator . ' ' . $right . ') != 0)'
				: '(' . $left . ' ' . $operator . ' ' . $right . ')',
			default => $asCondition ? '(0 != 0)' : '0',
		};
	}

	private function renderDivisionExpression(string $left, string $right, ?int $rightConstant): string {
		if ($rightConstant === 0) {
			return '0';
		}

		if ($rightConstant !== null) {
			return 'intdiv(' . $left . ', ' . $rightConstant . ')';
		}

		return '((' . $right . ' == 0) ? 0 : intdiv(' . $left . ', ' . $right . '))';
	}

	private function renderModuloExpression(string $left, string $right, ?int $rightConstant): string {
		if ($rightConstant === 0) {
			return '0';
		}

		if ($rightConstant !== null) {
			return '(' . $left . ' % ' . $rightConstant . ')';
		}

		return '((' . $right . ' == 0) ? 0 : (' . $left . ' % ' . $right . '))';
	}

	/**
	 * @return list<string>
	 */
	private function tokeniseExpression(string $expression): array {
		$tokens = [];
		$offset = 0;
		$length = strlen($expression);

		while ($offset < $length) {
			if (preg_match(self::TOKEN_PATTERN, $expression, $matches, 0, $offset) !== 1) {
				throw new RuntimeException('Unable to parse plural expression near `' . substr($expression, $offset) . '`');
			}
			$tokens[] = $matches[1];
			$offset += strlen($matches[0]);
		}

		return $tokens;
	}

	/**
	 * @param array<string,mixed> $node
	 * @return array<string,mixed>
	 */
	private function childNode(array $node, string $key): array {
		$child = $node[$key] ?? [];
		if (!is_array($child)) {
			return [];
		}

		/** @var array<string,mixed> $child */
		return $child;
	}
}
