<?php
declare(strict_types=1);

final class PluralFormsCompiler {
	/**
	 * @return array{formula:string,nplurals:int,lambda:string}
	 */
	public function compileFormula(string $pluralForms): array {
		$pluralForms = $this->normalisePluralForms($pluralForms);

		if (!preg_match('/^\s*nplurals\s*=\s*(\d+)\s*;\s*plural\s*=\s*(.+?)\s*;\s*$/', $pluralForms, $matches)) {
			throw new InvalidArgumentException('Invalid plural formula: ' . $pluralForms);
		}

		$expressionTree = $this->parsePluralExpression($matches[2], $pluralForms);

		return [
			'formula' => $pluralForms,
			'nplurals' => max(1, (int)$matches[1]),
			'lambda' => 'static fn (int $n): int => ' . $this->renderPhpExpression($expressionTree),
		];
	}

	public function compileFormulaToLambda(string $pluralForms): string {
		return $this->compileFormula($pluralForms)['lambda'];
	}

	public function compileFile(string $filePath): bool {
		if (!is_file($filePath)) {
			throw new InvalidArgumentException('Plural file not found: ' . $filePath);
		}

		$compiled = $this->compileFormula($this->extractPluralFormsFromFile($filePath));
		$newContent = $this->renderCompiledFile($compiled);
		$currentContent = file_get_contents($filePath);
		if (!is_string($currentContent)) {
			throw new RuntimeException('Unable to read plural file: ' . $filePath);
		}

		if ($currentContent === $newContent) {
			return false;
		}

		if (file_put_contents($filePath, $newContent) === false) {
			throw new RuntimeException('Unable to write plural file: ' . $filePath);
		}

		return true;
	}

	public function compileAll(string $globPattern = I18N_PATH . '/*/plurals.php'): int {
		$files = glob($globPattern) ?: [];
		sort($files, SORT_NATURAL);

		$changed = 0;
		foreach ($files as $filePath) {
			if ($this->compileFile($filePath)) {
				$changed++;
			}
		}

		return $changed;
	}

	private function extractPluralFormsFromFile(string $filePath): string {
		$fileContent = file_get_contents($filePath);
		if (!is_string($fileContent)) {
			throw new RuntimeException('Unable to read plural file: ' . $filePath);
		}

		if (preg_match('/^\s*\/\/\s*Plural-Forms:\s*(?P<formula>.+?)\s*$/mi', $fileContent, $matches) === 1) {
			return $this->normalisePluralForms($matches['formula']);
		}

		$pluralData = include $filePath;
		$pluralForms = is_array($pluralData) ? ($pluralData['plural-forms'] ?? null) : null;
		if (!is_string($pluralForms) || $pluralForms === '') {
			throw new RuntimeException('No plural formula found in `' . $filePath . '`');
		}

		return $this->normalisePluralForms($pluralForms);
	}

	/**
	 * @param array{formula:string,nplurals:int,lambda:string} $compiled
	 */
	private function renderCompiledFile(array $compiled): string {
		return <<<PHP
<?php

// Plural-Forms: {$compiled['formula']}
// This file is generated by cli/compile.plurals.php.
// Edit the formula comment and run `make fix-all`.

return array(
	'nplurals' => {$compiled['nplurals']},
	'plural' => {$compiled['lambda']},
);

PHP;
	}

	private function normalisePluralForms(string $pluralForms): string {
		$pluralForms = trim($pluralForms);
		$pluralForms = preg_replace('/^\s*\/\/\s*/', '', $pluralForms) ?? $pluralForms;
		if (preg_match('/^\s*Plural-Forms:\s*(?P<formula>.+?)\s*$/i', $pluralForms, $matches) === 1) {
			$pluralForms = $matches['formula'];
		}

		return trim($pluralForms);
	}

	/**
	 * @return array<string,mixed>
	 */
	private function parsePluralExpression(string $expression, string $pluralForms): array {
		$tokens = [];
		$offset = 0;
		$length = strlen($expression);
		$pattern = '/\G\s*(\d+|n|==|!=|<=|>=|\|\||&&|[?:()!%+\-*\/<>=])\s*/A';

		while ($offset < $length) {
			if (preg_match($pattern, $expression, $matches, 0, $offset) !== 1) {
				throw new RuntimeException('Unable to parse plural expression near `' . substr($expression, $offset) . '`');
			}
			$tokens[] = $matches[1];
			$offset += strlen($matches[0]);
		}

		$position = 0;
		$tree = $this->parsePluralTernary($tokens, $position, $pluralForms);
		if ($position !== count($tokens)) {
			throw new RuntimeException('Unexpected token in plural expression `' . $pluralForms . '`');
		}

		return $tree;
	}

	/**
	 * @param list<string> $tokens
	 * @return array<string,mixed>
	 */
	private function parsePluralTernary(array $tokens, int &$position, string $pluralForms): array {
		$condition = $this->parsePluralLogicalOr($tokens, $position, $pluralForms);
		if (($tokens[$position] ?? null) !== '?') {
			return $condition;
		}

		$position++;
		$ifTrue = $this->parsePluralTernary($tokens, $position, $pluralForms);
		if (($tokens[$position] ?? null) !== ':') {
			throw new RuntimeException('Missing `:` in plural expression `' . $pluralForms . '`');
		}
		$position++;
		$ifFalse = $this->parsePluralTernary($tokens, $position, $pluralForms);

		return [
			'type' => 'ternary',
			'condition' => $condition,
			'if_true' => $ifTrue,
			'if_false' => $ifFalse,
		];
	}

	/**
	 * @param list<string> $tokens
	 * @return array<string,mixed>
	 */
	private function parsePluralLogicalOr(array $tokens, int &$position, string $pluralForms): array {
		$node = $this->parsePluralLogicalAnd($tokens, $position, $pluralForms);
		while (($tokens[$position] ?? null) === '||') {
			$position++;
			$node = [
				'type' => 'binary',
				'operator' => '||',
				'left' => $node,
				'right' => $this->parsePluralLogicalAnd($tokens, $position, $pluralForms),
			];
		}

		return $node;
	}

	/**
	 * @param list<string> $tokens
	 * @return array<string,mixed>
	 */
	private function parsePluralLogicalAnd(array $tokens, int &$position, string $pluralForms): array {
		$node = $this->parsePluralEquality($tokens, $position, $pluralForms);
		while (($tokens[$position] ?? null) === '&&') {
			$position++;
			$node = [
				'type' => 'binary',
				'operator' => '&&',
				'left' => $node,
				'right' => $this->parsePluralEquality($tokens, $position, $pluralForms),
			];
		}

		return $node;
	}

	/**
	 * @param list<string> $tokens
	 * @return array<string,mixed>
	 */
	private function parsePluralEquality(array $tokens, int &$position, string $pluralForms): array {
		$node = $this->parsePluralRelational($tokens, $position, $pluralForms);
		while (in_array($tokens[$position] ?? null, ['==', '!='], true)) {
			$operator = $tokens[$position] ?? '';
			$position++;
			$node = [
				'type' => 'binary',
				'operator' => $operator,
				'left' => $node,
				'right' => $this->parsePluralRelational($tokens, $position, $pluralForms),
			];
		}

		return $node;
	}

	/**
	 * @param list<string> $tokens
	 * @return array<string,mixed>
	 */
	private function parsePluralRelational(array $tokens, int &$position, string $pluralForms): array {
		$node = $this->parsePluralAdditive($tokens, $position, $pluralForms);
		while (in_array($tokens[$position] ?? null, ['<', '<=', '>', '>='], true)) {
			$operator = $tokens[$position] ?? '';
			$position++;
			$node = [
				'type' => 'binary',
				'operator' => $operator,
				'left' => $node,
				'right' => $this->parsePluralAdditive($tokens, $position, $pluralForms),
			];
		}

		return $node;
	}

	/**
	 * @param list<string> $tokens
	 * @return array<string,mixed>
	 */
	private function parsePluralAdditive(array $tokens, int &$position, string $pluralForms): array {
		$node = $this->parsePluralMultiplicative($tokens, $position, $pluralForms);
		while (in_array($tokens[$position] ?? null, ['+', '-'], true)) {
			$operator = $tokens[$position] ?? '';
			$position++;
			$node = [
				'type' => 'binary',
				'operator' => $operator,
				'left' => $node,
				'right' => $this->parsePluralMultiplicative($tokens, $position, $pluralForms),
			];
		}

		return $node;
	}

	/**
	 * @param list<string> $tokens
	 * @return array<string,mixed>
	 */
	private function parsePluralMultiplicative(array $tokens, int &$position, string $pluralForms): array {
		$node = $this->parsePluralUnary($tokens, $position, $pluralForms);
		while (in_array($tokens[$position] ?? null, ['*', '/', '%'], true)) {
			$operator = $tokens[$position] ?? '';
			$position++;
			$node = [
				'type' => 'binary',
				'operator' => $operator,
				'left' => $node,
				'right' => $this->parsePluralUnary($tokens, $position, $pluralForms),
			];
		}

		return $node;
	}

	/**
	 * @param list<string> $tokens
	 * @return array<string,mixed>
	 */
	private function parsePluralUnary(array $tokens, int &$position, string $pluralForms): array {
		$token = $tokens[$position] ?? null;
		if ($token === '!' || $token === '-') {
			$position++;
			return [
				'type' => 'unary',
				'operator' => $token,
				'operand' => $this->parsePluralUnary($tokens, $position, $pluralForms),
			];
		}

		return $this->parsePluralPrimary($tokens, $position, $pluralForms);
	}

	/**
	 * @param list<string> $tokens
	 * @return array<string,mixed>
	 */
	private function parsePluralPrimary(array $tokens, int &$position, string $pluralForms): array {
		$token = $tokens[$position] ?? null;
		if ($token === null) {
			throw new RuntimeException('Unexpected end of plural expression `' . $pluralForms . '`');
		}

		if (ctype_digit($token)) {
			$position++;
			return ['type' => 'number', 'value' => (int)$token];
		}

		if ($token === 'n') {
			$position++;
			return ['type' => 'variable'];
		}

		if ($token === '(') {
			$position++;
			$node = $this->parsePluralTernary($tokens, $position, $pluralForms);
			if (($tokens[$position] ?? null) !== ')') {
				throw new RuntimeException('Missing `)` in plural expression `' . $pluralForms . '`');
			}
			$position++;
			return $node;
		}

		throw new RuntimeException('Unexpected token `' . $token . '` in plural expression `' . $pluralForms . '`');
	}

	/**
	 * @param array<string,mixed> $node
	 */
	private function renderPhpExpression(array $node): string {
		$operator = is_string($node['operator'] ?? null) ? $node['operator'] : '';
		$rightNode = $this->childNode($node, 'right');
		$rightConstant = $this->nodeNumberValue($rightNode);

		switch ($node['type'] ?? null) {
			case 'number':
				return (string)(is_int($node['value'] ?? null) ? $node['value'] : 0);
			case 'variable':
				return '$n';
			case 'unary':
				$operand = $this->renderPhpExpression($this->childNode($node, 'operand'));
				return match ($operator) {
					'!' => '(((' . $operand . ') != 0) ? 0 : 1)',
					'-' => '(-(' . $operand . '))',
					default => '(' . $operand . ')',
				};
			case 'ternary':
				$condition = $this->renderPhpExpression($this->childNode($node, 'condition'));
				$ifTrue = $this->renderPhpExpression($this->childNode($node, 'if_true'));
				$ifFalse = $this->renderPhpExpression($this->childNode($node, 'if_false'));
				return '(((' . $condition . ') != 0) ? (' . $ifTrue . ') : (' . $ifFalse . '))';
			case 'binary':
				$left = $this->renderPhpExpression($this->childNode($node, 'left'));
				$right = $this->renderPhpExpression($rightNode);
				return match ($operator) {
					'||' => '(((' . $left . ') != 0 || (' . $right . ') != 0) ? 1 : 0)',
					'&&' => '(((' . $left . ') != 0 && (' . $right . ') != 0) ? 1 : 0)',
					'==' => '(((' . $left . ') == (' . $right . ')) ? 1 : 0)',
					'!=' => '(((' . $left . ') != (' . $right . ')) ? 1 : 0)',
					'<' => '(((' . $left . ') < (' . $right . ')) ? 1 : 0)',
					'<=' => '(((' . $left . ') <= (' . $right . ')) ? 1 : 0)',
					'>' => '(((' . $left . ') > (' . $right . ')) ? 1 : 0)',
					'>=' => '(((' . $left . ') >= (' . $right . ')) ? 1 : 0)',
					'/' => $rightConstant === 0
						? '0'
						: ($rightConstant !== null
							? 'intdiv((' . $left . '), ' . $rightConstant . ')'
							: '(((' . $right . ') == 0) ? 0 : intdiv((' . $left . '), (' . $right . ')))'),
					'%' => $rightConstant === 0
						? '0'
						: ($rightConstant !== null
							? '((' . $left . ') % ' . $rightConstant . ')'
							: '(((' . $right . ') == 0) ? 0 : ((' . $left . ') % (' . $right . ')))'),
					'+' => '((' . $left . ') + (' . $right . '))',
					'-' => '((' . $left . ') - (' . $right . '))',
					'*' => '((' . $left . ') * (' . $right . '))',
					default => '0',
				};
			default:
				return '0';
		}
	}

	/**
	 * @param array<string,mixed> $node
	 */
	private function nodeNumberValue(array $node): ?int {
		if (($node['type'] ?? null) !== 'number') {
			return null;
		}

		return is_int($node['value'] ?? null) ? $node['value'] : null;
	}

	/**
	 * @param array<string,mixed> $node
	 * @return array<string,mixed>
	 */
	private function childNode(array $node, string $key): array {
		$child = $node[$key] ?? [];
		if (!is_array($child)) {
			return [];
		}

		/** @var array<string,mixed> $child */
		return $child;
	}
}
