<?php
	declare(strict_types=1);
	/** @var ShareByEmail\mailers\View $this */
?>
<div class="post">
    <h1><?= _t('shareByEmail.share.title') ?></h1>

    <p>
        <?= _t('shareByEmail.share.intro', isset($this->entry) ? $this->entry->title() : '') ?>
    </p>

    <form class="sbe-form-share" method="POST">
        <input type="hidden" name="_csrf" value="<?= FreshRSS_Auth::csrfToken() ?>" />

        <div class="form-group">
            <label class="group-name" for="to">
                <?= _t('shareByEmail.share.form.to') ?>
            </label>

            <div class="group-controls">
                <input
                    type="email"
                    name="to"
                    id="to"
                    class="long"
                    placeholder="camille@dupuis-morizeau.com"
                    required
                    autofocus
                    value="<?= $this->to ?>"
                />
            </div>
        </div>

        <div class="form-group">
            <label class="group-name" for="subject">
                <?= _t('shareByEmail.share.form.subject') ?>
            </label>

            <div class="group-controls">
                <input
                    type="text"
                    name="subject"
                    id="subject"
                    class="long"
                    required
                    value="<?= $this->subject ?>"
                />
            </div>
        </div>

        <div class="form-group">
            <label class="group-name" for="content">
                <?= _t('shareByEmail.share.form.content') ?>
            </label>

            <div class="group-controls">
                <textarea
                    name="content"
                    id="content"
                    required
                ><?= $this->content ?></textarea>
            </div>
        </div>

        <div class="form-group form-actions">
            <div class="group-controls">
                <button type="submit" class="btn btn-important">
                    <?= _t('shareByEmail.share.form.send') ?>
                </button>

                <a class="btn" href="<?= _url('index', 'index') ?>">
                    <?= _t('shareByEmail.share.form.cancel') ?>
                </a>
            </div>
        </div>
    </form>
</div>
