<div class="post content">
	<a href="<?php echo _url('index', 'index'); ?>"><?php echo _t('back_to_rss_feeds'); ?></a>

	<h1><?php echo _t('about_freshrss'); ?></h1>

	<dl class="infos">
		<dt><?php echo _t('project_website'); ?></dt>
		<dd><a href="<?php echo FRESHRSS_WEBSITE; ?>"><?php echo FRESHRSS_WEBSITE; ?></a></dd>

		<dt><?php echo _t('lead_developer'); ?></dt>
		<dd><a href="mailto:contact@marienfressinaud.fr">Marien Fressinaud</a> — <a href="http://marienfressinaud.fr"><?php echo _t('website'); ?></a></dd>

		<dt><?php echo _t('bugs_reports'); ?></dt>
		<dd><?php echo _t('github_or_email'); ?></dd>

		<dt><?php echo _t('license'); ?></dt>
		<dd><?php echo _t('agpl3'); ?></dd>

		<dt><?php echo _t('version'); ?></dt>
		<dd><?php echo FRESHRSS_VERSION; ?></dd>
	</dl>

	<p><?php echo _t('freshrss_description'); ?></p>

	<h1><?php echo _t('credits'); ?></h1>
	<p><?php echo _t('credits_content'); ?></p>
</div>
