<?php
	declare(strict_types=1);
	/** @var View $this */

use FreshRss\Models\Category;
use FreshRss\Models\Context;
use FreshRss\Models\Feed;
use FreshRss\Models\UserConfiguration;
use FreshRss\Models\View;

	// Override some layout preferences for the public API output
	Context::userConf()->content_width = 'large';
	Context::userConf()->show_author_date = UserConfiguration::default()->show_author_date;
	Context::userConf()->show_favicons = UserConfiguration::default()->show_favicons;
	Context::userConf()->show_feed_name = UserConfiguration::default()->show_feed_name;
	Context::userConf()->show_tags = UserConfiguration::default()->show_tags;
	Context::userConf()->show_tags_max = UserConfiguration::default()->show_tags_max;
?>
<?php $this->renderHelper('htmlPagination'); ?>
<main id="stream" class="reader api">
	<h2>
		<a href="<?= $this->html_url ?>"><?= View::title() ?></a> ·
		<a class="view-rss" href="<?= $this->rss_url ?>" title="<?= _t('index.menu.rss_view') ?>">
			<?= _i('rss') ?>
		</a>
	</h2>
	<?php
		foreach ($this->entries as $entry):
			$this->entry = $entry;
			$this->feed = $this->feeds[$entry->feedId()] ??
				Category::findFeed($this->categories, $entry->feedId()) ??
				Feed::default();
	?>
		<div class="flux">
			<?php $this->renderHelper('index/article'); ?>
		</div>
	<?php endforeach; ?>
</main>
<?php $this->renderHelper('htmlPagination'); ?>
