<?php

$output = Minz_Request::param ('output', 'normal');

if ($this->loginOk || Minz_Configuration::allowAnonymous()) {
	if ($output === 'normal') {
		$this->renderHelper ('view/normal_view');
	} elseif ($output === 'rss') {
		$this->renderHelper ('view/rss_view');
	} elseif ($output === 'reader') {
		$this->renderHelper ('view/reader_view');
	} elseif ($output === 'global') {
		$this->renderHelper ('view/global_view');
	} else {
		$this->renderHelper ('view/normal_view');
	}
} elseif ($output === 'rss') {
	$token = $this->conf->token;
	$token_param = Minz_Request::param ('token', '');
	$token_is_ok = ($token != '' && $token == $token_param);
	if ($token_is_ok) {
		$this->renderHelper ('view/rss_view');
	} else {
		$this->renderHelper ('view/login');
	}
} else {
	$this->renderHelper ('view/login');
}
