<?php

$output = Minz_Request::param ('output', 'normal');

if ($this->loginOk || Minz_Configuration::allowAnonymous()) {
	if ($output === 'normal') {
		$this->renderHelper ('view/normal_view');
	} elseif ($output === 'rss') {
		$this->renderHelper ('view/rss_view');
	} elseif ($output === 'reader') {
		$this->renderHelper ('view/reader_view');
	} elseif ($output === 'global') {
		$this->renderHelper ('view/global_view');
	} else {
		Minz_Request::_param ('output', 'normal');
		$output = 'normal';
		$this->renderHelper ('view/normal_view');
	}
} elseif ($output === 'rss') {
	// TODO: verification of token and redirection must be done in the
	// controller, not in the view
	$token = $this->conf->token;
	$token_param = Minz_Request::param ('token', '');
	$token_is_ok = ($token != '' && $token == $token_param);
	if ($token_is_ok) {
		$this->renderHelper ('view/rss_view');
	} else {
		Minz_Request::forward(array('c' => 'index', 'a' => 'formLogin'), true);
	}
} else {
	Minz_Request::forward(array('c' => 'index', 'a' => 'formLogin'), true);
}
