<div class="post content">
	<a href="<?php echo _url ('index', 'index'); ?>"><?php echo Minz_Translate::t ('back_to_rss_feeds'); ?></a>

	<h1><?php echo Minz_Translate::t ('logs'); ?></h1>
	<form method="post" action="<?php echo _url ('index', 'logs'); ?>"><p>
		<input type="hidden" name="clearLogs" />
		<button type="submit" class="btn"><?php echo Minz_Translate::t ('clear_logs'); ?></button>
	</p></form>

	<?php $items = $this->logsPaginator->items (); ?>

	<?php if (!empty ($items)) { ?>
	<div class="logs">
		<?php $this->logsPaginator->render ('logs_pagination.phtml', 'page'); ?>

		<?php foreach ($items as $log) { ?>
		<div class="log <?php echo $log->level (); ?>"><span class="date"><?php echo @date ('Y-m-d H:i:s', @strtotime ($log->date ())); ?></span><?php echo htmlspecialchars ($log->info (), ENT_NOQUOTES, 'UTF-8'); ?></div>
		<?php } ?>

		<?php $this->logsPaginator->render ('logs_pagination.phtml','page'); ?>
	</div>
	<?php } else { ?>
	<p class="alert alert-warn"><?php echo Minz_Translate::t ('logs_empty'); ?></p>
	<?php } ?>
</div>
