<div class="prompt">
	<h1><?php echo _t('auth_reset'); ?></h1>

	<?php if (!empty($this->message)) { ?>
	<p class="alert <?php echo $this->message['status'] === 'bad' ? 'alert-error' : 'alert-warn'; ?>">
		<span class="alert-head"><?php echo $this->message['title']; ?></span><br />
		<?php echo $this->message['body']; ?>
	</p>
	<?php } ?>

	<?php if (!$this->no_form) { ?>
	<form id="crypto-form" method="post" action="<?php echo _url('index', 'resetAuth'); ?>">
		<p class="alert alert-warn">
			<span class="alert-head"><?php echo _t('attention'); ?></span><br />
			<?php echo _t('auth_will_reset'); ?>
		</p>

		<div>
			<label for="username"><?php echo _t('username_admin'); ?></label>
			<input type="text" id="username" name="username" size="16" required="required" maxlength="16" pattern="[0-9a-zA-Z]{1,16}" autofocus="autofocus" />
		</div>
		<div>
			<label for="passwordPlain"><?php echo _t('password'); ?></label>
				<input type="password" id="passwordPlain" required="required" />
				<input type="hidden" id="challenge" name="challenge" /><br />
				<noscript><strong><?php echo _t('javascript_should_be_activated'); ?></strong></noscript>
		</div>
		<div>
			<button id="loginButton" type="submit" class="btn btn-important"><?php echo _t('submit'); ?></button>
		</div>
	</form>
	<?php } ?>
</div>
