<?php
	declare(strict_types=1);
	/** @var View $this */

use FreshRss\Models\Auth;
use FreshRss\Models\View;

	if (Auth::hasAccess()) {
		$this->partial('aside_configure');
	}
?>
<main class="post content<?= !Auth::hasAccess() ? ' centered' : ''?>">
	<h1><?= _t('index.tos.title')?></h1>
	<?= $this->terms_of_service ?>
</main>

<?php if (!Auth::hasAccess()) { ?>
<footer class="main-footer">
	<a href="<?= _url('index', 'about') ?>"><?= _t('gen.freshrss.about') ?></a>
</footer>
<?php } ?>
