<?php $this->partial('aside_subscription'); ?>

<div class="post">
	<a href="<?= _url('index', 'index') ?>"><?= _t('gen.action.back_to_rss_feeds') ?></a>

	<form id="add_tag" method="post" action="<?= _url('tag', 'add') ?>" autocomplete="off">
        <legend><?= _t('sub.title.add_label') ?></legend>
		<input type="hidden" name="_csrf" value="<?= FreshRSS_Auth::csrfToken() ?>" />
		<div class="form-group">
			<label class="group-name" for="category"><?= _t('sub.tag.name') ?></label>
			<div class="group-controls">
				<input id="name" name="name" type="text" autocomplete="off"/>
			</div>
		</div>

		<div class="form-group form-actions">
			<div class="group-controls">
				<button type="submit" class="btn btn-important"><?= _t('gen.action.add') ?></button>
			</div>
		</div>
	</form>

	
	<form id="rename_tag" method="post" action="<?= _url('tag', 'rename') ?>" autocomplete="off">
        <legend><?= _t('sub.title.rename_label') ?></legend>
		<input type="hidden" name="_csrf" value="<?= FreshRSS_Auth::csrfToken() ?>" />
		<div class="form-group">
			<label class="group-name" for="category"><?= _t('sub.tag.old_name') ?></label>
			<div class="group-controls">
				<select name="id_tag" id="id_tag">
					<?php foreach ($this->tags as $tag): ?>
						<option value="<?= $tag->id() ?>"><?= $tag->name() ?></option>
					<?php endforeach; ?>
				</select>
			</div>
		</div>
		<div class="form-group">
			<label class="group-name" for="category"><?= _t('sub.tag.new_name') ?></label>
			<div class="group-controls">
				<input id="name" name="name" type="text" autocomplete="off"/>
			</div>
		</div>

		<div class="form-group form-actions">
			<div class="group-controls">
				<button type="submit" class="btn btn-attention confirm"><?= _t('gen.action.rename') ?></button>
			</div>
		</div>
	</form>

	<form id="delete_tag" method="post" action="<?= _url('tag', 'delete') ?>" autocomplete="off">
        <legend><?= _t('sub.title.delete_label') ?></legend>
		<input type="hidden" name="_csrf" value="<?= FreshRSS_Auth::csrfToken() ?>" />
		<div class="form-group">
			<label class="group-name" for="category"><?= _t('sub.tag.name') ?></label>
			<div class="group-controls">
				<select name="id_tag" id="id_tag">
					<?php foreach ($this->tags as $tag): ?>
						<option value="<?= $tag->id() ?>"><?= $tag->name() ?></option>
					<?php endforeach; ?>
				</select>
			</div>
		</div>

		<div class="form-group form-actions">
			<div class="group-controls">
				<button type="submit" class="btn btn-attention confirm"><?= _t('gen.action.remove') ?></button>
			</div>
		</div>
	</form>
</div>
