<?php $this->partial('aside_configure'); ?>

<div class="post">
	<a href="<?php echo _url('index', 'index'); ?>"><?php echo _t('back_to_rss_feeds'); ?></a>

	<form method="post" action="<?php echo _url('users', 'auth'); ?>">
		<legend><?php echo _t('login_configuration'); ?></legend>

		<div class="form-group">
			<label class="group-name" for="current_user"><?php echo _t('current_user'); ?></label>
			<div class="group-controls">
				<input id="current_user" type="text" disabled="disabled" value="<?php echo Minz_Session::param('currentUser', '_'); ?>" />
				<label class="checkbox" for="is_admin">
					<input type="checkbox" id="is_admin" disabled="disabled" <?php echo Minz_Configuration::isAdmin(Minz_Session::param('currentUser', '_')) ? 'checked="checked" ' : ''; ?>/>
					<?php echo _t('is_admin'); ?>
				</label>
			</div>
		</div>

		<div class="form-group">
			<label class="group-name" for="passwordPlain"><?php echo _t('password_form'); ?></label>
			<div class="group-controls">
				<div class="stick">
					<input type="password" id="passwordPlain" name="passwordPlain" autocomplete="off" pattern=".{7,}" <?php echo cryptAvailable() ? '' : 'disabled="disabled" '; ?>/>
					<a class="btn toggle-password"><?php echo _i('key'); ?></a>
				</div>
				<noscript><b><?php echo _t('javascript_should_be_activated'); ?></b></noscript>
			</div>
		</div>

		<?php if (Minz_Configuration::apiEnabled()) { ?>
		<div class="form-group">
			<label class="group-name" for="apiPasswordPlain"><?php echo _t('password_api'); ?></label>
			<div class="group-controls">
				<div class="stick">
					<input type="password" id="apiPasswordPlain" name="apiPasswordPlain" autocomplete="off" pattern=".{7,}" <?php echo cryptAvailable() ? '' : 'disabled="disabled" '; ?>/>
					<a class="btn toggle-password"><?php echo _i('key'); ?></a>
				</div>
			</div>
		</div>
		<?php } ?>

		<div class="form-group">
			<label class="group-name" for="mail_login"><?php echo _t('persona_connection_email'); ?></label>
			<?php $mail = $this->conf->mail_login; ?>
			<div class="group-controls">
				<input type="email" id="mail_login" name="mail_login" class="extend" autocomplete="off" value="<?php echo $mail; ?>" <?php echo Minz_Configuration::isAdmin(Minz_Session::param('currentUser', '_')) ? '' : 'disabled="disabled"'; ?> placeholder="alice@example.net" />
				<noscript><b><?php echo _t('javascript_should_be_activated'); ?></b></noscript>
			</div>
		</div>

		<div class="form-group form-actions">
			<div class="group-controls">
				<button type="submit" class="btn btn-important"><?php echo _t('save'); ?></button>
				<button type="reset" class="btn"><?php echo _t('cancel'); ?></button>
			</div>
		</div>

	<?php if (Minz_Configuration::isAdmin(Minz_Session::param('currentUser', '_'))) { ?>

		<legend><?php echo _t('auth_type'); ?></legend>

		<div class="form-group">
			<label class="group-name" for="auth_type"><?php echo _t('auth_type'); ?></label>
			<div class="group-controls">
				<select id="auth_type" name="auth_type" required="required">
					<?php if (!in_array(Minz_Configuration::authType(), array('form', 'persona', 'http_auth', 'none'))) { ?>
						<option selected="selected"></option>
					<?php } ?>
					<option value="form"<?php echo Minz_Configuration::authType() === 'form' ? ' selected="selected"' : '', cryptAvailable() ? '' : ' disabled="disabled"'; ?>><?php echo _t('auth_form'); ?></option>
					<option value="persona"<?php echo Minz_Configuration::authType() === 'persona' ? ' selected="selected"' : '', $this->conf->mail_login == '' ? ' disabled="disabled"' : ''; ?>><?php echo _t('auth_persona'); ?></option>
					<option value="http_auth"<?php echo Minz_Configuration::authType() === 'http_auth' ? ' selected="selected"' : '', httpAuthUser() == '' ? ' disabled="disabled"' : ''; ?>><?php echo _t('http_auth'); ?> (REMOTE_USER = '<?php echo httpAuthUser(); ?>')</option>
					<option value="none"<?php echo Minz_Configuration::authType() === 'none' ? ' selected="selected"' : ''; ?>><?php echo _t('auth_none'); ?></option>
				</select>
			</div>
		</div>

		<div class="form-group">
			<div class="group-controls">
				<label class="checkbox" for="anon_access">
					<input type="checkbox" name="anon_access" id="anon_access" value="1"<?php echo Minz_Configuration::allowAnonymous() ? ' checked="checked"' : '',
						Minz_Configuration::canLogIn() ? '' : ' disabled="disabled"'; ?> />
					<?php echo _t('allow_anonymous', Minz_Configuration::defaultUser()); ?>
				</label>
			</div>
		</div>

		<div class="form-group">
			<div class="group-controls">
				<label class="checkbox" for="anon_refresh">
					<input type="checkbox" name="anon_refresh" id="anon_refresh" value="1"<?php echo Minz_Configuration::allowAnonymousRefresh() ? ' checked="checked"' : '',
						Minz_Configuration::canLogIn() ? '' : ' disabled="disabled"'; ?> />
					<?php echo _t('allow_anonymous_refresh'); ?>
				</label>
			</div>
		</div>

		<div class="form-group">
			<div class="group-controls">
				<label class="checkbox" for="unsafe_autologin">
					<input type="checkbox" name="unsafe_autologin" id="unsafe_autologin" value="1"<?php echo Minz_Configuration::unsafeAutologinEnabled() ? ' checked="checked"' : '',
						Minz_Configuration::canLogIn() ? '' : ' disabled="disabled"'; ?> />
					<?php echo _t('unsafe_autologin'); ?>
					<kbd>p/i/?a=formLogin&amp;u=Alice&amp;p=1234</kbd>
				</label>
			</div>
		</div>

		<?php if (Minz_Configuration::canLogIn()) { ?>
		<div class="form-group">
			<label class="group-name" for="token"><?php echo _t('auth_token'); ?></label>
			<?php $token = $this->conf->token; ?>
			<div class="group-controls">
				<input type="text" id="token" name="token" value="<?php echo $token; ?>" placeholder="<?php echo _t('blank_to_disable'); ?>"<?php
					echo Minz_Configuration::canLogIn() ? '' : ' disabled="disabled"'; ?> />
				<?php echo _i('help'); ?> <?php echo _t('explain_token', Minz_Url::display(null, 'html', true), $token); ?>
			</div>
		</div>
		<?php } ?>

		<div class="form-group">
			<div class="group-controls">
				<label class="checkbox" for="api_enabled">
					<input type="checkbox" name="api_enabled" id="api_enabled" value="1"<?php echo Minz_Configuration::apiEnabled() ? ' checked="checked"' : '',
						Minz_Configuration::needsLogin() ? '' : ' disabled="disabled"'; ?> />
					<?php echo _t('api_enabled'); ?>
				</label>
			</div>
		</div>

		<div class="form-group form-actions">
			<div class="group-controls">
				<button type="submit" class="btn btn-important"><?php echo _t('save'); ?></button>
				<button type="reset" class="btn"><?php echo _t('cancel'); ?></button>
			</div>
		</div>
	</form>

	<form method="post" action="<?php echo _url('users', 'delete'); ?>">
		<legend><?php echo _t('users'); ?></legend>

		<div class="form-group">
			<label class="group-name" for="users_list"><?php echo _t('users_list'); ?></label>
			<div class="group-controls">
				<select id="users_list" name="username"><?php
					foreach (listUsers() as $user) {
						echo '<option>', $user, '</option>';
					}
				?></select>
			</div>
		</div>
	
		<div class="form-group form-actions">
			<div class="group-controls">
				<button type="submit" class="btn btn-attention confirm"><?php echo _t('delete'); ?></button>
			</div>
		</div>
	</form>

	<form method="post" action="<?php echo _url('users', 'create'); ?>">
		<legend><?php echo _t('create_user'); ?></legend>

		<div class="form-group">
			<label class="group-name" for="new_user_language"><?php echo _t('language'); ?></label>
			<div class="group-controls">
				<select name="new_user_language" id="new_user_language">
				<?php $languages = $this->conf->availableLanguages(); ?>
				<?php foreach ($languages as $short => $lib) { ?>
				<option value="<?php echo $short; ?>"<?php echo $this->conf->language === $short ? ' selected="selected"' : ''; ?>><?php echo $lib; ?></option>
				<?php } ?>
				</select>
			</div>
		</div>

		<div class="form-group">
			<label class="group-name" for="new_user_name"><?php echo _t('username'); ?></label>
			<div class="group-controls">
				<input id="new_user_name" name="new_user_name" type="text" size="16" required="required" maxlength="16" autocomplete="off" pattern="[0-9a-zA-Z]{1,16}" placeholder="demo" />
			</div>
		</div>

		<div class="form-group">
			<label class="group-name" for="new_user_passwordPlain"><?php echo _t('password_form'); ?></label>
			<div class="group-controls">
				<div class="stick">
					<input type="password" id="new_user_passwordPlain" name="new_user_passwordPlain" autocomplete="off" pattern=".{7,}" />
					<a class="btn toggle-password"><?php echo _i('key'); ?></a>
				</div>
				<noscript><b><?php echo _t('javascript_should_be_activated'); ?></b></noscript>
			</div>
		</div>

		<div class="form-group">
			<label class="group-name" for="new_user_email"><?php echo _t('persona_connection_email'); ?></label>
			<?php $mail = $this->conf->mail_login; ?>
			<div class="group-controls">
				<input type="email" id="new_user_email" name="new_user_email" class="extend" autocomplete="off" placeholder="alice@example.net" />
			</div>
		</div>

		<div class="form-group form-actions">
			<div class="group-controls">
				<button type="submit" class="btn btn-important"><?php echo _t('create'); ?></button>
				<button type="reset" class="btn"><?php echo _t('cancel'); ?></button>
			</div>
		</div>

	</form>

	<?php } ?>
</div>
