<?php

// Plural-Forms: nplurals=3; plural=(n==1) ? 0 : (n>=2 && n<=4) ? 1 : 2;
// This file is generated by cli/compile.plurals.php.
// Edit the formula comment and run `make fix-all`.

return array(
	'nplurals' => 3,
	'plural' => static fn (int $n): int => ($n === 1 ? 0 : ($n >= 2 && $n <= 4 ? 1 : 2)),
);
