#!/bin/bash

if [[ "$DOCKERFILE_PATH" == *-ARM ]];
then
	# https://github.com/balena-io/qemu
	# Download a local copy of QEMU on Docker Hub build machine
	curl -LSs 'https://github.com/balena-io/qemu/releases/download/v3.0.0%2Bresin/qemu-3.0.0+resin-arm.tar.gz' | tar -xzv --strip-components=1 --wildcards '*/qemu-*'
fi
