#!/bin/bash

if [[ "$DOCKERFILE_PATH" == *-ARM ]];
then
	# https://github.com/multiarch/qemu-user-static
	# Register qemu-*-static for all supported processors except the current one, but also remove all registered binfmt_misc before
	docker run --rm --privileged multiarch/qemu-user-static:register --reset
fi
