apiVersion: v1
kind: Secret
metadata:
  name: {{ include "freshrss.fullname" . }}
  namespace: {{ include "freshrss.namespace" . }}
  labels:
    {{- include "freshrss.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.oidc.secrets }}
  OIDC_CLIENT_SECRET: {{ .Values.oidc.secrets.clientSecret | b64enc | quote }}

  {{- if .Values.oidc.secrets.clientCryptoKey }}
  OIDC_CLIENT_CRYPTO_KEY: {{ .Values.oidc.secrets.clientCryptoKey | b64enc | quote }}
  {{- else }}
  OIDC_CLIENT_CRYPTO_KEY: {{ include "freshrss.cryptokey" . }}
  {{- end }}

  {{- end }}