apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "name" . }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | default "" }}
stringData:
 {{- if .Values.oidc.secrets }}
  OIDC_CLIENT_SECRET: {{ .Values.oidc.secrets.clientSecret | default "" }}
  OIDC_CLIENT_CRYPTO_KEY: {{ .Values.oidc.secrets.clientCryptoKey | default "" }}
  {{- end }}