<div class="post">
	<h1>
		<?php echo $this->extension->getName(); ?> (<?php echo $this->extension->getVersion(); ?>) —
		<?php echo $this->extension->isEnabled() ? _t('admin.extensions.enabled')
		                                         : _t('admin.extensions.disabled'); ?>
	</h1>

	<p class="alert alert-warn"><?php echo $this->extension->getDescription(); ?> — <?php echo _t('gen.short.by_author'), ' ', $this->extension->getAuthor(); ?></p>

	<h2><?php echo _t('gen.action.manage'); ?></h2>
	<?php
		$configure_view = $this->extension->getConfigureView();
		if ($configure_view !== false) {
			echo $configure_view;
		} else {
	?>
	<p class="alert alert-warn"><?php echo _t('admin.extensions.no_configure_view'); ?></p>
	<?php } ?>
</div>
