<?php /** @var FreshRSS_View $this */ ?>

<?php 
if ($this->ext_details->getType() === 'user' || FreshRSS_Auth::hasAccess('admin')) { 
	$name_encoded = urlencode($this->ext_details->getName()); 
	$ext_enabled = $this->ext_details->isEnabled();
	if ($ext_enabled) { ?>
	<button class="switch active" form="form-extension" formaction="<?= _url('extension', 'disable', 'e', $name_encoded) ?>" title="<?= _t('gen.action.disable') ?>"></button>
	<?php } else { ?>
	<button class="switch" form="form-extension" formaction="<?= _url('extension', 'enable', 'e', $name_encoded) ?>" title="<?= _t('gen.action.enable') ?>"></button>
	<?php } ?>
<?php } else { ?>
<?= _t('admin.extensions.system.no_rights') ?>
<?php } ?>
<a class="open-slider" title="<?= _t('gen.action.manage') ?>" href="<?= _url('extension', 'configure', 'e', $name_encoded) ?>"><?= _i('configure') ?></a>
<span<?= (!$ext_enabled? ' class="disabled"':'')?>><?= $this->ext_details->getName() ?></span>
