<?php
	declare(strict_types=1);
	/** @var View $this */

use FreshRss\Models\Context;
use FreshRss\Models\View;

?>
<nav class="nav-pagination nav-list">
	<ul class="pagination">
		<?php if (Context::$offset > 0): ?>
		<li class="item pager-first">
			<a href="<?= $this->userQuery->sharedUrlHtml() . '&nb=' . Context::$number ?>">« <?= _t('conf.logs.pagination.first') ?></a>
		</li>
		<li class="item pager-previous">
			<a href="<?= $this->userQuery->sharedUrlHtml() . '&nb=' . Context::$number .
				'&offset=' . max(0, Context::$offset - Context::$number) ?>">‹ <?= _t('conf.logs.pagination.previous') ?></a>
		</li>
		<?php endif; ?>
		<li class="item pager-next">
			<a href="<?= $this->userQuery->sharedUrlHtml() . '&nb=' . Context::$number .
				'&offset=' . (Context::$offset + Context::$number) ?>"><?= _t('conf.logs.pagination.next') ?> ›</a>
		</li>
	</ul>
</nav>
