<?php
	declare(strict_types=1);
	/** @var FreshRSS_View $this */
?>
<nav class="nav-pagination nav-list">
	<ul class="pagination">
		<li class="item pager-first">
			<a href="<?= $this->userQuery->sharedUrlHtml() ?>">« <?= _t('conf.logs.pagination.first') ?></a>
		</li>
		<li class="item pager-previous">
			<a href="<?= $this->userQuery->sharedUrlHtml() ?>">‹ <?= _t('conf.logs.pagination.previous') ?></a>
		</li>
		<li class="item pager-next">
			<a href="<?= $this->userQuery->sharedUrlHtml() ?>"><?= _t('conf.logs.pagination.next') ?> ›</a>
		</li>
	</ul>
</nav>
