<?php
declare(strict_types=1);
/** @var View $this */

use FreshRss\Minz\ExtensionManager;
use FreshRss\Minz\HookType;
use FreshRss\Minz\Request;
use FreshRss\Minz\Session;
use FreshRss\Minz\Url;
use FreshRss\Models\Auth;
use FreshRss\Models\Context;
use FreshRss\Models\View;

$mark = Context::userConf()->mark_when;
$s = Context::userConf()->shortcuts;
$extData = ExtensionManager::callHook(HookType::JsVars, []);
$canView = Auth::hasAccess() || Context::systemConf()->allow_anonymous;
echo json_encode([
	'context' => [
		'anonymous' => !Auth::hasAccess(),
		'admin' => Auth::hasAccess('admin'),
		'suppress_csp_warning' => Context::systemConf()->suppress_csp_warning,
		'auto_remove_article' => !!Context::isAutoRemoveAvailable(),
		'hide_posts' => !(Context::userConf()->display_posts || Request::actionName() === 'reader'),
		'display_order' => Request::paramString('order') ?: Context::userConf()->sort_order,
		'sort' => Context::$sort,
		'display_categories' => Context::userConf()->display_categories,
		'show_title_unread' => Context::userConf()->show_title_unread,
		'auto_mark_article' => !!$mark['article'],
		'auto_mark_site' => !!$mark['site'],
		'auto_mark_scroll' => !!$mark['scroll'],
		'auto_mark_focus' => !!$mark['focus'],
		'auto_load_more' => Context::userConf()->auto_load_more && Context::$sort !== 'rand',
		'auto_actualize_feeds' => Session::paramBoolean('actualize_feeds'),
		'nb_parallel_refresh' => max(1, Context::systemConf()->nb_parallel_refresh),
		'does_lazyload' => Context::userConf()->lazyload && !Request::is('index', 'reader'), // TODO: currently no lazy-loading is being done in reader view
		'sides_close_article' => !!Context::userConf()->sides_close_article,
		'sidebar_hidden_by_default' => !!Context::userConf()->sidebar_hidden_by_default,
		'sticky_post' => !!Context::isStickyPostEnabled(),
		'html5_enable_notif' => Context::userConf()->html5_enable_notif,
		'html5_notif_timeout' => Context::userConf()->html5_notif_timeout,
		'closeNotification' => [
			'good' => Context::userConf()->good_notification_timeout * 1000,
			'bad' => Context::userConf()->bad_notification_timeout * 1000,
			'mouseLeave' => 3000,
		],
		'auth_type' => Context::systemConf()->auth_type,
		'current_view' => Request::actionName(),
		'csrf' => Auth::csrfToken(),
		'mtime' => [
			'extra.js' => @filemtime(PUBLIC_PATH . '/scripts/extra.js'),
			'feed.js' => @filemtime(PUBLIC_PATH . '/scripts/feed.js'),
		],
		'send_referrer_allowlist' => $canView ? Context::userConf()->send_referrer_allowlist : [],
		'max_favicon_upload_size' => Context::systemConf()->limits['max_favicon_upload_size'],
		'version' => FRESHRSS_VERSION,
	],
	'shortcuts' => [
		'actualize' => $s['actualize'] ?? '',
		'mark_read' => $s['mark_read'] ?? '',
		'mark_favorite' => $s['mark_favorite'] ?? '',
		'go_website' => $s['go_website'] ?? '',
		'prev_entry' => $s['prev_entry'] ?? '',
		'next_entry' => $s['next_entry'] ?? '',
		'next_unread_entry' => $s['next_unread_entry'] ?? '',
		'skip_prev_entry' => $s['skip_prev_entry'] ?? '',
		'skip_next_entry' => $s['skip_next_entry'] ?? '',
		'first_entry' => $s['first_entry'] ?? '',
		'last_entry' => $s['last_entry'] ?? '',
		'collapse_entry' => $s['collapse_entry'] ?? '',
		'load_more' => $s['load_more'] ?? '',
		'mylabels' => $s['mylabels'] ?? '',
		'auto_share' => $s['auto_share'] ?? '',
		'focus_search' => $s['focus_search'] ?? '',
		'user_filter' => $s['user_filter'] ?? '',
		'help' => $s['help'] ?? '',
		'close_menus' => $s['close_menus'] ?? '',
		'normal_view' => $s['normal_view'] ?? '',
		'global_view' => $s['global_view'] ?? '',
		'reading_view' => $s['reading_view'] ?? '',
		'rss_view' => $s['rss_view'] ?? '',
		'toggle_media' => $s['toggle_media'] ?? '',
		'toggle_aside' => $s['toggle_aside'] ?? '',
	],
	'urls' => [
		'index' => _url('index', 'index'),
		'login' => Url::display(['c' => 'auth', 'a' => 'login'], 'php'),
		'logout' => Url::display(['c' => 'auth', 'a' => 'logout'], 'php'),
		'help' => FRESHRSS_WIKI,
		'shortcuts' => Url::display(['c' => 'configure', 'a' => 'shortcut'], 'php'),
	],
	'i18n' => [
		'confirmation_default' => _t('gen.js.confirm_action'),
		'confirm_exit_slider' => _t('gen.js.confirm_exit_slider'),
		'notif_title_articles' => _t('gen.js.feedback.title_new_articles'),
		'notif_request_failed' => _t('gen.js.feedback.request_failed'),
		'category_empty' => _t('gen.js.category_empty'),
		'labels_empty' => _t('gen.js.labels_empty'),
		'favicon_size_exceeded' => _t('feedback.sub.feed.favicon.too_large', format_bytes(Context::systemConf()->limits['max_favicon_upload_size'])),
		'language' => Context::userConf()->language,
		'unsafe_csp_header' => _t('gen.js.unsafe_csp_header'),
	],
	'icons' => [
		'read' => rawurlencode(_i('read')),
		'unread' => rawurlencode(_i('unread')),
		'spinner' => '../themes/icons/spinner.svg',
	],
	'extensions' => $extData,
], JSON_UNESCAPED_UNICODE | JSON_HEX_TAG | JSON_HEX_AMP);
