<?php
	$c = Minz_Request::controllerName();
	$a = Minz_Request::actionName();
	$params = Minz_Request::fetchGET();
?>

<?php if ($this->nbPage > 1) { ?>
<ul class="pagination">
	<?php $params[$getteur] = 1; ?>
	<li class="item pager-first">
		<?php if ($this->currentPage > 1) { ?>
		<a href="<?= Minz_Url::display(array('c' => $c, 'a' => $a, 'params' => $params)) ?>">« <?= _t('gen.pagination.first') ?></a>
		<?php } ?>
	</li>

	<?php $params[$getteur] = $this->currentPage - 1; ?>
	<li class="item pager-previous">
		<?php if ($this->currentPage > 1) { ?>
		<a href="<?= Minz_Url::display(array('c' => $c, 'a' => $a, 'params' => $params)) ?>">‹ <?= _t('gen.pagination.previous') ?></a>
		<?php } ?>
	</li>

	<?php for ($i = $this->currentPage - 2; $i <= $this->currentPage + 2; $i++) { ?>
		<?php if($i > 0 && $i <= $this->nbPage) { ?>
			<?php if ($i != $this->currentPage) { ?>
			<?php $params[$getteur] = $i; ?>
			<li class="item pager-item"><a href="<?= Minz_Url::display(array('c' => $c, 'a' => $a, 'params' => $params)) ?>"><?= $i ?></a></li>
			<?php } else { ?>
			<li class="item pager-current"><?= $i ?></li>
			<?php } ?>
		<?php } ?>
	<?php } ?>

	<?php $params[$getteur] = $this->currentPage + 1; ?>
	<li class="item pager-next">
		<?php if ($this->currentPage < $this->nbPage) { ?>
		<a href="<?= Minz_Url::display(array('c' => $c, 'a' => $a, 'params' => $params)) ?>"><?= _t('gen.pagination.next') ?> ›</a>
		<?php } ?>
	</li>
	<?php $params[$getteur] = $this->nbPage; ?>
	<li class="item pager-last">
		<?php if ($this->currentPage < $this->nbPage) { ?>
		<a href="<?= Minz_Url::display(array('c' => $c, 'a' => $a, 'params' => $params)) ?>"><?= _t('gen.pagination.last') ?> »</a>
		<?php } ?>
	</li>
</ul>
<?php } ?>
