<?php
	/** @var FreshRSS_View $this */
	$c = Minz_Request::controllerName();
	$a = Minz_Request::actionName();
	$params = $_GET;
?>

<?php if ($this->nbPage > 1) { ?>
	<nav class="nav-pagination nav-list">
	<ul class="pagination">
		<?php
			/** @var int $getteur */
			$params[$getteur] = 1;
		?>
		<li class="item pager-first">
			<a href="<?= Minz_Url::display(array('c' => $c, 'a' => $a, 'params' => $params)) ?>">« <?= _t('gen.pagination.first') ?></a>
		</li>

		<?php $params[$getteur] = $this->currentPage - 1; ?>
		<li class="item pager-previous">
			<a href="<?= Minz_Url::display(array('c' => $c, 'a' => $a, 'params' => $params)) ?>">‹ <?= _t('gen.pagination.previous') ?></a>
		</li>

		<?php if ($this->currentPage - 2 > 1) { ?>
		<li class="item">…</a></li>
		<?php } ?>

		<?php
		for ($i = $this->currentPage - 2; $i <= $this->currentPage + 2; $i++) {
			if($i > 0 && $i <= $this->nbPage) {
				if ($i != $this->currentPage) {
					$params[$getteur] = $i;
					$class = '';
					$aria = 'false';
				} else {
					$class = ' active';
					$aria = 'true';
				} ?>
				<li class="item<?= $class ?>"><a href="<?= Minz_Url::display(array('c' => $c, 'a' => $a, 'params' => $params)) ?>" aria-current="<?= $aria ?>"><?= $i ?></a></li>
			<?php
			}
		} ?>

		<?php if ($this->nbPage > $i - 1) { ?>
		<li class="item">…</a></li>
		<?php } ?>

		<?php $params[$getteur] = $this->currentPage + 1; ?>
		<li class="item pager-next">
			<a href="<?= Minz_Url::display(array('c' => $c, 'a' => $a, 'params' => $params)) ?>"><?= _t('gen.pagination.next') ?> ›</a>
		</li>
		<?php $params[$getteur] = $this->nbPage; ?>
		<li class="item pager-last">
			<a href="<?= Minz_Url::display(array('c' => $c, 'a' => $a, 'params' => $params)) ?>"><?= _t('gen.pagination.last') ?> »</a>
		</li>
	</ul>
</nav>
<?php } ?>
