<?php
	$c = Request::controllerName ();
	$a = Request::actionName ();
	$params = Request::params ();
?>

<ul class="pagination">
	<li class="item pager-previous">
	<?php if ($this->currentPage > 1) { ?>
	<?php $params[$getteur] = $this->currentPage - 1; ?>
	<a href="<?php echo Url::display (array ('c' => $c, 'a' => $a, 'params' => $params)); ?>">‹ plus récents</a>
	<?php } else { ?>
	&nbsp;
	<?php } ?>
	</li>

	<li class="item pager-current">page <?php echo $this->currentPage; ?> / <?php echo $this->nbPage; ?></li>

	<li class="item pager-next">
	<?php if ($this->currentPage < $this->nbPage) { ?>
	<?php $params[$getteur] = $this->currentPage + 1; ?>
	<a href="<?php echo Url::display (array ('c' => $c, 'a' => $a, 'params' => $params)); ?>">plus anciens ›</a>
	<?php } else { ?>
	&nbsp;
	<?php } ?>
	</li>
</ul>
