<?php echo '<?xml version="1.0" encoding="UTF-8" ?>'; ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
	<channel>
		<title><?php echo View::title(); ?></title>
		<link><?php echo Url::display(); ?></link>
		<description><?php echo Translate::t ('rss_feeds_of', View::title()); ?></description>
		<pubDate><?php echo date('D, d M Y H:i:s O'); ?></pubDate>
		<lastBuildDate><?php echo gmdate('D, d M Y H:i:s'); ?> GMT</lastBuildDate>
		<atom:link href="<?php echo _url ('index', 'index', 'output', 'rss'); ?>" rel="self" type="application/rss+xml" />
<?php
$items = $this->entryPaginator->items ();
foreach ($items as $item) {
?>
		<item>
			<title><?php echo htmlspecialchars(html_entity_decode($item->title (), ENT_NOQUOTES, 'UTF-8'), ENT_NOQUOTES, 'UTF-8'); ?></title>
			<link><?php echo $item->link (); ?></link>
			<?php $author = $item->author (); ?>
			<?php if ($author != '') { ?>
			<dc:creator><?php echo $author; ?></dc:creator>
			<?php } ?>
			<description><![CDATA[<?php
	echo $item->content ();
?>]]></description>
			<pubDate><?php echo date('D, d M Y H:i:s O', $item->date (true)); ?></pubDate>
			<guid isPermaLink="false"><?php echo $item->id (); ?></guid>
		</item>
<?php } ?>		

	</channel>
</rss>
