<?php $this->partial('aside_subscription'); ?>

<div class="post">
	<a href="<?= _url('index', 'index') ?>"><?= _t('gen.action.back_to_rss_feeds') ?></a>

	<legend><?= _t('sub.bookmarklet.title') ?></legend>
	<p><a class="btn btn-important" href="javascript:(function(){var%20url%20=%20location.href;var%20otherWindow=window.open('about:blank','_blank');otherWindow.opener=null;otherWindow.location='<?= Minz\Url::display(array('c' => 'feed', 'a' => 'add'), 'html', true) ?>&amp;url_rss='+encodeURIComponent(url);})();"><?= _t('sub.bookmarklet.label') ?></a></p>
	<?= _t('sub.bookmarklet.documentation') ?>

	<legend><?= _t('sub.firefox.title') ?></legend>
	<p class="alert alert-warn">
		<?= _t('sub.firefox.obsolete_63', $this->default_category->name()) ?>
	</p>
	<p><?= _t('sub.firefox.documentation') ?></p>
	<pre>browser.contentHandlers.types.number.uri → <?= Minz\Url::display(array('c' => 'feed', 'a' => 'add'), 'html', true) ?>&amp;url_rss=%s</pre>

	<legend><?= _t('sub.api.title') ?></legend>
	<p><?= _t('sub.api.documentation') ?></p>
	<pre><?= Minz\Url::display(array('c' => 'feed', 'a' => 'add'), 'html', true) ?>&amp;url_rss=%s</pre>
</div>