<?php $this->partial('aside_subscription'); ?>

<div class="post">
	<a href="<?php echo _url('index', 'index'); ?>"><?php echo _t('gen.action.back_to_rss_feeds'); ?></a>

	<legend><?php echo _t('sub.bookmarklet.title'); ?></legend>
	<p><a class="btn btn-important" href="javascript:(function(){var%20url%20=%20location.href;var%20otherWindow=window.open('about:blank','_blank');otherWindow.opener=null;otherWindow.location='<?php echo Minz_Url::display(array('c' => 'feed', 'a' => 'add'), 'html', true); ?>&amp;url_rss='+encodeURIComponent(url);})();"><?php echo _t('sub.bookmarklet.label'); ?></a></p>
	<?php echo _t('sub.bookmarklet.documentation'); ?>

	<legend><?php echo _t('sub.firefox.title'); ?></legend>
	<p><?php echo _t('sub.firefox.documentation'); ?></p>
	<pre>browser.contentHandlers.types.number.uri → <?php echo Minz_Url::display(array('c' => 'feed', 'a' => 'add'), 'html', true); ?>&amp;url_rss=%s</pre>

	<legend><?php echo _t('sub.api.title'); ?></legend>
	<p><?php echo _t('sub.api.documentation'); ?></p>
	<pre><?php echo Minz_Url::display(array('c' => 'feed', 'a' => 'add'), 'html', true); ?>&amp;url_rss=%s</pre>
</div>