<?php
declare(strict_types=1);
/** @var View $this */

use FreshRss\Minz\Request;
use FreshRss\Models\View;

if (!Request::paramBoolean('ajax')) {
	$this->partial('aside_subscription');
}

if ($this->feed !== null) {
	$this->renderHelper('feed/update');
} else {
?>
<div class="alert alert-warn">
	<span class="alert-head"><?= _t('sub.feed.no_selected') ?></span>
	<?= _t('sub.feed.think_to_add') ?>
</div>
<?php } ?>
