<?php $this->partial('aside_subscription'); ?>

<div class="post">
	<a href="<?php echo _url('index', 'index'); ?>"><?php echo _t('back_to_rss_feeds'); ?></a>

	<h2><?php echo _t('subscription_management'); ?></h2>

	<form id="add_rss" method="post" action="<?php echo _url('feed', 'add'); ?>" autocomplete="off">
		<div class="stick">
			<input type="url" name="url_rss" class="extend" placeholder="<?php echo _t('add_rss_feed'); ?>" />
			<div class="dropdown">
				<div id="dropdown-cat" class="dropdown-target"></div>

				<a class="dropdown-toggle btn" href="#dropdown-cat"><?php echo _i('down'); ?></a>
				<ul class="dropdown-menu">
					<li class="dropdown-close"><a href="#close">❌</a></li>

					<li class="dropdown-header"><?php echo _t('category'); ?></li>

					<li class="input">
						<select name="category" id="category">
						<?php foreach ($this->categories as $cat) { ?>
						<option value="<?php echo $cat->id(); ?>"<?php echo $cat->id() == 1 ? ' selected="selected"' : ''; ?>>
							<?php echo $cat->name(); ?>
						</option>
						<?php } ?>
						<option value="nc"><?php echo _t('new_category'); ?></option>
						</select>
					</li>

					<li class="input" style="display:none">
						<input type="text" name="new_category[name]" id="new_category_name" autocomplete="off" placeholder="<?php echo _t('new_category'); ?>" />
					</li>

					<li class="separator"></li>

					<li class="dropdown-header"><?php echo _t('http_authentication'); ?></li>
					<li class="input">
						<input type="text" name="http_user" id="http_user_add" autocomplete="off" placeholder="<?php echo _t('username'); ?>" />
					</li>
					<li class="input">
						<input type="password" name="http_pass" id="http_pass_add" autocomplete="off" placeholder="<?php echo _t('password'); ?>" />
					</li>
				</ul>
			</div>
			<button class="btn" type="submit"><?php echo _i('add'); ?></button>
		</div>
	</form>

	<p class="alert alert-warn">
		<?php echo _t('feeds_moved_category_deleted', $this->default_category->name()); ?>
	</p>

	<div class="box">
		<div class="box-title"><label for="new-category"><?php echo _t('add_category'); ?></label></div>

		<ul class="box-content box-content-centered">
			<form action="<?php echo _url('category', 'create'); ?>" method="post">
				<li class="item"><input type="text" id="new-category" name="new-category" placeholder="<?php echo _t('new_category'); ?>" /></li>
				<li class="item"><button class="btn btn-important" type="submit"><?php echo _t('submit'); ?></button></li>
			</form>
		</ul>
	</div>

	<form id="controller-category" method="post" style="display: none;"></form>

	<?php
		foreach ($this->categories as $cat) {
			$feeds = $cat->feeds();
	?>
	<div class="box">
		<div class="box-title">
			<form action="<?php echo _url('category', 'update', 'id', $cat->id()); ?>" method="post">
				<input type="text" name="name" value="<?php echo $cat->name(); ?>" />

				<div class="dropdown">
					<div id="dropdown-cat-<?php echo $cat->id(); ?>" class="dropdown-target"></div>

					<a class="dropdown-toggle btn" href="#dropdown-cat-<?php echo $cat->id(); ?>"><?php echo _i('down'); ?></a>
					<ul class="dropdown-menu">
						<li class="dropdown-close"><a href="#close">❌</a></li>

						<li class="item"><a href="<?php echo _url('index', 'index', 'get', 'c_' . $cat->id()); ?>"><?php echo _t('filter'); ?></a></li>

						<li class="separator"></li>

						<?php if (!empty($feeds)) { ?>
						<li class="item">
							<button class="as-link confirm"
							        data-str-confirm="<?php echo _t('confirm_action_feed_cat'); ?>"
							        type="submit"
							        form="controller-category"
							        formaction="<?php echo _url('category', 'empty', 'id', $cat->id()); ?>">
							        <?php echo _t('ask_empty'); ?></button>
						</li>
						<?php } ?>
						<li class="item">
							<button class="as-link confirm"
							        data-str-confirm="<?php echo _t('confirm_action_feed_cat'); ?>"
							        type="submit"
							        form="controller-category"
							        formaction="<?php echo _url('category', 'delete', 'id', $cat->id()); ?>">
							        <?php echo _t('delete'); ?></button>
						</li>
					</ul>
				</div>
			</form>
		</div>

		<ul class="box-content">
			<?php if (!empty($feeds)) { ?>
			<?php
					foreach ($feeds as $feed) {
						$error = $feed->inError() ? ' error' : '';
						$empty = $feed->nbEntries() == 0 ? ' empty' : '';
			?>
			<li class="item<?php echo $error, $empty; ?>">
				<a class="configure open-slider" href="<?php echo _url('subscription', 'feed', 'id', $feed->id()); ?>"><?php echo _i('configure'); ?></a>
				<img class="favicon" src="<?php echo $feed->favicon(); ?>" alt="✇" /> <?php echo $feed->name(); ?>
			</li>
			<?php 	}
				} else {
			?>
			<li class="item"><?php echo _t('category_empty'); ?></li>
			<?php } ?>
		</ul>
	</div>
	<?php } ?>
</div>

<div id="slider">
<?php
	if (isset($this->feed) && $this->feed) {
		$this->renderHelper('feed/update');
	}
?>
</div>
