<?php
	$sharing = array();
	if (FreshRSS_Auth::hasAccess()) {
		$sharing = FreshRSS_Context::$user_conf->sharing;
	}

	$bottomline_read = FreshRSS_Context::$user_conf->bottomline_read;
	$bottomline_favorite = FreshRSS_Context::$user_conf->bottomline_favorite;
	$bottomline_sharing = FreshRSS_Context::$user_conf->bottomline_sharing && (count($sharing) > 0);
	$bottomline_labels = true;	//TODO
	$bottomline_tags = FreshRSS_Context::$user_conf->bottomline_tags;
	$bottomline_date = FreshRSS_Context::$user_conf->bottomline_date;
	$bottomline_link = FreshRSS_Context::$user_conf->bottomline_link;
?><ul class="horizontal-list bottom"><?php
	if (FreshRSS_Auth::hasAccess()) {
		if ($bottomline_read) {
			?><li class="item manage"><?php
				$arUrl = array('c' => 'entry', 'a' => 'read', 'params' => array('id' => $this->entry->id()));
				if ($this->entry->isRead()) {
					$arUrl['params']['is_read'] = 0;
				}
				?><a class="read" href="<?= Minz_Url::display($arUrl) ?>"><?php
					echo _i($this->entry->isRead() ? 'read' : 'unread'); ?></a><?php
			?></li><?php
		}
		if ($bottomline_favorite) {
			?><li class="item manage"><?php
				$arUrl = array('c' => 'entry', 'a' => 'bookmark', 'params' => array('id' => $this->entry->id()));
				if ($this->entry->isFavorite()) {
					$arUrl['params']['is_favorite'] = 0;
				}
				?><a class="bookmark" href="<?= Minz_Url::display($arUrl) ?>"><?php
					echo _i($this->entry->isFavorite() ? 'starred' : 'non-starred'); ?></a><?php
			?></li><?php
		}
	}
	if ($bottomline_labels) {
	?><li class="item">
		<div class="dropdown dynamictags">
			<div id="dropdown-labels-<?= $this->entry->id() ?>" class="dropdown-target"></div>
			<?= FreshRSS_Themes::alt('label') ?>
			<a class="dropdown-toggle" href="#dropdown-labels-<?= $this->entry->id() ?>"><?php
				echo _t('index.menu.tags');
			?></a>
			<ul class="dropdown-menu dropdown-menu-scrollable">
				<li class="dropdown-close"><a href="#close">❌</a></li>
				<!-- Ajax -->
			</ul>
			<div class="dropdown-close"><a href="#close">❌</a></div>
		</div>
	</li><?php
	}
	$tags = $bottomline_tags ? $this->entry->tags() : null;
	if (!empty($tags)) {
	?><li class="item">
		<div class="dropdown">
			<div id="dropdown-tags-<?= $this->entry->id() ?>" class="dropdown-target"></div>
			<?= _i('tag') ?>
			<a class="dropdown-toggle" href="#dropdown-tags-<?= $this->entry->id() ?>"><?php
				echo _t('index.tag.related');
			?></a>
			<ul class="dropdown-menu">
				<li class="dropdown-close"><a href="#close">❌</a></li><?php
				foreach ($tags as $tag) {
					?><li class="item"><a href="<?= _url('index', 'index', 'search', '#' . str_replace(' ', '+', htmlspecialchars_decode($tag, ENT_QUOTES))) ?>"><?= $tag ?></a></li><?php
				} ?>
			</ul>
		</div>
	</li><?php
	}
	?><li class="item"><?php
			if ($bottomline_sharing) {
		?><div class="dropdown">
			<div id="dropdown-share-<?= $this->entry->id() ?>" class="dropdown-target"></div>
			<a class="dropdown-toggle" href="#dropdown-share-<?= $this->entry->id() ?>">
				<?= _i('share') ?>
				<?= _t('index.share') ?>
			</a>

			<ul class="dropdown-menu">
				<li class="dropdown-close"><a href="#close">❌</a></li><?php
					$id = $this->entry->id();
					$link = $this->entry->link();
					$title = $this->entry->title() . ' · ' . $this->feed->name();
					foreach (FreshRSS_Context::$user_conf->sharing as $share_options) {
						$share = FreshRSS_Share::get($share_options['type']);
						if ($share === null) {
							continue;
						}
						$share_options['id'] = $id;
						$share_options['link'] = $link;
						$share_options['title'] = $title;
						$share->update($share_options);
				?><li class="item share">
					<?php if ('GET' === $share->method()) {?>
						<a target="_blank" rel="noreferrer" href="<?= $share->url() ?>"><?= $share->name() ?></a>
					<?php } else {?>
						<a href="POST"><?= $share->name() ?></a>
						<form method="POST" action="<?= $share->url() ?>" disabled="disabled">
							<input type="hidden" value="<?= $link ?>" name="<?= $share->field() ?>"/>
						</form>
					<?php } ?>
				</li><?php
					}
			?></ul>
		</div>
		<?php } ?>
	</li><?php
	if ($bottomline_date) {
		?><li class="item date"><?= $this->entry->date() ?></li><?php
	}
	if ($bottomline_link) {
		?><li class="item link"><a target="_blank" rel="noreferrer" href="<?= $this->entry->link() ?>"><?= _i('link') ?></a></li><?php
	} ?>
</ul>
