<?php $this->partial ('aside_feed'); ?>

<div class="post ">
	<a href="<?php echo _url ('index', 'index'); ?>"><?php echo Minz_Translate::t ('back_to_rss_feeds'); ?></a>

	<form method="post" action="<?php echo _url('importExport', 'import'); ?>" enctype="multipart/form-data">
		<legend><?php echo Minz_Translate::t ('import'); ?></legend>
		<div class="form-group">
			<label class="group-name" for="file"><?php echo Minz_Translate::t ('file_to_import'); ?></label>
			<div class="group-controls">
				<input type="file" name="file" id="file" />
			</div>
		</div>

		<div class="form-group form-actions">
			<div class="group-controls">
				<button type="submit" class="btn btn-important"><?php echo Minz_Translate::t ('import'); ?></button>
			</div>
		</div>
	</form>

	<form method="post" action="<?php echo _url('importExport', 'export'); ?>">
		<legend><?php echo Minz_Translate::t ('export'); ?></legend>
		<div class="form-group">
			<div class="group-controls">
				<label class="checkbox" for="export_opml">
					<input type="checkbox" name="export_opml" id="export_opml" value="1" checked="checked" />
					<?php echo Minz_Translate::t ('export_opml'); ?>
				</label>

				<label class="checkbox" for="export_starred">
					<input type="checkbox" name="export_starred" id="export_starred" value="1" checked="checked" />
					<?php echo Minz_Translate::t ('export_starred'); ?>
				</label>

				<label class="checkbox" for="export_all">
					<input type="checkbox" name="export_all" id="export_all" value="1" />
					<?php echo Minz_Translate::t ('export_all'); ?>
					<?php echo FreshRSS_Themes::icon('help'); ?> <?php echo Minz_Translate::t('export_all_is_long'); ?>
				</label>
			</div>
		</div>

		<div class="form-group form-actions">
			<div class="group-controls">
				<button type="submit" class="btn btn-important"><?php echo Minz_Translate::t ('export'); ?></button>
			</div>
		</div>
	</form>
</div>
