<?php $this->partial ('aside_feed'); ?>

<div class="post ">
	<a href="<?php echo _url ('index', 'index'); ?>"><?php echo Minz_Translate::t ('back_to_rss_feeds'); ?></a>

	<form method="post" action="<?php echo _url('importExport', 'import'); ?>" enctype="multipart/form-data">
		<legend><?php echo Minz_Translate::t ('import_export'); ?></legend>
		<div class="form-group">
			<label class="group-name" for="file"><?php echo Minz_Translate::t ('file_to_import'); ?></label>
			<div class="group-controls">
				<input type="file" name="file" id="file" />
			</div>
		</div>

		<div class="form-group form-actions">
			<div class="group-controls">
				<button type="submit" class="btn btn-important"><?php echo Minz_Translate::t ('import'); ?></button>
				<?php echo Minz_Translate::t ('or'); ?>
				<a target="_blank" class="btn btn-important" href="<?php echo _url ('importExport', 'export'); ?>"><?php echo Minz_Translate::t ('export'); ?></a>
			</div>
		</div>
	</form>
</div>
