<form action="<?php echo _url('extension', 'configure', 'e', urlencode($this->getName())); ?>" method="post">
	<input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />
	<div class="form-group">
		<label class="group-name" for="js-rules"><?php echo _t('ext.custom_js.write_js'); ?></label>
		<div class="group-controls">
			<textarea name="js-rules" id="js-rules"><?php echo $this->js_rules; ?></textarea>
		</div>
	</div>

	<div class="form-group form-actions">
		<?php if (isset($this->permission_problem)) { ?>
			<p class="alert alert-error"><?php echo _t('ext.custom_js.permission_problem', $this->permission_problem); ?></p>
		<?php } else { ?>
			<div class="group-controls">
				<button type="submit" class="btn btn-important"><?php echo _t('gen.action.submit'); ?></button>
				<button type="reset" class="btn"><?php echo _t('gen.action.cancel'); ?></button>
			</div>
		<?php } ?>
	</div>
</form>
