<?php $this->partial('aside_configure'); ?>

<div class="post">
	<a href="<?php echo _url('index', 'index'); ?>"><?php echo Minz_Translate::t('back_to_rss_feeds'); ?></a>

	<form method="post" action="<?php echo _url('configure', 'archiving'); ?>">
		<legend><?php echo Minz_Translate::t('archiving_configuration'); ?></legend>
		<p><?php echo FreshRSS_Themes::icon('help'); ?> <?php echo Minz_Translate::t('archiving_configuration_help'); ?></p>

		<div class="form-group">
			<label class="group-name" for="old_entries"><?php echo Minz_Translate::t('delete_articles_every'); ?></label>
			<div class="group-controls">
				<input type="number" id="old_entries" name="old_entries" min="1" max="1200" value="<?php echo $this->conf->old_entries; ?>" /> <?php echo Minz_Translate::t('month'); ?>
				  <a class="btn confirm" href="<?php echo _url('entry', 'purge'); ?>"><?php echo Minz_Translate::t('purge_now'); ?></a>
			</div>
		</div>
		<div class="form-group">
			<label class="group-name" for="keep_history_default"><?php echo Minz_Translate::t('keep_history'), ' ', Minz_Translate::t('by_feed'); ?></label>
			<div class="group-controls">
				<select class="number" name="keep_history_default" id="keep_history_default" required="required"><?php
					foreach (array('' => '', 0 => '0', 10 => '10', 50 => '50', 100 => '100', 500 => '500', 1000 => '1 000', 5000 => '5 000', 10000 => '10 000', -1 => '∞') as $v => $t) {
						echo '<option value="' . $v . ($this->conf->keep_history_default == $v ? '" selected="selected' : '') . '">' . $t . ' </option>';
					}
				?></select> (<?php echo Minz_Translate::t('by_default'); ?>)
			</div>
		</div>

		<div class="form-group form-actions">
			<div class="group-controls">
				<button type="submit" class="btn btn-important"><?php echo Minz_Translate::t('save'); ?></button>
				<button type="reset" class="btn"><?php echo Minz_Translate::t('cancel'); ?></button>
			</div>
		</div>
	</form>

	<form method="post" action="<?php echo _url('entry', 'optimize'); ?>">
		<legend><?php echo Minz_Translate::t ('advanced'); ?></legend>

		<div class="form-group">
		<p class="group-name"><?php echo Minz_Translate::t('current_user'); ?></p>
			<div class="group-controls">
				<p><?php echo formatNumber($this->nb_total), ' ', Minz_Translate::t('articles'), ', ', formatBytes($this->size_user); ?></p>
				<input type="hidden" name="optimiseDatabase" value="1" />
				<button type="submit" class="btn btn-important"><?php echo Minz_Translate::t('optimize_bdd'); ?></button>
				<?php echo FreshRSS_Themes::icon('help'); ?> <?php echo Minz_Translate::t('optimize_todo_sometimes'); ?>
			</div>
		</div>

		<?php if (Minz_Configuration::isAdmin(Minz_Session::param('currentUser', '_'))) { ?>
		<div class="form-group">
			<p class="group-name"><?php echo Minz_Translate::t('users'); ?></p>
			<div class="group-controls">
				<p><?php echo formatBytes($this->size_total); ?></p>
			</div>
		</div>
		<?php } ?>
	</form>
</div>
