<?php $this->partial('aside_configure'); ?>

<div class="post">
	<a href="<?php echo _url('index', 'index'); ?>"><?php echo _t('gen.action.back_to_rss_feeds'); ?></a>

	<form method="post" action="<?php echo _url('configure', 'archiving'); ?>">
		<input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />
		<legend><?php echo _t('conf.archiving'); ?></legend>
		<p><?php echo _i('help'); ?> <?php echo _t('conf.archiving.help'); ?></p>

		<div class="form-group">
			<label class="group-name" for="old_entries"><?php echo _t('conf.archiving.delete_after'); ?></label>
			<div class="group-controls">
				<input type="number" id="old_entries" name="old_entries" min="1" max="1200" value="<?php echo FreshRSS_Context::$user_conf->old_entries; ?>" data-leave-validation="<?php echo FreshRSS_Context::$user_conf->old_entries; ?>"/> <?php echo _t('gen.date.month'); ?>
			</div>
		</div>
		<div class="form-group">
			<label class="group-name" for="keep_history_default"><?php echo _t('conf.archiving.keep_history_by_feed'); ?></label>
			<div class="group-controls">
				<select class="number" name="keep_history_default" id="keep_history_default" required="required" data-leave-validation="<?php echo FreshRSS_Context::$user_conf->keep_history_default; ?>"><?php
					foreach (array('' => '', 0 => '0', 10 => '10', 50 => '50', 100 => '100', 500 => '500', 1000 => '1 000', 5000 => '5 000', 10000 => '10 000', FreshRSS_Feed::KEEP_HISTORY_INFINITE => '∞') as $v => $t) {
						echo '<option value="' . $v . (FreshRSS_Context::$user_conf->keep_history_default == $v ? '" selected="selected' : '') . '">' . $t . ' </option>';
					}
				?></select> (<?php echo _t('gen.short.by_default'); ?>)
			</div>
		</div>
		<div class="form-group">
			<label class="group-name" for="ttl_default"><?php echo _t('conf.archiving.ttl'); ?></label>
			<div class="group-controls">
				<select class="number" name="ttl_default" id="ttl_default" required="required" data-leave-validation="<?php echo FreshRSS_Context::$user_conf->ttl_default; ?>"><?php
					$found = false;
					foreach (array(1200 => '20min', 1500 => '25min', 1800 => '30min', 2700 => '45min',
					                3600 => '1h', 5400 => '1.5h', 7200 => '2h', 10800 => '3h', 14400 => '4h', 18800 => '5h', 21600 => '6h', 25200 => '7h', 28800 => '8h',
					                36000 => '10h', 43200 => '12h', 64800 => '18h',
					                86400 => '1d', 129600 => '1.5d', 172800 => '2d', 259200 => '3d', 345600 => '4d', 432000 => '5d', 518400 => '6d',
					                604800 => '1wk') as $v => $t) {
						echo '<option value="' . $v . (FreshRSS_Context::$user_conf->ttl_default == $v ? '" selected="selected' : '') . '">' . $t . '</option>';
						if (FreshRSS_Context::$user_conf->ttl_default == $v) {
							$found = true;
						}
					}
					if (!$found) {
						echo '<option value="' . intval(FreshRSS_Context::$user_conf->ttl_default) . '" selected="selected">' . intval(FreshRSS_Context::$user_conf->ttl_default) . 's</option>';
					}
				?></select> (<?php echo _t('gen.short.by_default'); ?>)
			</div>
		</div>

		<div class="form-group form-actions">
			<div class="group-controls">
				<button type="submit" class="btn btn-important"><?php echo _t('gen.action.submit'); ?></button>
				<button type="reset" class="btn"><?php echo _t('gen.action.cancel'); ?></button>
			</div>
		</div>
	</form>

	<legend><?php echo _t('conf.archiving.maintenance'); ?></legend>
	<form method="post" action="<?php echo _url('entry', 'purge'); ?>">
		<input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />

		<div class="form-group">
			<div class="group-controls">
				<button type="submit" class="btn btn-important confirm"><?php echo _t('conf.archiving.purge_now'); ?></button>
			</div>
		</div>
	</form>
	<?php if (FreshRSS_Auth::hasAccess('admin')) { ?>
	<form method="post" action="<?php echo _url('entry', 'optimize'); ?>">
		<input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />

		<div class="form-group">
			<div class="group-controls">
				<input type="hidden" name="optimiseDatabase" value="1" />
				<button type="submit" class="btn btn-important"><?php echo _t('conf.archiving.optimize'); ?></button>
				<?php echo _i('help'); ?> <?php echo _t('conf.archiving.optimize_help'); ?>
			</div>
		</div>
	</form>
	<?php } ?>
</div>
