<?php $this->partial('aside_configure'); ?>

<div class="post">
	<a href="<?php echo _url('index', 'index'); ?>"><?php echo _t('back_to_rss_feeds'); ?></a>

	<form method="post" action="<?php echo _url('configure', 'archiving'); ?>">
		<legend><?php echo _t('archiving_configuration'); ?></legend>
		<p><?php echo _i('help'); ?> <?php echo _t('archiving_configuration_help'); ?></p>

		<div class="form-group">
			<label class="group-name" for="old_entries"><?php echo _t('delete_articles_every'); ?></label>
			<div class="group-controls">
				<input type="number" id="old_entries" name="old_entries" min="1" max="1200" value="<?php echo FreshRSS_Context::$conf->old_entries; ?>" /> <?php echo _t('month'); ?>
				  <a class="btn confirm" href="<?php echo _url('entry', 'purge'); ?>"><?php echo _t('purge_now'); ?></a>
			</div>
		</div>
		<div class="form-group">
			<label class="group-name" for="keep_history_default"><?php echo _t('keep_history'), ' ', _t('by_feed'); ?></label>
			<div class="group-controls">
				<select class="number" name="keep_history_default" id="keep_history_default" required="required"><?php
					foreach (array('' => '', 0 => '0', 10 => '10', 50 => '50', 100 => '100', 500 => '500', 1000 => '1 000', 5000 => '5 000', 10000 => '10 000', -1 => '∞') as $v => $t) {
						echo '<option value="' . $v . (FreshRSS_Context::$conf->keep_history_default == $v ? '" selected="selected' : '') . '">' . $t . ' </option>';
					}
				?></select> (<?php echo _t('by_default'); ?>)
			</div>
		</div>
		<div class="form-group">
			<label class="group-name" for="ttl_default"><?php echo _t('ttl'); ?></label>
			<div class="group-controls">
				<select class="number" name="ttl_default" id="ttl_default" required="required"><?php
					$found = false;
					foreach (array(1200 => '20min', 1500 => '25min', 1800 => '30min', 2700 => '45min',
					                3600 => '1h', 5400 => '1.5h', 7200 => '2h', 10800 => '3h', 14400 => '4h', 18800 => '5h', 21600 => '6h', 25200 => '7h', 28800 => '8h',
					                36000 => '10h', 43200 => '12h', 64800 => '18h',
					                86400 => '1d', 129600 => '1.5d', 172800 => '2d', 259200 => '3d', 345600 => '4d', 432000 => '5d', 518400 => '6d',
					                604800 => '1wk', -1 => '∞') as $v => $t) {
						echo '<option value="' . $v . (FreshRSS_Context::$conf->ttl_default == $v ? '" selected="selected' : '') . '">' . $t . '</option>';
						if (FreshRSS_Context::$conf->ttl_default == $v) {
							$found = true;
						}
					}
					if (!$found) {
						echo '<option value="' . intval(FreshRSS_Context::$conf->ttl_default) . '" selected="selected">' . intval(FreshRSS_Context::$conf->ttl_default) . 's</option>';
					}
				?></select> (<?php echo _t('by_default'); ?>)
			</div>
		</div>

		<div class="form-group form-actions">
			<div class="group-controls">
				<button type="submit" class="btn btn-important"><?php echo _t('save'); ?></button>
				<button type="reset" class="btn"><?php echo _t('cancel'); ?></button>
			</div>
		</div>
	</form>

	<form method="post" action="<?php echo _url('entry', 'optimize'); ?>">
		<legend><?php echo _t('advanced'); ?></legend>

		<div class="form-group">
			<label class="group-name"><?php echo _t('current_user'); ?></label>
			<div class="group-controls">
				<?php echo _t('conf.users.articles_and_size', formatNumber($this->nb_total), formatBytes($this->size_user)); ?>
			</div>
		</div>

		<?php if (FreshRSS_Auth::hasAccess('admin')) { ?>
		<div class="form-group">
			<label class="group-name"><?php echo _t('users'); ?></label>
			<div class="group-controls">
				<?php echo formatBytes($this->size_total); ?>
			</div>
		</div>

		<div class="form-group form-actions">
			<div class="group-controls">
				<input type="hidden" name="optimiseDatabase" value="1" />
				<button type="submit" class="btn btn-important"><?php echo _t('optimize_bdd'); ?></button>
				<?php echo _i('help'); ?> <?php echo _t('optimize_todo_sometimes'); ?>
			</div>
		</div>
		<?php } ?>
	</form>
</div>
