<?php $this->partial ('aside_configure'); ?>

<div class="post">
	<form method="post" action="<?php echo _url ('configure', 'categorize'); ?>">
		<legend>Gestion des catégories - <a href="<?php echo _url ('configure', 'feed'); ?>">gestion des flux</a></legend>

		<?php $i = 0; foreach ($this->categories as $cat) { $i++; ?>
		<div class="form-group">
			<label class="group-name" for="cat_<?php echo $cat->id (); ?>">Catégorie n°<?php echo $i; ?></label>
			<div class="group-controls">
				<input type="text" id="cat_<?php echo $cat->id (); ?>" name="categories[]" value="<?php echo $cat->name (); ?>" />
				<?php if ($cat->id () == '000000') { ?>
				<i class="icon i_help"></i> ne peut pas être supprimé
				<?php } ?>
				<input type="hidden" name="ids[]" value="<?php echo $cat->id (); ?>" />
			</div>
		</div>
		<?php } ?>

		<div class="form-group">
			<label class="group-name" for="new_category">Ajouter une catégorie</label>
			<div class="group-controls">
				<input type="text" id="new_category" name="new_category" placeholder="Nouvelle catégorie" />
			</div>
		</div>

		<div class="form-group form-actions">
			<div class="group-controls">
				<button type="submit" class="btn btn-important">Sauvegarder</button>
				<button type="reset" class="btn">Annuler</button>
			</div>
		</div>
	</form>
</div>
