<?php $this->partial ('aside_configure'); ?>

<div class="post">
	<form method="post" action="<?php echo _url ('configure', 'display'); ?>">
		<legend>Configuration générale</legend>

		<div class="form-group">
			<label class="group-name" for="old_entries">Supprimer les articles tous les</label>
			<div class="group-controls">
				<input type="number" id="old_entries" name="old_entries" value="<?php echo $this->conf->oldEntries (); ?>" /> mois
			</div>
		</div>

		<div class="form-group">
			<label class="group-name" for="mail_login">Adresse mail de connexion (utilise <a href="https://persona.org/">Persona</a>)</label>
		<?php $mail = $this->conf->mailLogin (); ?>
			<div class="group-controls">
				<input type="email" id="mail_login" name="mail_login" value="<?php echo $mail ? $mail : ''; ?>" placeholder="Laissez vide pour désactiver" />
				<noscript><b>nécessite que javascript soit activé</b></noscript>
			</div>
		</div>
	
		<legend>Configuration de lecture</legend>

		<div class="form-group">
			<label class="group-name" for="posts_per_page">Nombre d'articles par page</label>
			<div class="group-controls">
				<input type="number" id="posts_per_page" name="posts_per_page" value="<?php echo $this->conf->postsPerPage (); ?>" />
			</div>
		</div>

		<div class="form-group">
			<label class="group-name">Vue par défaut</label>
			<div class="group-controls">
				<label class="radio" for="radio_all">
					<input type="radio" name="default_view" id="radio_all" value="all"<?php echo $this->conf->defaultView () == 'all' ? ' checked="checked"' : ''; ?> />
					Tout afficher
				</label>
				<label class="radio" for="radio_not_read">
					<input type="radio" name="default_view" id="radio_not_read" value="not_read"<?php echo $this->conf->defaultView () == 'not_read' ? ' checked="checked"' : ''; ?> />
					Afficher les non lus
				</label>
			</div>
		</div>

		<div class="form-group">
			<label class="group-name" for="sort_order">Ordre de tri</label>
			<div class="group-controls">
				<select name="sort_order" id="sort_order">
					<option value="low_to_high"<?php echo $this->conf->sortOrder () == 'low_to_high' ? ' selected="selected"' : ''; ?>>Du plus récent au plus ancien</option>
					<option value="high_to_low"<?php echo $this->conf->sortOrder () == 'high_to_low' ? ' selected="selected"' : ''; ?>>Du plus ancien au plus récent</option>
				</select>
			</div>
		</div>

		<div class="form-group">
			<label class="group-name">Afficher les articles dépliés par défaut</label>
			<div class="group-controls">
				<label class="radio" for="radio_yes">
					<input type="radio" name="display_posts" id="radio_yes" value="yes"<?php echo $this->conf->displayPosts () == 'yes' ? ' checked="checked"' : ''; ?> />
					Oui
				</label>
				<label class="radio" for="radio_no">
					<input type="radio" name="display_posts" id="radio_no" value="no"<?php echo $this->conf->displayPosts () == 'no' ? ' checked="checked"' : ''; ?> />
					Non<noscript> - <b>nécessite que javascript soit activé</b></noscript>
				</label>
			</div>
		</div>

		<div class="form-group">
			<label class="group-name">Article automatiquement marqué comme lu lorsque</label>
			<div class="group-controls">
				<label class="checkbox" for="check_open_article">
					<input type="checkbox" name="mark_open_article" id="check_open_article" value="yes"<?php echo $this->conf->markWhenArticle () == 'yes' ? ' checked="checked"' : ''; ?> />
					l'article est sélectionné
				</label>
				<label class="checkbox" for="check_open_site">
					<input type="checkbox" name="mark_open_site" id="check_open_site" value="yes"<?php echo $this->conf->markWhenSite () == 'yes' ? ' checked="checked"' : ''; ?> />
					l'article est ouvert sur le site d'origine
				</label>
				<label class="checkbox" for="check_open_page">
					<input type="checkbox" name="mark_open_page" id="check_open_page" value="yes"<?php echo $this->conf->markWhenPage () == 'yes' ? ' checked="checked"' : ''; ?> />
					la page est chargée
				</label>
			</div>
		</div>

		<div class="form-group form-actions">
			<div class="group-controls">
				<button type="submit" class="btn btn-important">Valider</button>
				<button type="reset" class="btn">Annuler</button>
			</div>
		</div>
	</form>
</div>
