<?php $this->partial ('aside_configure'); ?>

<div class="post">
	<a href="<?php echo _url ('index', 'index'); ?>"><?php echo Minz_Translate::t ('back_to_rss_feeds'); ?></a>

	<form method="post" action="<?php echo _url ('configure', 'display'); ?>">
		<legend><?php echo Minz_Translate::t ('theme'); ?></legend>

		<div class="form-group">
			<label class="group-name" for="language"><?php echo Minz_Translate::t ('language'); ?></label>
			<div class="group-controls">
				<select name="language" id="language">
				<?php $languages = $this->conf->availableLanguages (); ?>
				<?php foreach ($languages as $short => $lib) { ?>
				<option value="<?php echo $short; ?>"<?php echo $this->conf->language === $short ? ' selected="selected"' : ''; ?>><?php echo $lib; ?></option>
				<?php } ?>
				</select>
			</div>
		</div>

		<div class="form-group">
			<label class="group-name" for="theme"><?php echo Minz_Translate::t ('theme'); ?></label>
			<div class="group-controls">
				<select name="theme" id="theme" required=""><?php
					$found = false;
					foreach ($this->themes as $theme) {
						?><option value="<?php echo $theme['id']; ?>"<?php if ($this->conf->theme === $theme['id']) { echo ' selected="selected"'; $found = true; } ?>><?php
							echo $theme['name'] . ' — ' . Minz_Translate::t ('by') . ' ' . $theme['author'];
						?></option><?php
					}
					if (!$found) {
						?><option selected="selected"></option><?php
					}
				?></select>
			</div>
		</div>

		<div class="form-group form-actions">
			<div class="group-controls">
				<button type="submit" class="btn btn-important"><?php echo Minz_Translate::t ('save'); ?></button>
				<button type="reset" class="btn"><?php echo Minz_Translate::t ('cancel'); ?></button>
			</div>
		</div>

		<legend><?php echo Minz_Translate::t ('reading_configuration'); ?></legend>

		<div class="form-group">
			<label class="group-name" for="posts_per_page"><?php echo Minz_Translate::t ('articles_per_page'); ?></label>
			<div class="group-controls">
				<input type="number" id="posts_per_page" name="posts_per_page" value="<?php echo $this->conf->posts_per_page; ?>" />
			</div>
		</div>

		<div class="form-group">
			<label class="group-name" for="sort_order"><?php echo Minz_Translate::t ('sort_order'); ?></label>
			<div class="group-controls">
				<select name="sort_order" id="sort_order">
					<option value="DESC"<?php echo $this->conf->sort_order === 'DESC' ? ' selected="selected"' : ''; ?>><?php echo Minz_Translate::t ('newer_first'); ?></option>
					<option value="ASC"<?php echo $this->conf->sort_order === 'ASC' ? ' selected="selected"' : ''; ?>><?php echo Minz_Translate::t ('older_first'); ?></option>
				</select>
			</div>
		</div>

		<div class="form-group">
			<label class="group-name" for="view_mode"><?php echo Minz_Translate::t ('default_view'); ?></label>
			<div class="group-controls">
				<select name="view_mode" id="view_mode">
					<option value="normal"<?php echo $this->conf->view_mode === 'normal' ? ' selected="selected"' : ''; ?>><?php echo Minz_Translate::t ('normal_view'); ?></option>
					<option value="reader"<?php echo $this->conf->view_mode === 'reader' ? ' selected="selected"' : ''; ?>><?php echo Minz_Translate::t ('reader_view'); ?></option>
					<option value="global"<?php echo $this->conf->view_mode === 'global' ? ' selected="selected"' : ''; ?>><?php echo Minz_Translate::t ('global_view'); ?></option>
				</select>
				<label class="radio" for="radio_all">
					<input type="radio" name="default_view" id="radio_all" value="all"<?php echo $this->conf->default_view === 'all' ? ' checked="checked"' : ''; ?> />
					<?php echo Minz_Translate::t ('show_all_articles'); ?>
				</label>
				<label class="radio" for="radio_not_read">
					<input type="radio" name="default_view" id="radio_not_read" value="not_read"<?php echo $this->conf->default_view === 'not_read' ? ' checked="checked"' : ''; ?> />
					<?php echo Minz_Translate::t ('show_not_reads'); ?>
				</label>
			</div>
		</div>

		<div class="form-group">
			<div class="group-controls">
				<label class="checkbox" for="auto_load_more">
					<input type="checkbox" name="auto_load_more" id="auto_load_more" value="1"<?php echo $this->conf->auto_load_more ? ' checked="checked"' : ''; ?> />
					<?php echo Minz_Translate::t ('auto_load_more'); ?>
					<noscript> — <strong><?php echo Minz_Translate::t ('javascript_should_be_activated'); ?></strong></noscript>
				</label>
			</div>
		</div>

		<div class="form-group">
			<div class="group-controls">
				<label class="checkbox" for="display_posts">
					<input type="checkbox" name="display_posts" id="display_posts" value="1"<?php echo $this->conf->display_posts ? ' checked="checked"' : ''; ?> />
					<?php echo Minz_Translate::t ('display_articles_unfolded'); ?>
					<noscript> — <strong><?php echo Minz_Translate::t ('javascript_should_be_activated'); ?></strong></noscript>
				</label>
			</div>
		</div>

		<div class="form-group">
			<div class="group-controls">
				<label class="checkbox" for="lazyload">
					<input type="checkbox" name="lazyload" id="lazyload" value="1"<?php echo $this->conf->lazyload ? ' checked="checked"' : ''; ?> />
					<?php echo Minz_Translate::t ('img_with_lazyload'); ?>
					<noscript> — <strong><?php echo Minz_Translate::t ('javascript_should_be_activated'); ?></strong></noscript>
				</label>
			</div>
		</div>

		<div class="form-group">
			<label class="group-name"><?php echo Minz_Translate::t ('auto_read_when'); ?></label>
			<div class="group-controls">
				<label class="checkbox" for="check_open_article">
					<input type="checkbox" name="mark_open_article" id="check_open_article" value="1"<?php echo $this->conf->mark_when['article'] ? ' checked="checked"' : ''; ?> />
					<?php echo Minz_Translate::t ('article_selected'); ?>
				</label>
				<label class="checkbox" for="check_open_site">
					<input type="checkbox" name="mark_open_site" id="check_open_site" value="1"<?php echo $this->conf->mark_when['site'] ? ' checked="checked"' : ''; ?> />
					<?php echo Minz_Translate::t ('article_open_on_website'); ?>
				</label>
				<label class="checkbox" for="check_scroll">
					<input type="checkbox" name="mark_scroll" id="check_scroll" value="1"<?php echo $this->conf->mark_when['scroll'] ? ' checked="checked"' : ''; ?> />
					<?php echo Minz_Translate::t ('scroll'); ?>
				</label>
				<label class="checkbox" for="check_reception">
					<input type="checkbox" name="mark_upon_reception" id="check_reception" value="1"<?php echo $this->conf->mark_when['reception'] ? ' checked="checked"' : ''; ?> />
					<?php echo Minz_Translate::t ('upon_reception'); ?>
				</label>
			</div>
		</div>

		<div class="form-group">
			<label class="group-name"><?php echo Minz_Translate::t ('after_onread'); ?></label>
			<div class="group-controls">
				<label class="checkbox" for="onread_jump_next">
					<input type="checkbox" name="onread_jump_next" id="onread_jump_next" value="1"<?php echo $this->conf->onread_jump_next ? ' checked="checked"' : ''; ?> />
					<?php echo Minz_Translate::t ('jump_next'); ?>
				</label>
			</div>
		</div>

		<div class="form-group form-actions">
			<div class="group-controls">
				<button type="submit" class="btn btn-important"><?php echo Minz_Translate::t ('save'); ?></button>
				<button type="reset" class="btn"><?php echo Minz_Translate::t ('cancel'); ?></button>
			</div>
		</div>

		<legend><?php echo Minz_Translate::t ('reading_icons'); ?></legend>
		<div class="form-group">
			<table>
				<thead>
					<tr>
						<th> </th>
						<th title="<?php echo Minz_Translate::t ('mark_read'); ?>"><?php echo FreshRSS_Themes::icon('read'); ?></th>
						<th title="<?php echo Minz_Translate::t ('mark_favorite'); ?>"><?php echo FreshRSS_Themes::icon('bookmark'); ?></th>
						<th><?php echo Minz_Translate::t ('sharing'); ?></th>
						<th><?php echo Minz_Translate::t ('related_tags'); ?></th>
						<th><?php echo Minz_Translate::t ('publication_date'); ?></th>
						<th><?php echo FreshRSS_Themes::icon('link'); ?></th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<th><?php echo Minz_Translate::t ('top_line'); ?></th>
						<td><input type="checkbox" name="topline_read" value="1"<?php echo $this->conf->topline_read ? ' checked="checked"' : ''; ?> /></td>
						<td><input type="checkbox" name="topline_favorite" value="1"<?php echo $this->conf->topline_favorite ? ' checked="checked"' : ''; ?> /></td>
						<td><input type="checkbox" disabled="disabled" /></td>
						<td><input type="checkbox" disabled="disabled" /></td>
						<td><input type="checkbox" name="topline_date" value="1"<?php echo $this->conf->topline_date ? ' checked="checked"' : ''; ?> /></td>
						<td><input type="checkbox" name="topline_link" value="1"<?php echo $this->conf->topline_link ? ' checked="checked"' : ''; ?> /></td>
					</tr><tr>
						<th><?php echo Minz_Translate::t ('bottom_line'); ?></th>
						<td><input type="checkbox" name="bottomline_read" value="1"<?php echo $this->conf->bottomline_read ? ' checked="checked"' : ''; ?> /></td>
						<td><input type="checkbox" name="bottomline_favorite" value="1"<?php echo $this->conf->bottomline_favorite ? ' checked="checked"' : ''; ?> /></td>
						<td><input type="checkbox" name="bottomline_sharing" value="1"<?php echo $this->conf->bottomline_sharing ? ' checked="checked"' : ''; ?> /></td>
						<td><input type="checkbox" name="bottomline_tags" value="1"<?php echo $this->conf->bottomline_tags ? ' checked="checked"' : ''; ?> /></td>
						<td><input type="checkbox" name="bottomline_date" value="1"<?php echo $this->conf->bottomline_date ? ' checked="checked"' : ''; ?> /></td>
						<td><input type="checkbox" name="bottomline_link" value="1"<?php echo $this->conf->bottomline_link ? ' checked="checked"' : ''; ?> /></td>
					</tr>
				</tbody>
			</table><br />
		</div>

		<div class="form-group form-actions">
			<div class="group-controls">
				<button type="submit" class="btn btn-important"><?php echo Minz_Translate::t ('save'); ?></button>
				<button type="reset" class="btn"><?php echo Minz_Translate::t ('cancel'); ?></button>
			</div>
		</div>
	</form>
</div>
