<?php $this->partial ('aside_feed'); ?>

<?php if ($this->flux) { ?>
<div class="post">
	<a href="<?php echo _url ('index', 'index'); ?>">← Retour à vos flux RSS</a>

	<h1><?php echo $this->flux->name (); ?></h1>
	<?php echo $this->flux->description (); ?>

	<form method="post" action="<?php echo _url ('configure', 'feed', 'id', $this->flux->id ()); ?>">
		<legend>Informations</legend>

		<div class="form-group">
			<label class="group-name">URL du site</label>
			<div class="group-controls">
				<span class="control"><a target="_blank" href="<?php echo $this->flux->website (); ?>"><?php echo $this->flux->website (); ?></a></span>
			</div>
		</div>

		<div class="form-group">
			<label class="group-name">URL du flux</label>
			<div class="group-controls">
				<span class="control"><a target="_blank" href="<?php echo $this->flux->url (); ?>"><?php echo $this->flux->url (); ?></a></span>
			</div>
		</div>
	
		<div class="form-group">
			<label class="group-name">Nombre d'articles</label>
			<div class="group-controls">
				<span class="control"><?php echo $this->flux->nbEntries (); ?></span>
			</div>
		</div>
	
		<legend>Catégorie - <a href="<?php echo _url ('configure', 'categorize'); ?>">gestion</a></legend>
		<div class="form-group">
			<label class="group-name">Ranger dans une catégorie</label>
			<div class="group-controls">
				<?php foreach ($this->categories as $cat) { ?>
				<label class="radio" for="cat_<?php echo $cat->id (); ?>">
					<input type="radio" name="category" id="cat_<?php echo $cat->id (); ?>" value="<?php echo $cat->id (); ?>"<?php echo $cat->id () == $this->flux->category () ? ' checked="checked"' : ''; ?> />
					<?php echo $cat->name (); ?>
				</label>
				<?php } ?>
			</div>
		</div>

		<legend>Avancé</legend>
		<div class="form-group">
			<label class="group-name" for="path_entries">Chemin CSS des articles sur le site d'origine</label>
			<div class="group-controls">
				<input type="text" name="path_entries" id="path_entries" value="<?php echo $this->flux->pathEntries (); ?>" placeholder="Laissez vide pour désactiver" />
				<i class="icon i_help"></i> Permet de récupérer les flux tronqués (attention, demande plus de temps !)
			</div>
		</div>

<!--
		<div class="form-group">
			<label class="group-name" for="http_user">Username HTTP</label>
			<div class="group-controls">
				<input type="text" name="http_user" id="http_user" value="Pas encore implémenté" />
				<i class="icon i_help"></i> La connexion permet d'accéder aux flux protégés par une authentification HTTP
			</div>

			<label class="group-name" for="http_pass">Password HTTP</label>
			<div class="group-controls">
				<input type="text" name="http_pass" id="http_pass" value="Pas encore implémenté" />
			</div>
		</div>
-->

		<div class="form-group form-actions">
			<div class="group-controls">
				<button class="btn btn-important">Valider</button>
				<button class="btn btn-attention" formaction="<?php echo Url::display (array ('c' => 'feed', 'a' => 'delete', 'params' => array ('id' => $this->flux->id ()))); ?>">Supprimer</button>
			</div>
		</div>
	</form>
</div>
<?php } else { ?>
<div class="alert"><span class="alert-head">Aucun flux sélectionné.</span> Pensez à en ajouter !</div>
<?php } ?>
