<?php $this->partial ('aside_feed'); ?>

<?php if ($this->flux) { ?>
<form method="post" action="">
	<h1><?php echo $this->flux->name (); ?></h1>
	<?php echo $this->flux->description (); ?>
	
	<label>URL du site</label>
	<span><a target="_blank" href="<?php echo $this->flux->website (); ?>"><?php echo $this->flux->website (); ?></a></span>
	
	<label>Nombre d'articles</label>
	<span><?php echo $this->flux->nbEntries (); ?></span>
	
	<?php if (!empty ($this->categories)) { ?>
	<label>Ranger dans une catégorie</label>
	<div class="radio_group">
		<?php foreach ($this->categories as $cat) { ?>
		<input type="radio" name="category" id="cat_<?php echo $cat->id (); ?>" value="<?php echo $cat->id (); ?>"<?php echo $cat->id () == $this->flux->category () ? ' checked="checked"' : ''; ?> />
		<label for="cat_<?php echo $cat->id (); ?>"><?php echo $cat->name (); ?></label>
		<br />
		<?php } ?>
	</div>
	
	<button class="btn btn-important">Valider</button>
	<?php } ?>
	
	<button class="btn" formaction="<?php echo Url::display (array ('c' => 'feed', 'a' => 'delete', 'params' => array ('id' => $this->flux->id ()))); ?>">Supprimer</button>
</form>
<?php } else { ?>
<div class="alert"><span class="alert-head">Aucun flux sélectionné.</span> Pensez à en ajouter !</div>
<?php } ?>
