<?php $this->partial('aside_configure'); ?>

<div class="post">
	<a href="<?php echo _url('index', 'index'); ?>"><?php echo _t('gen.action.back_to_rss_feeds'); ?></a>

	<form method="post" action="<?php echo _url('configure', 'system'); ?>">
		<input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />
		<legend><?php echo _t('admin.system'); ?></legend>

		<div class="form-group">
			<label class="group-name" for="instance-name"><?php echo _t('admin.system.instance-name'); ?></label>
			<div class="group-controls">
			    <input type="text" class="extend" id="instance-name" name="instance-name" value="<?php echo FreshRSS_Context::$system_conf->title; ?>" data-leave-validation="<?php echo FreshRSS_Context::$system_conf->title; ?>"/>
			</div>
		</div>

		<div class="form-group">
			<label class="group-name" for="auto-update-url"><?php echo _t('admin.system.auto-update-url'); ?></label>
			<div class="group-controls">
			    <input type="text" class="extend" id="auto-update-url" name="auto-update-url" value="<?php echo FreshRSS_Context::$system_conf->auto_update_url; ?>" data-leave-validation="<?php echo FreshRSS_Context::$system_conf->auto_update_url; ?>"/>
			</div>
		</div>

		<div class="form-group">
			<label class="group-name" for="max-registrations"><?php echo _t('admin.system.registration.number'); ?></label>
			<div class="group-controls">
				<input type="number" id="max-registrations" name="max-registrations" value="<?php echo FreshRSS_Context::$system_conf->limits['max_registrations']; ?>" min="0" data-leave-validation="<?php echo FreshRSS_Context::$system_conf->limits['max_registrations']; ?>"/>
				<?php echo _i('help'); ?> <?php echo _t('admin.system.registration.help'); ?>
			</div>
		</div>

		<div class="form-group">
			<div class="group-controls">
				<?php
					$number = count(listUsers());
					echo ($number > 1 ? _t('admin.user.numbers', $number) : _t('admin.user.number', $number));
				?>
			</div>
		</div>

		<?php if ($this->can_enable_email_validation) { ?>
			<div class="form-group">
				<div class="group-controls">
					<label class="checkbox" for="force-email-validation">
						<input
							type="checkbox"
							name="force-email-validation"
							id="force-email-validation"
							value="1"
							<?php echo FreshRSS_Context::$system_conf->force_email_validation ? 'checked="checked"' : ''; ?>
							data-leave-validation="<?php echo FreshRSS_Context::$system_conf->force_email_validation; ?>"
						/>
						<?php echo _t('admin.system.force_email_validation'); ?>
					</label>
				</div>
			</div>
		<?php } ?>

		<div class="form-group">
			<label class="group-name" for="max-feeds"><?php echo _t('admin.system.max-feeds'); ?></label>
			<div class="group-controls">
			    <input type="number" id="max-feeds" name="max-feeds" value="<?php echo FreshRSS_Context::$system_conf->limits['max_feeds']; ?>" min="1" data-leave-validation="<?php echo FreshRSS_Context::$system_conf->limits['max_feeds']; ?>"/>
			</div>
		</div>

		<div class="form-group">
			<label class="group-name" for="max-categories"><?php echo _t('admin.system.max-categories'); ?></label>
			<div class="group-controls">
			    <input type="number" id="max-categories" name="max-categories" value="<?php echo FreshRSS_Context::$system_conf->limits['max_categories']; ?>" min="1" data-leave-validation="<?php echo FreshRSS_Context::$system_conf->limits['max_categories']; ?>"/>
			</div>
		</div>

		<div class="form-group">
			<label class="group-name" for="cookie-duration"><?php echo _t('admin.system.cookie-duration.number'); ?></label>
			<div class="group-controls">
				<input type="number" id="cookie-duration" name="cookie-duration" value="<?php echo FreshRSS_Context::$system_conf->limits['cookie_duration']; ?>" min="0" data-leave-validation="<?php echo FreshRSS_Context::$system_conf->limits['cookie_duration']; ?>"/>
				<?php echo _i('help'); ?> <?php echo _t('admin.system.cookie-duration.help'); ?>
			</div>
		</div>

		<div class="form-group form-actions">
			<div class="group-controls">
				<button type="submit" class="btn btn-important"><?php echo _t('gen.action.submit'); ?></button>
				<button type="reset" class="btn"><?php echo _t('gen.action.cancel'); ?></button>
			</div>
		</div>
	</form>
</div>
