<?php $this->partial('aside_configure'); ?>

<div class="post">
	<a href="<?php echo _url('index', 'index'); ?>"><?php echo Minz_Translate::t('back_to_rss_feeds'); ?></a>

	<form method="post" action="<?php echo _url('configure', 'users'); ?>">
		<legend><?php echo Minz_Translate::t('login_configuration'); ?></legend>

		<div class="form-group">
			<label class="group-name" for="current_user"><?php echo Minz_Translate::t('current_user'); ?></label>
			<div class="group-controls">
				<input id="current_user" type="text" disabled="disabled" value="<?php echo Minz_Session::param('currentUser', '_'); ?>" />
				<code>$_SERVER['REMOTE_USER'] = <?php echo httpAuthUser(); ?></code>
				<label class="checkbox" for="is_admin">
					<input type="checkbox" id="is_admin" disabled="disabled"<?php echo Minz_Configuration::isAdmin(Minz_Session::param('currentUser', '_')) ? ' checked="checked"' : ''; ?> />
					<?php echo Minz_Translate::t('is_admin'); ?>
				</label>
			</div>
		</div>

		<div class="form-group">
			<label class="group-name" for="mail_login"><?php echo Minz_Translate::t('persona_connection_email'); ?></label>
			<?php $mail = $this->conf->mail_login; ?>
			<div class="group-controls">
				<input type="email" id="mail_login" name="mail_login" value="<?php echo $mail ? $mail : ''; ?>" placeholder="alice@example.net" />
				<noscript><b><?php echo Minz_Translate::t('javascript_should_be_activated'); ?></b></noscript>
			</div>
		</div>

		<div class="form-group form-actions">
			<div class="group-controls">
				<button type="submit" class="btn btn-important"><?php echo Minz_Translate::t('save'); ?></button>
				<button type="reset" class="btn"><?php echo Minz_Translate::t('cancel'); ?></button>
			</div>
		</div>

		<?php if (Minz_Configuration::isAdmin(Minz_Session::param('currentUser', '_'))) { ?>

		<legend><?php echo Minz_Translate::t('users'); ?></legend>

		<div class="form-group">
			<label class="group-name" for="auth_type"><?php echo Minz_Translate::t('auth_type'); ?></label>
			<div class="group-controls">
				<select id="auth_type" name="auth_type">
					<option value="none"<?php echo Minz_Configuration::authType() === 'none' ? ' selected="selected"' : ''; ?>><?php echo Minz_Translate::t('auth_none'); ?></option>
					<option value="http_auth"<?php echo Minz_Configuration::authType() === 'http_auth' ? ' selected="selected"' : '', httpAuthUser() == '' ? ' disabled="disabled"' : ''; ?>>HTTP Auth</option>
					<option value="persona"<?php echo Minz_Configuration::authType() === 'persona' ? ' selected="selected"' : ''; ?>>Mozilla Persona</option>
				</select>
			</div>
		</div>

		<div class="form-group">
			<label class="group-name" for="users_list"><?php echo Minz_Translate::t('users_list'); ?></label>
			<div class="group-controls">
				<select id="users_list" name="users_list"><?php
					foreach (listUsers() as $user) {
						echo '<option>', $user, '</option>';
					}
				?></select>
			</div>
		</div>

		<div class="form-group form-actions">
			<div class="group-controls">
				<button type="submit" class="btn btn-important"><?php echo Minz_Translate::t('save'); ?></button>
				<button type="reset" class="btn"><?php echo Minz_Translate::t('cancel'); ?></button>
			</div>
		</div>

		<legend>Mozilla Persona</legend>
		<div class="form-group">
			<div class="group-controls">
				<label class="checkbox" for="anon_access">
					<input type="checkbox" name="anon_access" id="anon_access" value="1"<?php echo Minz_Configuration::allowAnonymous() ? ' checked="checked"' : ''; ?> />
					<?php echo Minz_Translate::t('allow_anonymous', Minz_Configuration::defaultUser()); ?>
				</label>
			</div>
		</div>

		<div class="form-group">
			<label class="group-name" for="token"><?php echo Minz_Translate::t('auth_token'); ?></label>
			<?php $token = $this->conf->token; ?>
			<div class="group-controls">
				<input type="text" id="token" name="token" value="<?php echo $token; ?>"  placeholder="<?php echo Minz_Translate::t('blank_to_disable'); ?>"/>
				<?php echo FreshRSS_Themes::icon('help'); ?> <?php echo Minz_Translate::t('explain_token', Minz_Url::display(null, 'html', true), $token); ?>
			</div>
		</div>

		<div class="form-group form-actions">
			<div class="group-controls">
				<button type="submit" class="btn btn-important"><?php echo Minz_Translate::t('save'); ?></button>
				<button type="reset" class="btn"><?php echo Minz_Translate::t('cancel'); ?></button>
			</div>
		</div>

		<?php } ?>
	</form>
</div>
