<?php
	declare(strict_types=1);
	/** @var View $this */

use FreshRss\Models\Auth;
use FreshRss\Models\Context;
use FreshRss\Models\View;

?>
<main class="post">
	<p>
		<?= _t('user.email.validation.need_to', Context::systemConf()->title) ?>
	</p>

	<p>
		<?= _t('user.email.validation.email_sent_to', Context::userConf()->mail_login) ?>
	</p>

	<form action="<?= _url('user', 'sendValidationEmail') ?>" method="post">
		<input type="hidden" name="_csrf" value="<?= Auth::csrfToken() ?>" />
		<button type="submit" class="btn">
			<?= _t('user.email.validation.resend_email') ?>
		</button>
	</form>

	<p>
		<small>
			<?= _t('user.email.validation.change_email', _url('user', 'profile')) ?>
		</small>
	</p>
</main>
