<?php
	declare(strict_types=1);
	/** @var FreshRSS_View $this */
	$this->partial('aside_configure');
?>
<main class="post">
	<h1><?= _t('gen.menu.check_install') ?></h1>
	<h2><?= _t('install.check.php') ?></h2>

	<?php foreach ($this->status_php as $key => $status) { ?>
	<p class="alert <?= match ($status) { 'ok' => 'alert-success', 'warn' => 'alert-warn', default => 'alert-error' } ?>">
		<?php
			if ($key === 'php') {
				echo _t('install.check.' . $key . '.' . ($status === 'ok' ? 'ok' : 'nok'), PHP_VERSION, FRESHRSS_MIN_PHP_VERSION);
			} else {
				echo _t('install.check.' . $key . '.' . ($status === 'ok' ? 'ok' : 'nok'));
			}
		?>
	</p>
	<?php } ?>

	<h2><?= _t('install.check.files') ?></h2>

	<?php foreach ($this->status_files as $key => $status) { ?>
	<p class="alert <?= match ($status) { 'ok' => 'alert-success', 'warn' => 'alert-warn', default => 'alert-error' } ?>">
		<?= _t('install.check.' . $key . '.' . ($status === 'ok' ? 'ok' : 'nok')) ?>
	</p>
	<?php } ?>

	<?php /*
	<h2><?= _t('install.check.database') ?></h2>

	<?php foreach ($this->status_database as $key => $status) { ?>
	<p class="alert <?= match ($status) { 'ok' => 'alert-success', 'warn' => 'alert-warn', default => 'alert-error' } ?>">
		<?= _t('install.check.' . $key . '.' . ($status === 'ok' ? 'ok' : 'nok')) ?>
	</p>
	<?php } ?>
	*/ ?>

</main>
