<?php $this->partial('aside_configure'); ?>

<div class="post">
	<a href="<?php echo _url('index', 'index'); ?>"><?php echo _t('gen.action.back_to_rss_feeds'); ?></a>

	<h2><?php echo _t('admin.check_install.php'); ?></h2>

	<?php foreach ($this->status_php as $key => $status) { ?>
	<p class="alert <?php echo $status ? 'alert-success' : 'alert-error'; ?>">
		<?php
			if ($key === 'php') {
				echo _t('admin.check_install.' . $key . '.' . ($status ? 'ok' : 'nok'), PHP_VERSION, '5.6.0');
			} else {
				echo _t('admin.check_install.' . $key . '.' . ($status ? 'ok' : 'nok'));
			}
		?>
	</p>
	<?php } ?>

	<h2><?php echo _t('admin.check_install.files'); ?></h2>

	<?php foreach ($this->status_files as $key => $status) { ?>
	<p class="alert <?php echo $status ? 'alert-success' : 'alert-error'; ?>">
		<?php echo _t('admin.check_install.' . $key . '.' . ($status ? 'ok' : 'nok')); ?>
	</p>
	<?php } ?>

	<?php /*
	<h2><?php echo _t('admin.check_install.database'); ?></h2>

	<?php foreach ($this->status_database as $key => $status) { ?>
	<p class="alert <?php echo $status ? 'alert-success' : 'alert-error'; ?>">
		<?php echo _t('admin.check_install.' . $key . '.' . ($status ? 'ok' : 'nok')); ?>
	</p>
	<?php } ?>
	*/ ?>

</div>
