<?php $this->partial('aside_configure'); ?>

<div class="post">
	<a href="<?php echo _url('index', 'index'); ?>"><?php echo _t('gen.action.back_to_rss_feeds'); ?></a>

	<h1><?php echo _t('admin.update'); ?></h1>

	<p>
		<?php echo _i('help'); ?> <?php echo _t('admin.update.current_version', FRESHRSS_VERSION); ?>
	</p>

	<p>
		<?php echo _t('admin.update.last', $this->last_update_time); ?>
	</p>

	<?php if (!empty($this->message)) { ?>
    <?php
        $class = 'alert-warn';
        switch ($this->message['status']) {
            case 'bad':
                $class = 'alert-error';
                break;
            case 'latest':
                $class = 'alert-success';
                break;
            default:
                $class = 'alert-warn';
                break;
        }
    ?>
	<p class="alert <?php echo $class; ?>">
		<span class="alert-head"><?php echo $this->message['title']; ?></span>
		<?php echo $this->message['body']; ?>
	</p>
	<?php } ?>

	<?php
		if (empty($this->message) || $this->message['status'] !== 'good') {
	?>
	<p>
		<a href="<?php echo _url('update', 'check'); ?>" class="btn"><?php echo _t('admin.update.check'); ?></a>
	</p>
	<?php } ?>

	<?php if ($this->update_to_apply) { ?>
	<a class="btn btn-important" href="<?php echo _url('update', 'apply'); ?>"><?php echo _t('admin.update.apply'); ?></a>
	<?php } ?>
</div>
