<?php
header('Content-Type: application/json; charset=UTF-8');

$url = array(
	'c' => Minz\Request::controllerName(),
	'a' => Minz\Request::actionName(),
	'params' => Minz\Request::fetchGET(),
);

$url['params']['is_favorite'] = Minz\Request::param('is_favorite', true) ? '0' : '1';

FreshRSS::loadStylesAndScripts();
echo json_encode(array(
		'url' => str_ireplace('&amp;', '&', Minz\Url::display($url)),
		'icon' => _i($url['params']['is_favorite'] === '1' ? 'non-starred' : 'starred')
	));
