<?php $this->partial ('aside_flux'); ?>

<div class="post">
	<a href="<?php echo _url ('index', 'index'); ?>">← Retour à vos flux RSS</a>

	<form method="post" action="<?php echo _url ('entry', 'note', 'id', $this->entry->id ()); ?>">
		<legend>Note</legend>

		<div class="form-group">
			<label class="group-name" for="note">Ajouter une note</label>
			<div class="group-controls">
				<textarea rows="5" cols="80" name="note" id="note"><?php echo $this->entry->notes (); ?></textarea>
			</div>
		</div>
		<div class="form-group">
			<label class="group-name" for="public_note">Article public ?</label>
			<div class="group-controls">
				<label class="checkbox" for="public">
					<input type="checkbox" name="public" id="public" value="yes"<?php echo $this->entry->isPublic () ? ' checked="checked"' : ''; ?> /> Oui
				</label>
			</div>
		</div>

		<div class="form-group form-actions">
			<div class="group-controls">
				<button type="submit" class="btn btn-important">Sauvegarder</button>
				<button type="reset" class="btn">Annuler</button>
			</div>
		</div>

		<legend>Article</legend>

		<div class="form-group">
			<label class="group-name">Titre</label>
			<div class="group-controls">
				<span class="control"><a href="<?php echo $this->entry->link (); ?>"><?php echo $this->entry->title (); ?></a></span>
			</div>
		</div>

		<?php
		$author = $this->entry->author ();
		if ($author) { ?>
		<div class="form-group">
			<label class="group-name">Auteur</label>
			<div class="group-controls">
				<span class="control"><?php echo $author; ?></span>
			</div>
		</div>
		<?php } ?>

		<div class="form-group">
			<label class="group-name">Date de publication</label>
			<div class="group-controls">
				<span class="control"><?php echo $this->entry->date (); ?></span>
			</div>
		</div>

		<div class="form-group">
			<label class="group-name">Article</label>
			<div class="group-controls">
				<span class="control"><?php echo $this->entry->content (); ?></span>
			</div>
		</div>
	</form>
</div>
