<?php $this->partial ('aside_flux'); ?>

<div class="post">
	<a href="<?php echo _url ('index', 'index'); ?>"><?php echo Translate::t ('back_to_rss_feeds'); ?></a>

	<form method="post" action="<?php echo _url ('entry', 'note', 'id', $this->entry->id ()); ?>">
		<legend><?php echo Translate::t ('note'); ?></legend>

		<div class="form-group">
			<label class="group-name" for="note"><?php echo Translate::t ('add_note'); ?></label>
			<div class="group-controls">
				<textarea rows="5" cols="80" name="note" id="note"><?php echo $this->entry->notes (); ?></textarea>
			</div>
		</div>
		<div class="form-group">
			<label class="group-name" for="public_note"><?php echo Translate::t ('ask_public_article'); ?></label>
			<div class="group-controls">
				<label class="checkbox" for="public">
					<input type="checkbox" name="public" id="public" value="yes"<?php echo $this->entry->isPublic () ? ' checked="checked"' : ''; ?> /> <?php echo Translate::t ('yes'); ?>
				</label>
			</div>
		</div>

		<div class="form-group form-actions">
			<div class="group-controls">
				<button type="submit" class="btn btn-important"><?php echo Translate::t ('save'); ?></button>
				<button type="reset" class="btn"><?php echo Translate::t ('cancel'); ?></button>
			</div>
		</div>

		<legend><?php echo Translate::t ('article'); ?></legend>

		<div class="form-group">
			<label class="group-name"><?php echo Translate::t ('title'); ?></label>
			<div class="group-controls">
				<span class="control"><a href="<?php echo $this->entry->link (); ?>"><?php echo $this->entry->title (); ?></a></span>
			</div>
		</div>

		<?php
		$author = $this->entry->author ();
		if ($author) { ?>
		<div class="form-group">
			<label class="group-name"><?php echo Translate::t ('author'); ?></label>
			<div class="group-controls">
				<span class="control"><?php echo $author; ?></span>
			</div>
		</div>
		<?php } ?>

		<div class="form-group">
			<label class="group-name"><?php echo Translate::t ('publication_date'); ?></label>
			<div class="group-controls">
				<span class="control"><?php echo $this->entry->date (); ?></span>
			</div>
		</div>

		<div class="form-group">
			<label class="group-name"><?php echo Translate::t ('article'); ?></label>
			<div class="group-controls">
				<span class="control"><?php echo $this->entry->content (); ?></span>
			</div>
		</div>
	</form>
</div>
