apiVersion: apps/v1
kind: StatefulSet # Stateful set, as we only ever want a single copy of freshrss running.
metadata:
  labels:
    app: freshrss
  name: freshrss
  namespace: freshrss
  annotations:
    # Keel annotations, useful if you have keel in your cluster. Won't hurt anything if it is not installed.
    keel.sh/policy: all
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@daily"
    keel.sh/approvals: "1"
    keel.sh/releaseNotes: "https://github.com/FreshRSS/FreshRSS/blob/edge/CHANGELOG.md"
spec:
  replicas: 1
  serviceName: freshrss
  selector:
    matchLabels:
      app: freshrss
  template:
    metadata:
      labels:
        app: freshrss
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: freshrss-data
      containers:
        - name: freshrss
          image: freshrss/freshrss:latest #1.22.0 - Change to match the version tag wanted.
          envFrom:
            - configMapRef:
                name: freshrss-config
                optional: true
            - secretRef:
                name: freshrss-secrets
                optional: true
          volumeMounts:
            # Add other volume mounts / subpaths as needed.
            - mountPath: "/var/www/FreshRSS/data"
              name: data
              subPath: www/freshrss/data
          ports:
          - containerPort: 80
            name: http
