# Environment Variables for FreshRSS                                                                                              freshrss-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: freshrss-config
  namespace: freshrss
data:
  # Default cron-timer schedule.
  CRON_MIN: "*/15"

  # See https://freshrss.github.io/FreshRSS/en/admins/16_OpenID-Connect.html
  OIDC_ENABLED: "0"
  OIDC_PROVIDER_METADATA_URL: ""
  OIDC_REMOTE_USER_CLAIM: preferred_username
  OIDC_CLIENT_ID: ""
  OIDC_SCOPES: "openid profile"
  OIDC_X_FORWARDED_HEADERS: X-Forwarded-Host X-Forwarded-Port X-Forwarded-Proto
  
  ADMIN_EMAIL: ""
