# Persistent Storage for FreshRSS

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss
  namespace: freshrss
spec:
  # Put your storage class name here, or leave blank to use the default cluster storage-class.
  storageClassName: 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # Change as you see fit.
      storage: 5Gi
