<?php

// Plural-Forms: nplurals=1; plural=0;
// This file is generated by cli/compile.plurals.php.
// Edit the formula comment and run `make fix-all`.

return array(
	'nplurals' => 1,
	'plural' => static fn (int $n): int => 0,
);
