source "https://rubygems.org"

gem "kramdown-parser-gfm"

group :jekyll_plugins do
  gem 'jekyll-coffeescript'
  gem 'jekyll-commonmark-ghpages'
  gem 'jekyll-gist'
  gem 'jekyll-github-metadata'
  gem 'jekyll-paginate'
  gem 'jekyll-relative-links'
  gem 'jekyll-optional-front-matter'
  gem 'jekyll-readme-index'
  gem 'jekyll-default-layout'
  gem 'jekyll-titles-from-headings'
  gem 'jekyll-i18n_tags'
end
