<?php
	/** @var FreshRSS_View $this */
	$this->partial('aside_subscription');
?>

<main class="post">
	<div class="link-back-wrapper">
		<a class="link-back" href="<?= _url('index', 'index') ?>"><?= _t('gen.action.back_to_rss_feeds') ?></a>
	</div>

	<h1><?= _t('admin.stats.idle') ?></h1>

	<?php
		$current_url = Minz_Url::display(
			array('c' => 'stats', 'a' => 'idle'),
			'php', true
		);
		$nothing = true;
		foreach ($this->idleFeeds as $period => $feeds) {
			if (!empty($feeds)) {
				$nothing = false;
	?>
	<div class="box">
		<div class="box-title"><?= _t('gen.date.' . $period) ?></div>
			<ul class="box-content">
				<?php foreach ($feeds as $feed) { ?>
					<li class="item feed">
						<a class="configure open-slider" href="<?= _url('stats', 'feed', 'id', $feed['id'], 'sub', 'idle') ?>" title="<?= _t('gen.action.manage') ?>"><?= _i('configure') ?></a>
						<?php if (FreshRSS_Context::$user_conf->show_favicons): ?><img class="favicon" src="<?= $feed['favicon'] ?>" alt="✇" loading="lazy" /><?php endif; ?>
						<span title="<?= timestamptodate($feed['last_date'], false) ?>"><?= $feed['name'] ?>
							(<?= _t('admin.stats.number_entries', $feed['nb_articles']) ?>)</span>
					</li>
				<?php } ?>
			</ul>
	</div>
	<?php
			}
		}

		if ($nothing) {
	?>
	<p class="alert alert-warn">
		<span class="alert-head"><?= _t('admin.stats.no_idle') ?></span>
	</p>
	<?php } ?>

	<?php $class = $this->displaySlider ? ' class="active"' : ''; ?>
	<a href="#" id="close-slider"<?= $class ?>>
		<?= _i('close') ?>
	</a>
	<div id="slider"<?= $class ?>>
	<?php
		if (isset($this->feed)) {
			$this->renderHelper('feed/update');
		}
	?>
	</div>
	<script src="../scripts/slider.js?<?= @filemtime(PUBLIC_PATH . '/scripts/slider.js') ?>"></script>
</main>
