<?php $this->partial('aside_stats'); ?>

<div class="post">
	<div class="backToFeeds">
		<a href="<?= _url('index', 'index') ?>"><?= _t('gen.action.back_to_rss_feeds') ?></a>
	</div>

	<h1><?= _t('admin.stats.idle') ?></h1>

	<?php
		$current_url = Minz_Url::display(
			array('c' => 'stats', 'a' => 'idle'),
			'php', true
		);
		$nothing = true;
		foreach ($this->idleFeeds as $period => $feeds) {
			if (!empty($feeds)) {
				$nothing = false;
	?>
		<div class="stat">
			<h2><?= _t('gen.date.' . $period) ?></h2>

			<form id="form-delete" method="post">
			<input type="hidden" name="_csrf" value="<?= FreshRSS_Auth::csrfToken() ?>" />
			<?php foreach ($feeds as $feed) { ?>
			<ul class="horizontal-list">
				<li class="item">
					<div class="stick">
						<a class="btn" href="<?= _url('index', 'index', 'get', 'f_' . $feed['id']) ?>"><?= _i('link') ?> <?= _t('gen.action.filter') ?></a>
						<a class="btn" href="<?= _url('subscription', 'index', 'id', $feed['id']) ?>"><?= _i('configure') ?> <?= _t('gen.action.manage') ?></a>
						<button class="btn btn-attention confirm" form="form-delete"
							formaction="<?= _url('feed', 'delete', 'id', $feed['id'], 'r', $current_url) ?>"><?= _t('gen.action.remove') ?></button>
					</div>
				</li>
				<li class="item">
					<span title="<?= timestamptodate($feed['last_date'], false) ?>"><?= $feed['name'] ?>
						(<?= _t('admin.stats.number_entries', $feed['nb_articles']) ?>)</span>
				</li>
			</ul>
			<?php } ?>
			</form>
		</div>
	<?php
			}
		}

		if ($nothing) {
	?>
	<p class="alert alert-warn">
		<span class="alert-head"><?= _t('admin.stats.no_idle') ?></span>
	</p>
	<?php } ?>
</div>
