<?php $this->partial('aside_stats'); ?>

<div class="post ">
	<div class="backToFeeds">
		<a href="<?= _url('index', 'index') ?>"><?= _t('gen.action.back_to_rss_feeds') ?></a>
	</div>

	<h1><?= _t('admin.stats.repartition') ?></h1>

	<select id="feed_select" class="select-change">
		<option data-url="<?= _url('stats', 'repartition') ?>"><?= _t('admin.stats.all_feeds') ?></option>
	<?php foreach ($this->categories as $category) {
		$feeds = $category->feeds();
		if (!empty($feeds)) {
			echo '<optgroup label="', $category->name(), '">';
			foreach ($feeds as $feed) {
				if ($this->feed && $feed->id() == $this->feed->id()) {
					echo '<option value="', $feed->id(), '" selected="selected" data-url="',
						_url('stats', 'repartition', 'id', $feed->id()), '">', $feed->name(), '</option>';
				} else {
					echo '<option value="', $feed->id(), '" data-url="',
						_url('stats', 'repartition', 'id', $feed->id()), '">', $feed->name(), '</option>';
				}
			}
			echo '</optgroup>';
		}
	}?>
	</select>

	<?php if ($this->feed) {?>
		<a class="btn" href="<?= _url('subscription', 'index', 'id', $this->feed->id()) ?>">
			<?= _i('configure') ?> <?= _t('gen.action.manage') ?>
		</a>
	<?php }?>

	<div class="stat">
		<table>
		<tr>
			<th><?= _t('admin.stats.status_total') ?></th>
			<th><?= _t('admin.stats.status_read') ?></th>
			<th><?= _t('admin.stats.status_unread') ?></th>
			<th><?= _t('admin.stats.status_favorites') ?></th>
		</tr>
		<tr>
			<td class="numeric"><?= $this->repartition['total'] ?></td>
			<td class="numeric"><?= $this->repartition['count_reads'] ?></td>
			<td class="numeric"><?= $this->repartition['count_unreads'] ?></td>
			<td class="numeric"><?= $this->repartition['count_favorites'] ?></td>
		</tr>
		</table>
	</div>

	<div class="stat">
		<h2><?= _t('admin.stats.entry_per_hour', $this->averageHour) ?></h2>
		<div id="statsEntryPerHour" class="statGraph"></div>
	</div>

	<div class="stat half">
		<h2><?= _t('admin.stats.entry_per_day_of_week', $this->averageDayOfWeek) ?></h2>
		<div id="statsEntryPerDayOfWeek" class="statGraph"></div>
	</div>

	<div class="stat half">
		<h2><?= _t('admin.stats.entry_per_month', $this->averageMonth) ?></h2>
		<div id="statsEntryPerMonth" class="statGraph"></div>
	</div>
</div>

<script id="jsonRepartition" type="application/json"><?php
echo htmlspecialchars(json_encode(array(
	'repartitionHour' => $this->repartitionHour,
	'repartitionDayOfWeek' => $this->repartitionDayOfWeek,
	'days' => $this->days,
	'repartitionMonth' => $this->repartitionMonth,
	'months' => $this->months,
), JSON_UNESCAPED_UNICODE), ENT_NOQUOTES, 'UTF-8');
?></script>
<script src="../scripts/repartition.js?<?= @filemtime(PUBLIC_PATH . '/scripts/repartition.js') ?>"></script>
