<?php $this->partial('aside_stats'); ?>

<div class="post ">
	<a href="<?php echo _url('index', 'index'); ?>"><?php echo _t('gen.action.back_to_rss_feeds'); ?></a>

	<h1><?php echo _t('admin.stats.repartition'); ?></h1>

	<select id="feed_select" class="select-change">
		<option data-url="<?php echo _url('stats', 'repartition')?>"><?php echo _t('admin.stats.all_feeds')?></option>
	<?php foreach ($this->categories as $category) {
		$feeds = $category->feeds();
		if (!empty($feeds)) {
			echo '<optgroup label="', $category->name(), '">';
			foreach ($feeds as $feed) {
				if ($this->feed && $feed->id() == $this->feed->id()){
					echo '<option value="', $feed->id(), '" selected="selected" data-url="', _url('stats', 'repartition', 'id', $feed->id()), '">', $feed->name(), '</option>';
				} else {
					echo '<option value="', $feed->id(), '" data-url="', _url('stats', 'repartition', 'id', $feed->id()), '">', $feed->name(), '</option>';
				}
			}
			echo '</optgroup>';
		}
	}?>
	</select>

	<?php if ($this->feed) {?>
		<a class="btn" href="<?php echo _url('subscription', 'index', 'id', $this->feed->id()); ?>">
			<?php echo _i('configure'); ?> <?php echo _t('gen.action.manage'); ?>
		</a>
	<?php }?>

	<div class="stat">
	    <table>
		<tr>
		    <th><?php echo _t('admin.stats.status_total'); ?></th>
		    <th><?php echo _t('admin.stats.status_read'); ?></th>
		    <th><?php echo _t('admin.stats.status_unread'); ?></th>
		    <th><?php echo _t('admin.stats.status_favorites'); ?></th>
		</tr>
		<tr>
		    <td class="numeric"><?php echo $this->repartition['total']; ?></td>
		    <td class="numeric"><?php echo $this->repartition['read']; ?></td>
		    <td class="numeric"><?php echo $this->repartition['unread']; ?></td>
		    <td class="numeric"><?php echo $this->repartition['favorite']; ?></td>
		</tr>
	    </table>
	</div>

	<div class="stat">
		<h2><?php echo _t('admin.stats.entry_per_hour', $this->averageHour); ?></h2>
		<div id="statsEntryPerHour" style="height: 300px"></div>
	</div>

	<div class="stat half">
		<h2><?php echo _t('admin.stats.entry_per_day_of_week', $this->averageDayOfWeek); ?></h2>
		<div id="statsEntryPerDayOfWeek" style="height: 300px"></div>
	</div><!--

	--><div class="stat half">
		<h2><?php echo _t('admin.stats.entry_per_month', $this->averageMonth); ?></h2>
		<div id="statsEntryPerMonth" style="height: 300px"></div>
	</div>
</div>

<script>
"use strict";
function initStats() {
	if (!window.Flotr) {
		if (window.console) {
			console.log('FreshRSS waiting for Flotr…');
		}
		window.setTimeout(initStats, 50);
		return;
	}
	// Entry per hour
	Flotr.draw(document.getElementById('statsEntryPerHour'),
		[{
			data: <?php echo $this->repartitionHour ?>,
			bars: {horizontal: false, show: true}
		}],
		{
			grid: {verticalLines: false},
			xaxis: {noTicks: 23,
				tickFormatter: function(x) {
					var x = parseInt(x);
					return x + 1;
				},
				min: -0.9,
				max: 23.9,
				tickDecimals: 0},
			yaxis: {min: 0},
			mouse: {relative: true, track: true, trackDecimals: 0, trackFormatter: function(obj) {return numberFormat(obj.y);}}
		});
	// Entry per day of week
	Flotr.draw(document.getElementById('statsEntryPerDayOfWeek'),
		[{
			data: <?php echo $this->repartitionDayOfWeek ?>,
			bars: {horizontal: false, show: true}
		}],
		{
			grid: {verticalLines: false},
			xaxis: {noTicks: 6,
				tickFormatter: function(x) {
					var x = parseInt(x),
					    days = <?php echo $this->days?>;
					return days[x];
				},
				min: -0.9,
				max: 6.9,
				tickDecimals: 0},
			yaxis: {min: 0},
			mouse: {relative: true, track: true, trackDecimals: 0, trackFormatter: function(obj) {return numberFormat(obj.y);}}
		});
	// Entry per month
	Flotr.draw(document.getElementById('statsEntryPerMonth'),
		[{
			data: <?php echo $this->repartitionMonth ?>,
			bars: {horizontal: false, show: true}
		}],
		{
			grid: {verticalLines: false},
			xaxis: {noTicks: 12,
				tickFormatter: function(x) {
					var x = parseInt(x),
					    months = <?php echo $this->months?>;
					return months[(x - 1)];
				},
				min: 0.1,
				max: 12.9,
				tickDecimals: 0},
			yaxis: {min: 0},
			mouse: {relative: true, track: true, trackDecimals: 0, trackFormatter: function(obj) {return numberFormat(obj.y);}}
		});

}
initStats();
</script>
