name: build-images

on:
  push:
    branches:
      - edge
  release:
  workflow_dispatch:

permissions:
  contents: read
  # packages: write

jobs:
  build-container-image:
    name: Image Build ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Debian
            file: Docker/Dockerfile
            flavor: |
              latest=auto
              suffix=,onlatest=false
          - name: Alpine
            file: Docker/Dockerfile-Alpine
            flavor: |
              latest=auto
              suffix=-alpine,onlatest=true
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        flavor: ${{ matrix.flavor }}
        images: |
          docker.io/freshrss/freshrss
      #     ghcr.io/${{ github.repository }}
        tags: |
          type=edge
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/0.') }}
        labels: |
          org.opencontainers.image.description="A self-hosted RSS feed aggregator"
          org.opencontainers.image.documentation="https://freshrss.github.io/FreshRSS/"
          org.opencontainers.image.url="https://freshrss.org/"

    - name: Login to DockerHub
      if: github.repository_owner == 'FreshRSS'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # - name: Login to GitHub Container Registry
    #   uses: docker/login-action@v3
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.repository_owner }}
    #     password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        file: ${{ matrix.file }}
        platforms: linux/arm/v7,linux/arm64,linux/amd64
        push: ${{ (github.ref == 'refs/heads/latest' || github.ref == 'refs/heads/edge' || startsWith(github.ref, 'refs/tags/') && github.repository_owner == 'FreshRSS' ) }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
