name: push readme to dockerhub

on:
  push:
    paths:
      - Docker/README.md
    branches:
      - latest
  workflow_dispatch:

jobs:
  push-docker-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Update repo description
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: freshrss/freshrss
        readme-filepath: Docker/README.md
